newrelic/newrelic-ruby-agent

lib/new_relic/agent/vm/rubinius_vm.rb
test/new_relic/agent/vm/rubinius_vm_test.rb

The commit 6038c791526f48b7d1b18d663432967a1e176d0d says it all. I'm currently deploying this to a production application to see how things look when presented in the RPM web interface. I'll update this pull-request once things look good from my end.

Updated RubiniusVM metrics for Rubinius 2.3.0.

---

lib/new_relic/agent/datastores/mongo/event_formatter.rb
lib/new_relic/agent/datastores/mongo/obfuscator.rb
lib/new_relic/agent/datastores/mongo/statement_formatter.rb
lib/new_relic/agent/instrumentation/mongodb_command_subscriber.rb
test/multiverse/suites/mongo/Envfile
test/multiverse/suites/mongo/mongo2_instrumentation_test.rb
test/new_relic/agent/datastores/mongo/event_formatter_test.rb
test/new_relic/agent/instrumentation/mongodb_command_subscriber_test.rb

@mwear This addresses most issues at stated here https://github.com/newrelic/rpm/pull/211#issuecomment-132009360
Responses to those questions:
1. `event.command.values.first` is guaranteed by our spec to always be the command name since `BSON::Documents` are ordered - it was an issue in the beta version of the Ruby driver, which is fixed in master and will be in the RC relase. I pointed the multiverse tests at master now instead of the beta.
2. The command that is issued will not always match the event name, as this is low level monitoring and we wanted to avoid any sort of method tracing in order to not break future the agent in future API changes to the driver. We also deemed it more important for a user to know exactly what was happening in the database... Ie a `find` can be a `find`, …

RUBY-1498: Event publishing with Mongo Ruby driver 2.1.0

---

lib/new_relic/recipes/capistrano3.rb
lib/new_relic/recipes/capistrano_legacy.rb

With many commits and no environment or config variable set, deploys will hang trying to report deployments and change sets to new relic.  To finish the deploy, you have to login to the server and kill the git process.  Then the deployment can complete.

Don't use a pager when running git log.  

---

lib/new_relic/agent/agent.rb
test/new_relic/agent/agent_test.rb

A bug in `Net::HTTP`'s Gzip decoder can cause the (un-catchable) thread-kill exception to be replaced with a (catchable) `Zlib` exception, which prevents a connecting agent thread from exiting during shutdown, causing the Ruby process to hang indefinitely.
This workaround checks for an 'aborting' thread in the #connect exception handler and re-raises the exception, allowing a killed thread to continue exiting.
Fixes #340.
https://bugs.ruby-lang.org/issues/13882#note-4
Includes a test (failing on `main`, passing on this PR) that minimally reproduces the issue described in https://github.com/newrelic/newrelic-ruby-agent/issues/340#issuecomment-661304946.

Prevent connecting agent thread from hanging on shutdown

---

CONTRIBUTING.md

Just a small change to documentation - the "closed issues" link in our CONTRIBUTING.md erroneously linked only to closed issues with the `enhancement` label - of which there actually aren't any.

Fix closed issues link

---

.travis.yml

Removed all versions of ruby except one, 2.6, from the travis matrix. We're moving over to github actions right now and can decrease the resources used on travis.
https://github.com/newrelic/newrelic-ruby-agent/issues/365

removed all versions of ruby except 2.6 for travis

---

test/multiverse/suites/agent_only/utilization_data_collection_test.rb

Previously, this test was failing in certain situations because it assumes there is no vendor information available in the environment. When the test runs in an environment where the information is available (like github actions), the test failed. This change ensures that no vendor information is gathered by the agent.

Fix test that fails when run in certain environments

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/troubleshooting.md

Adding an issue template so that troubleshooting tickets are redirected to the appropriate places. When creating a ticket now there is no longer an option to create a troubleshooting ticket, instead it redirects them to the support section of our README.

Add issue template config to clarify troubleshooting tickets

---

.github/workflows/ci.yml
.github/workflows/infinite_tracing_tests.yml
.github/workflows/pr_review_checklist.yml

Infinite tracing tests have frequent intermittent failures that cause our CI to be a bit rocky. The main agent also has some less frequent intermittent failures. Retrying the test runs when failing will help weed out the intermittent failures from true failures.

Add Retry to running tests

---

.github/workflows/stale.yml

Runs the stale action once a day to check for stale issues and pull requests. They will be marked as stale after 30 days, and then closed 5 days after that if there is no activity. 
These labels will prevent an issue from being marked as stale
- good first issue
- help wanted
- in progress
- in review
- on hold
https://github.com/newrelic/newrelic-ruby-agent/issues/387

Close stale issues and pull requests

---

lib/new_relic/agent/new_relic_service.rb
test/new_relic/agent/new_relic_service_test.rb

The ruby agent previously used a root SSL/TLS certificate bundle by default. Now the agent will attempt to use the default system certificate, but will fall back to the bundled cert if there is an issue (and log that this occurred). 
Requirement for https://github.com/newrelic/newrelic-ruby-agent/issues/351
Github Actions when a pull request is made. More details on running the tests locally can be …

Use System Certificates by default

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/rake.rb

When running a Rails application with rake tasks, customers could see the following error:
```
ERROR : Error while detecting rake_instrumentation:
ERROR : NameError: uninitialized constant Rake::VERSION
```
This is because a very small piece of Rake is loaded with [the Rails test runner](https://github.com/rails/rails/blob/9734dfa1a1a2d5909652dcbb80947a92ce42c431/railties/lib/rails/test_unit/runner.rb#L5).
On this branch, we're checking to see if `Rake::VERSION` exists before going further with determining whether to install rake instrumentation. This does not seem to have any ill effects on our normal rake instrumentation.
#338 - thanks to @CamilleDrapier for reporting this!
Verified in my logs that the error does not appear, and there was no breakage of existing tests when run locally. …

Check Rake::VERSION is defined before checking for supported versions

---

CHANGELOG.md
lib/new_relic/agent/agent.rb
test/new_relic/agent/agent_test.rb

Please see #359 for discussion on the original PR. Our CI is in a bit of an intermediate state right now as we migrate to GitHub actions, so we created a branch to make sure this passed our internal Travis CI, which it does. Reopening so we can continue to evaluate our options for fixing this issue.
Thank you again for your submission, @wjordan!

PR 359: Prevent reconnect attempts during shutdowns

---

lib/new_relic/agent/transaction/segment.rb
test/performance/README.md

Previously, our segments were always creating an attributes object in the initializer. Moving the creation of the attributes object to when it is actually being used decreased allocations by 21% in a basic middleware performance test.
Results:
```
+--------------------------------------------+-----------+-----------+-------+---------------+--------------+--------------+
| name                                       | before    | after     | delta | allocs_before | allocs_after | allocs_delta |
|--------------------------------------------+-----------+-----------+- …
```

Decrease allocations for span attributes

---

CHANGELOG.md
lib/new_relic/agent/new_relic_service.rb
test/agent_helper.rb
test/multiverse/suites/config_file_loading/config_file_loading_test.rb
test/new_relic/agent/new_relic_service_test.rb

Stealing shamelessly from @astormnewrelic's [excellent explanation of this issue](https://github.com/newrelic/node-newrelic/issues/462). 😄 
When connecting to New Relic, the Ruby Agent uses the value in `Agent.config[:host]` to post a request to the New Relic preconnect endpoint. This endpoint returns a "redirect host", which (at the time of this writing) often looks like one of the following:
```
collector-00n.newrelic.com
gov-collector-00n.newrelic.com
```
This URL becomes the URL that agents will send data to.
There is a bug in the Ruby Agent related to this functionality. If the agent needs to reconnect to the collector, it will incorrectly use this redirect host to call the preconnect endpoint, when instead it should use the original configured value in `Agent.config[:host]`.
The …

Ensure preconnect never uses redirect host

---

.github/workflows/stale.yml

A simple change to make sure issues on our roadmap are not marked as stale.

Add roadmap to list of stale action excluded labels

---

CHANGELOG.md
lib/new_relic/version.rb
test/performance/README.md

Updating the version constants and CHANGELOG for our upcoming release of 6.13.0 of the agent.

Release preparation for version 6.13.0

---

test/multiverse/suites/sidekiq/Envfile

Sidekiq multiverse tests started failing today because of an incompatibility between a new version of the `timers` gem and Ruby 2.0.0. Pinned `timers` in the Envfile to fix.

Pin timers gem to 4.1.1. for Sidekiq ~> 3.5.3 multiverse

---

CONTRIBUTING.md

I noticed that our documentation on testing in our CONTRIBUTING.md file is no longer accurate since we have now migrated to GitHub actions. Additionally, we no longer run unit tests in a Rails environment by default, so I added some instructions on how to do that.

Update test running instructions in CONTRIBUTING.md

---

newrelic_rpm.gemspec

Another small fix to our release workflow: removing the outdated reference to a repo-specific Code of Conduct (we're now using the organization-level one) from the agent's gemspec.

Remove reference to repo-specific CoC from gemspec

---

.github/workflows/release.yml
.github/workflows/scripts/ruby-gems-authenticate.rb

Additional fixes for the release workflow
* ensure rubygems is up-to-date
* install rotp and base32 gems in one shot
* set environment var for the MFA key

Fixes rubygems mfa

---

CHANGELOG.md
lib/new_relic/agent/http_clients/uri_util.rb
test/new_relic/agent/http_clients/uri_util_test.rb

A recent change to the Ruby agent to obfuscate URIs sent to external services had the unintended side-effect of removing query parameters from the original URI.  This is fixed to obfuscate while also preserving the original URI
Resolves #451 and potentially #450.

resolves Issue 451 and possibly 450

---

CHANGELOG.md
lib/new_relic/agent/http_clients/uri_util.rb
lib/new_relic/version.rb
test/new_relic/agent/http_clients/uri_util_test.rb

Prevents original URI objects from be modified when obfuscated.

---

newrelic_rpm.gemspec

This pull request reduces gem package size.
Currently newrelic_rpm gem package is 4.5MB after unzip. We can confirm the size with `du` command.
For example
```bash
$ cd path/to/installed/dir/lib/ruby/gems/2.7.0/gems
$ du newrelic_rpm-6.13.1/ --summarize -h
4.5M    newrelic_rpm-6.13.1/
```
And `.github` directory occupies half of the size.
```bash
$ du newrelic_rpm-6.13.1/* --summarize -b | sort -n | tail
7933    newrelic_rpm-6.13.1/README.md
9317    newrelic_rpm-6.13.1/config.dot
11571   newrelic_rpm-6.13.1/LICENSE
13169   newrelic_rpm-6.13.1/bin/
17626 …
```

Reduce gem package size

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/rack.rb

This PR skips all middleware processing in the case that a `nil` value exists in the middleware chain. Sorry the diff is rendering weird - the only actual change is checking for `nil` here.
Here's the [internal ticket](https://newrelic.atlassian.net/browse/GTSE-3080) where the bug was reported through support. The customer was seeing `nil` passed in as a middleware (reason unknown on their end), resulting in error messages such as `NoMethodError: undefined method `new' for nil:NilClass`.
This is confirmed to have solved the customer's issue and we should get …

Add checks for nil middleware class in use_with_newrelic

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/redis.rb

When attempting to detect Redis, an error is raised and logged:
```
[2020-10-02 14:10:49 -0400 C02ZH0B1LVDT (37897)] INFO : Environment: development
[2020-10-02 14:10:49 -0400 C02ZH0B1LVDT (37897)] INFO : No known dispatcher detected.
[2020-10-02 14:10:49 -0400 C02ZH0B1LVDT (37897)] INFO : Application: Performance Test (development)
[2020-10-02 14:10:49 -0400 C02ZH0B1LVDT (37897)] WARN : Agent configured not to send data in this environment.
[2020-10-02 14:10:49 -0400 C02ZH0B1LVDT (37897)] DEBUG : New Relic Ruby Agent 6.13.1 Initialized: pid = 37897
[2020-10-02 14:10:49 -0400 C02ZH0B1LVDT (37897)] DEBUG : NewRelic::Agent.config[:disable_redis] == false => true
[2020-10-02 14:10:49 -0400 C02ZH0B1LVDT (37897)] ERROR : Error while detecting redis_instrumentation:
[2020-10-02 14:10:49 -0400 …
```

fixes dependency check for Redis instrumentation

---

CHANGELOG.md
lib/new_relic/agent/samplers/memory_sampler.rb

Updated the regex in the memory sampler to recognize the new macos, Big Sur. Big sur platform output is `x86_64-darwin20`, so adding 1 or 2 catches this new OS as well. 
https://github.com/newrelic/newrelic-ruby-agent/issues/474 …

Updated the memory sampler to recognize macOS Big Sur

---

lib/new_relic/agent/instrumentation/action_view_subscriber.rb
lib/new_relic/agent/instrumentation/notifications_subscriber.rb
lib/new_relic/agent/stats_engine/gc_profiler.rb
lib/new_relic/supportability_helper.rb
test/new_relic/agent/monitors/trace_context_request_monitor_test.rb
test/new_relic/agent/span_event_primitive_test.rb
test/performance/README.md
test/performance/lib/performance/baseline_compare_reporter.rb
test/performance/lib/performance/instrumentation/gc_stats.rb
test/performance/lib/performance/runner.rb
test/performance/script/runner
test/performance/suites/logging.rb
test/performance/suites/redis.rb
test/performance/suites/thread_profiling.rb
test/performance/suites/trace_context.rb
test/performance/suites/trace_context_request_monitor.rb
test/performance/suites/transaction_tracing.rb

To have a repeatable process for tracking and detecting memory leaks, the performance tests were improved to 
track GC.stats[:old_objects] with capability to baseline then compare.  Performance tests were enhanced to
flush stats for old_objects by running major GC sweeps three times, disabling GC during test runs, then re-enabling and running 3 times after the test run.  This ensures consistent tracking and baselining.
The `test/performance/README.md` was also updated for correctness as running the tests while homed to the repo's root folder did not quite work as advertised.  The performance test now also correctly loads the Ruby agent before running whereas before would complain about not finding specific files.
Minor typos, misspellings, etc. were fixed in comments.

tracks retained objects in memory profiler for Performance tests

---

infinite_tracing/newrelic-infinite_tracing.gemspec

`rake` command for this repository fails with Ruby 3.0.0-preview1 (and the latest dev version of Ruby).
```bash
$ rbenv shell 3.0.0-preview1
$ ruby -v
ruby 3.0.0preview1 (2020-09-25 master 0096d2b895) [x86_64-linux]
$ bundle exec rake -T
bundler: failed to load command: rake (/home/pocke/.rbenv/versions/3.0.0-preview1/bin/rake)
Bundler::GemspecError: 
[!] There was an error while loading `newrelic-infinite_tracing.gemspec`: uninitialized constant FileUtils
Did you mean?  FileTest. Bundler cannot continue.
>        FileUtils.cp source_full_filename, dest_full_filename
/home/pocke/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/bundler.rb:645:in `rescue in eval_gemspec'
/home/pocke/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/bundler.rb:636:in `eval_gemspec' …
```

Enable rake task to work with Ruby 3.0.0-preview1

---

lib/new_relic/environment_report.rb

This PR is really just to silence this Rails 6.1 deprecation warning
```
DEPRECATION WARNING: The kwarg `spec_name` is deprecated in favor of `name`. `spec_name` will be removed in Rails 6.2 (called from block in <class:EnvironmentReport> at /Users/tomgilligan/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/newrelic_rpm-6.13.1/lib/new_relic/environment_report.rb:74)
DEPRECATION WARNING: DatabaseConfig#config will be removed in 6.2.0 in favor of DatabaseConfigurations#configuration_hash which returns a hash with symbol keys (called from block in <class:EnvironmentReport> at /Users/tomgilligan/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/newrelic_rpm-6.13.1/lib/new_relic/environment_report.rb:74)
```
No tests introduced thus far.  Probably it'd be nice to introduce a Rails 6.1 …

Use connection_db_config if it's available

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb

Adds `newrelic.yml.erb` to the list of directories and files searched at start up.
Resolves #493

restores .erb to the search paths for config files

---

CHANGELOG.md
lib/new_relic/agent/audit_logger.rb
lib/new_relic/agent/distributed_tracing/cross_app_tracing.rb
lib/new_relic/agent/new_relic_service.rb
lib/new_relic/agent/transaction/distributed_tracer.rb
lib/new_relic/agent/transaction/message_broker_segment.rb
test/new_relic/agent/transaction/external_request_segment_test.rb

HTTP request headers will be logged when log level is at least debug level.  
Similarly, request headers for exchanges with New Relic servers are now audit logged when audit logging is enabled.
This resolves #472

request headers are now logged

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/middleware_proxy.rb
lib/new_relic/agent/instrumentation/rack.rb

When adapting the agent for Ruby 2.7, we were over-zealous in making changes to support Ruby 2.7.  Rack, and therefore, RackApp do not pass keyword arguments, so it was unnecessary change to double-splat the last argument in the rack instrumentation.
Resolves #486 
Resolves #487

fixed overzealous 2.7 changes

---

.github/workflows/assignproj.yml
.github/workflows/ci.yml
.github/workflows/pr_review_checklist.yml
.github/workflows/release.yml

- Changed release workflow so it is no longer using the deprecated `set-env`, and is now using [`$GITHUB_ENV`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable). 
- Pulled infinite tracing tests into a separate job in the same CI workflow. This enables us to bump up the retry limits for only infinite tracing, which has the most intermittent failures. This makes it so that we don't have to wait even longer in the case of real failures in other parts of the agent unrelated to …

Updates for our github action workflows

---

.github/workflows/ci.yml
CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/net.rb
lib/new_relic/agent/instrumentation/net_prepend.rb
test/multiverse/lib/multiverse/runner.rb
test/multiverse/suites/net_http/config/newrelic.yml
test/multiverse/suites/net_http_prepend/Envfile
test/multiverse/suites/net_http_prepend/config/newrelic.yml
test/multiverse/suites/net_http_prepend/net_http_prepend.rb
test/new_relic/net_http_test_cases.rb

This change adds a new config option to enable the instrumentation of Net::HTTP to use prepend rather than monkey patching. 
https://github.com/newrelic/newrelic-ruby-agent/issues/347
Added a new test suite `net_http_prepend`. I pulled out all of the existing work in net_http test suite into a helper module and included that in both `net_http_prepend` and `net_http`. These needed to be in separate suites because the instrumentation is set up when the agent starts, and cannot switch instrumentation implementations while running.

Add prepend option for Net::HTTP instrumentation

---

lib/new_relic/agent/instrumentation/net.rb
lib/new_relic/agent/instrumentation/net_prepend.rb
lib/new_relic/dependency_detection.rb

resolves #510 where infinite recursion error occurs when both the Ruby agent and Airbrake are loaded in a Rails project.  Airbrake and the Ruby agent both are monkey patching the Net::HTTP#request method in order to benchmark.  When prepend method of patching is used, we end up with an infinite recursion issue since the two approaches cannot be used together.
Closes #510

resolve infinite recursion when airbrake is present

---

lib/new_relic/cli/commands/deployments.rb
test/new_relic/agent_test.rb

Removed all instances of require 'rexml/document' in the agent.
Added Passwd and Group to our deprecated constants list in our agent test
closes #491

Remove warnings from tests in ruby 3.0.0-preview1

---

CHANGELOG.md
lib/new_relic/agent/span_event_primitive.rb
lib/new_relic/agent/transaction/abstract_segment.rb
lib/new_relic/supportability_helper.rb
test/new_relic/agent/span_event_primitive_test.rb

Multiple bugs were encountered and fixed while exploring issue with why certain Sidekiq processes were not recording calls to external services.  Principally, when an error is noticed and recording such against a span/segment that does not have any custom attributes, a Cannot modify Frozen Hash exception would result and agent attributes for the span/segment would not be collected.  It is not known at this time whether these bugfixes resolve the original observation of not seeing external calls/spans in the UI, but nevertheless, these bugs are now fixed.
* closes #518 
* closes #519 
* closes #520

multiple bug fixes

---

infinite_tracing/lib/infinite_tracing/client.rb
infinite_tracing/test/infinite_tracing/connection_test.rb
infinite_tracing/test/support/fake_trace_observer.rb
infinite_tracing/test/support/fake_trace_observer_helpers.rb

Implements handing FAILED_PRECONDITION responses from the server.
Closes #509

509 handle failed precondition response

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
test/multiverse/suites/net_http_prepend/config/newrelic.yml

We've had a few issues come through where prepend instrumentation on Net::HTTP is causing compatibility issues with gems that are still using monkey patching on the same objects. For now, we should change the default behavior back to monkey patching to prevent unexpected problems to arise for customers using gems that monkey patch. We should revisit this change when we do our major shift to prepend in our next major release. 
https://github.com/newrelic/newrelic-ruby-agent/issues/530
https://github.com/newrelic/newrelic-ruby-agent/issues/510

Default net_prepend_instrumentation to false

---

.github/workflows/ci.yml

A new preview for ruby 3 has been released, `3.0.0-preview2`. This PR updates all CI running on preview1 to preview2.

Upgrade ruby 3 preview version

---

infinite_tracing/CHANGELOG.md
infinite_tracing/lib/infinite_tracing/connection.rb
infinite_tracing/test/infinite_tracing/connection_test.rb
lib/new_relic/agent/new_relic_service.rb

Adds the key-value pairs from `request_headers_map` (in the agents connect response) to the metadata used in connecting to the infinite trace observer. The keys are all downcased per the spec.
closes #508 
All the existing connection tests on metadata have been updated to include these changes

Add connect response data to infinite trace metadata

---

lib/new_relic/agent/instrumentation/sidekiq.rb

We are using Shoryuken to pull from SQS and push to Sidekiq. This is a small slice of logic that we don't want monitored with with New Relic, but we do want to connect the distributed tracing that is happening from the Ruby application on the other side of SNS. Our Shoryuken worker is putting the key in place and it is being overwritten by sidekiq.
I can have our application delete the New Relic client sidekiq middleware within shoryuken, but I figured it'd be sharing what I ran into here as well.
Maybe `::NewRelic::Agent.config[:'distributed_tracing.enabled']` …

Don't overwrite existing sidekiq trace info.

---

lib/new_relic/agent/vm/mri_vm.rb

This change fixes the 2 test suites that are currently failing in `dev` for `3.0.0-preview2`.
https://github.com/ruby/ruby/commit/278450de803c59137fff69c4db03cd40c5b5d08a

Ruby 3 has removed :global_method_state from VM stats

---

.github/workflows/ci.yml
lib/new_relic/agent.rb
lib/new_relic/agent/database_adapter.rb
lib/new_relic/environment_report.rb
test/environments/rails61/Gemfile
test/environments/rails61/Rakefile
test/environments/rails61/config/application.rb
test/environments/rails61/config/boot.rb
test/environments/rails61/config/database.yml
test/environments/rails61/config/environment.rb
test/environments/rails61/db/schema.rb

The adapter lookup in Rails 6.1 is raising an error which is caught by the rescue block. However, the lookup in the rescue block is producing a deprecation warning that will be removed in Rails 6.2.

Fix database adapter lookup for Rails 6.1

---

lib/new_relic/agent/distributed_tracing.rb
lib/new_relic/supportability_helper.rb

We did implement custom version of distributed tracing in Sidekiq when it was not available back in time. In the logs, after upgrading newrelic_rpm gem, I've noticed following:
```
[2021-01-26 13:17:16 +0000 host.local (44425)] WARN : The method create_distributed_trace_payload is deprecated.
[2021-01-26 13:17:16 +0000 host.local (44425)] WARN : Please use create_distributed_trace_headers instead.
```
Problem is, `create_distributed_trace_headers` never existed. What we should use is `insert_distributed_trace_headers`.
It's not required, no code changes.

Remove reference to non-existing create_distributed_trace_headers method

---

lib/new_relic/agent/transaction.rb

Transaction nesting_max_depth can get out of sync with segments length resulting in an exception when attempting to nest the initial segment which does not exist.
https://github.com/newrelic/newrelic-ruby-agent/issues/545
Existing test coverage ensures that the behaviour of nesting_max_depth is unchanged

Ensure transaction nesting max depth is always consistent with length of segments

---

lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/httpclient.rb
lib/new_relic/agent/instrumentation/httpclient/chain.rb
lib/new_relic/agent/instrumentation/httpclient/prepend.rb
test/multiverse/suites/httpclient/Envfile
test/multiverse/suites/httpclient/config/newrelic.yml

Updated HTTPClient gem instrumentation to have both prepend and chain options hooked up and defaults to prepend.
closes #584

Implement prepend instrumentation for HTTPClient

---

test/new_relic/agent/transaction_sampler_test.rb

While looking at https://github.com/newrelic/newrelic-ruby-agent/pull/575 I noticed the two helper functions are never used anymore.

Remove unused functions in test

---

infinite_tracing/newrelic-infinite_tracing.gemspec

The gemspec for infinite tracing had the required minimun ruby version as 2.3, however the correct minimum ruby version is 2.5. Our CI has already been reflecting that we support 2.5+, so this change is just to our gemspec to more accurately reflect the ruby versions infinite tracing is expected to run on.

Fix required ruby version for infinite tracing

---

lib/new_relic/agent/configuration/default_source.rb

Rails recently bumped its version number, which breaks the NewRelic agent.

Support current Rails edge

---

lib/new_relic/agent/instrumentation/middleware_proxy.rb
test/new_relic/agent/instrumentation/middleware_proxy_test.rb

Passing keyword arguments to `middleware_class` in MiddlewareProxy is broken in ruby 3.0. It's fine, when middleware doesn't require `keyword arguments. Bu when it doesn't they are passed as an hash argument.
Here is an example issue from with honeycomb integration:
For most contributions it is strongly …

Fix passing keyword arguments in ruby 3.0

---

.github/actions/build-ruby/index.js
test/multiverse/lib/multiverse/suite.rb
test/new_relic/fake_server.rb

The `httpclient` suite can take well over 30 minutes to run approximately 4 minutes worth of tests with jRuby.  This PR introduces the --dev flag for jRuby environments that brings that overall runtime down to around 6 minutes.
Resolves #637  …

Speedup jruby

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/net_http.rb
lib/new_relic/agent/instrumentation/redis.rb
lib/new_relic/agent/instrumentation/resque.rb

Adds recently reported prepend conflicts to our checks before installing instrumentation. This will allow the agent to choose chain instrumentation instead of the default of prepend if the config setting is 'auto'. Setting the config value to prepend explicitly will bypass these checks.
https://github.com/newrelic/newrelic-ruby-agent/issues/659 (redis & net_http)
https://github.com/newrelic/newrelic-ruby-agent/issues/656 (resque & net_http)

Add recently reported prepend conflicts

---

lib/new_relic/agent/configuration/default_source.rb

This fix is for #658  to find all instances of using HTML links in the config descriptions and change them to Markdown.
This change converts all of the HTML <a href></a> style links in the config descriptions to be markdown style links, and it converts the absolute paths to relative paths.
#658
All of the existing default_source tests still pass.

Change HTML links to Markdown links.

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/active_record_subscriber.rb
test/new_relic/agent/instrumentation/rails/active_record_subscriber.rb

As of Rails 6.1, ActiveRecord instrumentation does not provide `connection_id` in the payload for "sql.active_record". The agent currently expects this key to be there; in 6.1, this results in no connection config being fetched, and the default vendor falls back to "ActiveRecord" rather than the appropriate database name - other side effects may also be occurring.
The nature of this fix should ensure no behavior changes for the agent in existing Rails installations. `connection` will be used if present; otherwise it will fall back to `connection_id` (the previous behavior).
Also updated the unit test `test_active_record_config_for_event` to cover both pre- and post-Rails 6.1. This test was not working as intended and has been branched into two new tests.
Fixes …

Use `connection` from sql.active_record payload over `connection_id`

---

test/multiverse/suites/httprb/Envfile

This PR just comments out our testing of latest release of [httprb](https://github.com/httprb/http). 
We typically test the latest release as part of our CI, so that if a gem we instrument releases a new version that breaks our instrumentation we are aware of it. Httprb 5.0.0 was released, and appears to to break our instrumentation. We will need to investigate the changes and update our instrumentation to support this new version. However, in the meantime we will be removing this version from being tested in our CI until we add support for the changes made in …

Remove httprb 5.0.0 from test suite

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/sinatra/instrumentation.rb

Unfortunately, part of the bugfix in [this PR](https://github.com/newrelic/newrelic-ruby-agent/pull/564) was accidentally overwritten when we made our prepend changes for 7.0.0. The only effected section of code was in the `lib/new_relic/agent/instrumentation/sinatra.rb` file [here](https://github.com/newrelic/newrelic-ruby-agent/pull/564/files#diff-1590c5124311e7422410bf0489dd50d1c309f71699d69efe6a008ec639900674R104-R112). This code was moved to the file `lib/new_relic/agent/instrumentation/sinatra/instrumentation.rb`, but the new changes were missed in this …

Fix for overwritten bugfix in #564

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb

https://github.com/newrelic/newrelic-ruby-agent/issues/670
Enabled SSC for distributed tracing in the Ruby agent. Tested in a sample application, verified that enabling/disabling DT in NR1 sends the signal to force restart the agent, and the configs are correctly updated. *Note: tested in prod as staging reconnect issue is still being investigated.*
Cross-app spec for DT was reviewed. The only change here is to allow `distributed_tracing.enabled` from the server; existing config combinations should continue working as intended.

allow distributed_tracing.enabled to be set from server

---

CHANGELOG.md
lib/new_relic/agent/sql_sampler.rb
test/new_relic/agent/sql_sampler_test.rb

In order to allow the agent to run in FIPS compliant servers, we have replaced the uses of md5 with SHA1 when we are hashing the slow sql id in order to aggregate slow sql traces. 
The other use of md5 in the agent is in Cross Application Tracing (CAT), and can not be updated in order to keep it in line with agent specs. This means that CAT can not be used on FIPS compliant servers, distributed tracing should be used instead.
closes #602

Update md5 use in the sql_sampler to SHA1

---

lib/new_relic/agent/new_relic_service.rb

This PR is a workaround for the issue happening with the staging collector. The issue this PR addresses only impacts internal New Relic teams that are using the agent to report to the staging collector.
This makes a change to the logic added in PR https://github.com/newrelic/newrelic-ruby-agent/pull/406 when making a preconnect request. The changes present in that pull request work correctly on production, but currently the staging collector is having issues when using the original configured collector. This change will allow the agent to use the redirect host for all preconnect requests rather than the configured collector. 
This change is intended to be a temporary workaround until the issue is resolved with the staging collector. 
closes #657

Workaround for 403 response when using the staging collector

---

CHANGELOG.md
lib/new_relic/agent.rb
lib/new_relic/agent/javascript_instrumentor.rb
test/new_relic/agent/javascript_instrumentor_test.rb
test/new_relic/rack/browser_monitoring_test.rb

This PR adds support for CSP nonces when injecting the browser agent for our API method `browser_timing_header`. This change was implemented in a way that is in line with the other language agents, based on the updated agent specs for the Browser Monitoring API. 
In order to utilize this change, you must disable auto instrumentation for the browser agent, and use the API method `browser_timing_header` to inject the script manually.
Example:
```
<html>
<head>
<%= ::NewRelic::Agent.browser_timing_header("nonce") %>
...
</head>
<body>
```
closes #332

Add support for CSP nonces when injecting the browser agent

---

test/multiverse/suites/rack/Envfile

https://github.com/newrelic/newrelic-ruby-agent/issues/652
Update rack multiverse Envfile for Rack versions 2.0 and 2.2, Puma versions 4 and 5. Added a version check so Rack 2.2 on runs in Ruby 2.3+.
I tried to follow the intent of existing Puma 3.11 tests which run against both Rack 1.6 and Rack 2.0. Only Rack 2.0 and up have Ruby version requirements, and certain tests only run if Puma is present, so I included all of these combinations for Puma 3 and up.

update rack and puma versions in multiverse

---

lib/new_relic/agent/instrumentation/resque.rb

Airbrake released a new version, 11.0.3, that updates their use of method chaining on Resque::Job to use Module#prepend instead. I've updated our prepend conflict check for resque to add the new version so that the agent correctly chooses prepend when using the this airbrake version or higher.
https://github.com/newrelic/newrelic-ruby-agent/issues/668 …

Updates resque prepend conflict check

---

lib/new_relic/agent/instrumentation/rack/chain.rb
lib/new_relic/agent/instrumentation/rack/prepend.rb
test/multiverse/suites/rack/example_app.rb
test/multiverse/suites/rack/rack_auto_instrumentation_test.rb

Prior to this change, in Ruby 3.0, using a middleware with keyword arguments would fail with an `ArgumentError`.
This fix is pretty much the same as https://github.com/rack/rack/pull/1505

Fix Rack instrumentation for "kwarg middlewares" in Ruby 3.0

---

lib/new_relic/agent.rb
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/configuration/manager.rb
lib/new_relic/agent/error_collector.rb
lib/new_relic/agent/error_filter.rb
lib/new_relic/noticed_error.rb
test/multiverse/suites/rails/error_tracing_test.rb
test/new_relic/agent/error_collector_test.rb
test/new_relic/agent/error_filter_test.rb

This PR implements Expected Errors in the Ruby agent, and allows server-side configuration for ignored/expected error classes and messages. This PR does NOT implement ignoring/expecting errors by status code; this will be addressed in a future PR.
Formerly the error collector only used a single config setting for ignored error classes and stored this in an instance variable. In this PR, the work of loading ignored/expected errors and determining at runtime whether an error is ignored/expected/neither is handled by the `ErrorFilter` class, which is instantiated …

Implement Expected/Ignored errors

---

CHANGELOG.md

This pr adds 7.2.0 to the changelog and adds entries for merged community PRs …

Add upcoming 7.2.0 to changelog

---

.github/workflows/release.yml

instead of tagging
Updates our release workflow to use this action https://github.com/softprops/action-gh-release to create a release on github instead of just tagging the release like we've been doing. This should make it clearer to users looking at our release page on github what has been released.
This is something that's hard to try out the whole thing until we are ready to actually release, so if any issues with this change pop up when we release I'll need to deal with them at that time. 
closes #699

Update release workflow to create github release

---

lib/new_relic/agent/error_collector.rb
lib/new_relic/agent/error_filter.rb
test/multiverse/suites/sinatra/sinatra_error_tracing_test.rb
test/new_relic/agent/error_collector_test.rb
test/new_relic/agent/error_filter_test.rb
test/new_relic/multiverse_helpers.rb

One more Expected Errors change that didn't make it into #704. This commit ensures that if SSC sends an empty array to the agent, this will not overwrite any locally-set expected/ignored errors.
Also fixes Error Filter to accept integers as status codes (as these will be sent by SSC as integers).

Ensure blank SSC settings don't overwrite local expected errors

---

lib/new_relic/agent/method_tracer.rb

Should be a simple update to use the `assemble_code_header` in `NewRelic::Agent::MethodTracer.method_with_push_scope` as it is used in `.method_without_push_scope` for consistency. Should not change any functionality.
Note these methods will likely be refactored in the course of working on #502.
https://github.com/newrelic/newrelic-ruby-agent/issues/716

Use `assemble_code_header` in `method_with_push_scope`

---

test/environments/rails61/Gemfile

* Upgrade rack version used in Rails 6.1 tests to 2.1.4 or above to avoid a high severity CVE
* Small syntax changes to the Gemfile to support community standards
https://github.com/newrelic/newrelic-ruby-agent/issues/736
[here for our unit tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/ …

Update rack < 2.1.4 for Rails 6.1 tests

---

lib/new_relic/agent/external.rb
lib/new_relic/agent/http_clients/abstract.rb
lib/new_relic/agent/messaging.rb
lib/new_relic/agent/span_event_aggregator.rb
lib/new_relic/agent/tracer.rb
lib/new_relic/agent/transaction/message_broker_segment.rb

Our agent has code that provides compatibility for required keyword arguments in Ruby versions below 2.1. Since the agent supports Ruby 2.2+, this code is no longer required.
Also added parentheses to method definitions where applicable, for the sake of consistency and readability.

Remove Ruby 2.0 required kwarg compatibility checks

---

lib/new_relic/agent/configuration/default_source.rb

Suggested documentation change to clarify the scope of the `rules.ignore_url_regexes` configuration. This reflects a similar update made in the Ruby Agent docs.
Closes https://github.com/newrelic/newrelic-ruby-agent/issues/729

Update config description for rules.ignore_url_regexes

---

lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/distributed_tracing/cross_app_tracing.rb
lib/new_relic/agent/monitors/cross_app_monitor.rb
test/new_relic/agent/monitors/cross_app_monitor_test.rb

Update the location of the CAT deprecation message and the accompanying text.
The previous location printed a message to the logs every time an external request is made. By moving the message to `CrossAppMonitor`, it will only be printed when CAT is initialized. 
#551  …

Update CAT deprecation message

---

CHANGELOG.md
lib/new_relic/agent/configuration/yaml_source.rb
lib/new_relic/agent/instrumentation/sidekiq.rb
test/multiverse/suites/active_record/config/database.rb
test/multiverse/suites/config_file_loading/Envfile
test/multiverse/suites/config_file_loading/config_file_loading_test.rb

Uses the `YAML.unsafe_load` method when it is available, otherwise will still use YAML.load in older psych versions.
closes #759  …

added YAML.unsafe_load if the method is available

---

CHANGELOG.md
lib/new_relic/agent/configuration/dotted_hash.rb
lib/new_relic/agent/configuration/manager.rb
lib/new_relic/agent/configuration/yaml_source.rb
test/config/newrelic.yml
test/new_relic/agent/configuration/yaml_source_test.rb

The way we load our config file was unable to properly handle hash values, which are now needed for certain configuration values (`error_collector.ignore_messages`, `error_collector.expected_messages`). This fix adds a constant for config values that have a hash type as the value of the configuration option, which we check while we are flattening the config file.
verify your changes don't break existing functionality. These …

Load hash value for configuration option from yaml file

---

.github/workflows/ci.yml
test/multiverse/suites/httprb/Envfile
test/multiverse/suites/httprb/httprb_test.rb
test/new_relic/agent/stats_engine/stats_hash_test.rb

This PR fixes the breaking change httprb 5.0.0 introduces into our test suite, and adds that version back to our multiverse testing. The change made that caused the failures was related to this change https://github.com/httprb/http/pull/546. Our instrumentation was not affected, but our test suite needed to be updated to create response objects correctly in 5.0.0. 
closes https://github.com/newrelic/newrelic-ruby-agent/issues/674
verify your changes don't break existing …

Update for httprb 5.0.0

---

CHANGELOG.md
lib/new_relic/agent/external.rb
test/new_relic/agent/external_test.rb
test/new_relic/agent/supportability_test.rb

Per 7.x->8.x migration guide and changelog for 6.0, `NewRelic::Agent::External#start_segment` is deprecated. There were no explicit uses of this method within the code outside of tests.
As @angelatan2 pointed out, this method was not marked deprecated within the actual API documentation here:
https://rubydoc.info/github/newrelic/newrelic-ruby-agent/NewRelic/Agent/External:start_segment
Closes #746

Remove deprecated method External#start_segment

---

CHANGELOG.md
lib/new_relic/agent/monitors/cross_app_monitor.rb
newrelic.yml

Updated wording related to DT and CAT. …

Updated text

---

CHANGELOG.md

Adds some new entries to the changelog for 8.0.0

Update changelog for 8.0.0

---

lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/error_filter.rb
test/new_relic/agent/error_filter_test.rb

- Fixes bug where agent errors on ignore_status_codes with Integer values, identified in https://github.com/newrelic/newrelic-ruby-agent/issues/713
- Adds a test to confirm that the fix works
https://github.com/newrelic/newrelic-ruby-agent/issues/713
- Additional config added to existing test to verify that Integer status codes can pass

Accept Integers for ignored status codes in YAML config

---

test/multiverse/suites/rails/Envfile

Now that JRuby has pushed a fix for i18n, the version restrictions for JRuby can be removed from the Rails multiverse Envfile. There were also restrictions on Thor version related to another bug. I removed the Thor restrictions and the tests passed locally.
Closes: https://github.com/newrelic/newrelic-ruby-agent/issues/560 
Github Actions when a pull request is made. More details on running the tests …

Remove resolved thor and i18n restrictions for jruby

---

lib/new_relic/agent/method_tracer.rb
test/new_relic/agent/method_tracer_test.rb

Fixes #789 
When using `add_method_tracer`, the created tracer method called `self.class.trace_execution_[un]scoped`; however, `Kernel#class` is not available on BasicObjects. The tracer method is updated here to call `::NewRelic::Agent::MethodTracer.trace_execution_scoped` as these are effectively static methods. A new test case has been added for adding method tracers to BasicObjects.
Note that the above method call relies on the fact that `MethodTracer` is included in `Module` at startup. The historic reasons for this are unclear, and it's difficult to trace *how* `trace_execution_scoped` is available as a class method on `MethodTracer`. Making this more explicit in the code would require more refactoring than is in scope here.
If/when we do change `MethodTracer` not to be included in …

[BUGFIX] add_method_tracer errors on BasicObject methods

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/logger.rb
lib/new_relic/agent/instrumentation/logger/chain.rb
lib/new_relic/agent/instrumentation/logger/instrumentation.rb
lib/new_relic/agent/instrumentation/logger/prepend.rb
newrelic.yml
test/helpers/config_scanning.rb
test/multiverse/suites/logger/Envfile
test/multiverse/suites/logger/config/newrelic.yml
test/multiverse/suites/logger/logger_instrumentation_test.rb
test/multiverse/suites/mongo/mongo2_instrumentation_test.rb
test/multiverse/suites/rack/nested_non_rack_app_test.rb
test/multiverse/suites/rack/puma_rack_builder_test.rb
test/multiverse/suites/rack/rack_auto_instrumentation_test.rb
test/multiverse/suites/rack/rack_unsupported_version_test.rb
test/multiverse/suites/rack/url_map_test.rb
test/multiverse/suites/sinatra/ignoring_test.rb
test/multiverse/suites/sinatra/sinatra_metric_explosion_test.rb
test/new_relic/agent/configuration/orphan_configuration_test.rb
test/new_relic/agent/error_trace_aggregator_test.rb
test/new_relic/agent/instrumentation/logger/instrumentation_test.rb
test/new_relic/agent/monitors/cross_app_monitor_test.rb
test/new_relic/agent/transaction/segment_test.rb
test/performance/lib/performance/instrumentation/gc_stats.rb
test/performance/lib/performance/instrumentation/stackprof.rb
test/performance/lib/performance/platform.rb
test/performance/suites/logging.rb

This pull request introduces basic instrumentation for logging line counts and sizes, with faceting by severity. It hooks into the Ruby standard library `Logger` class.
This new instrumentation is controlled by the configuration flags `instrumentation.logger` or the older style `disable_logger_instrumentation`.
I've confirmed that the point that we're instrumenting is available with the same signature all the way back to Ruby 2.2.0, so nothing special needed to support it on all our currently allowed Rubies.
There did end up being one subtle bit here because the agent uses `Logger` ourselves via `AgentLogger`. This meant that if our metric recording caused us to write to the `AgentLogger` again (which does happen in some paths), we could end up in a recursion. This surfaced immediately in …

Logger instrumentation and perf suite

---

test/environments/rails42/Gemfile
test/environments/rails51/Gemfile
test/multiverse/suites/activemerchant/Envfile
test/multiverse/suites/rails/Envfile
test/multiverse/suites/rails_prepend/Envfile

The issue with the newest racc version on jruby has been resolved https://github.com/ruby/racc/issues/172, so this PR will revert the changes we made in https://github.com/newrelic/newrelic-ruby-agent/pull/812 to work around the error. …

Remove all pinned racc versions for jruby

---

lib/new_relic/agent/monitors/cross_app_monitor.rb

Adds a check for if CAT is enabled before logging the CAT deprecation warning.
closes #827
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/REA …

Log CAT deprecation warning only when enabled

---

lib/new_relic/agent/instrumentation/memcache/dalli.rb
lib/new_relic/agent/instrumentation/memcache/helper.rb
lib/new_relic/agent/instrumentation/memcache/prepend.rb
test/multiverse/suites/memcache/Envfile
test/multiverse/suites/memcache/dalli_test.rb

Since Dalli 3.0.2 was released, usage of Dalli::Server has been
deprecated. see: https://github.com/petergoldstein/dalli/pull/760
This commit removes those references and replaces them with the updated
API through Dalli::Protocol::Binary
For most contributions it is strongly recommended to add additional tests …

Use Dalli::Protocol::Binary rather than Dalli::Server

---

lib/new_relic/agent/configuration/default_source.rb

While working on a GTSE ticket, I noticed [the documentation for `error_collector.ignore_errors`](https://docs.newrelic.com/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration/#error_collector-ignore_errors) marked this setting as deprecated, but the deprecated flag was not included on default_source.

Add deprecated flag to error_collector.ignore_errors

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/tilt.rb
lib/new_relic/agent/instrumentation/tilt/chain.rb
lib/new_relic/agent/instrumentation/tilt/instrumentation.rb
lib/new_relic/agent/instrumentation/tilt/prepend.rb
test/multiverse/suites/tilt/Envfile
test/multiverse/suites/tilt/config/newrelic.yml
test/multiverse/suites/tilt/layout.haml
test/multiverse/suites/tilt/test.erb
test/multiverse/suites/tilt/test.haml
test/multiverse/suites/tilt/tilt_instrumentation_test.rb

This instrumentation creates new metrics with the style of: `View/#{class_name}/#{file_path}/Rendering`
An example metric would look like `View/Tilt::HamlTemplate/blog/layout.html/Rendering` 
Traces and spans related to view rendering within Tilt should be nested within the action that causes the template to render.
If a template is rendered within the block of another template rendering call, it will appear as nested within the outer template. 
```ruby 
require 'tilt'
require 'haml'
def index
Tilt.new('layout.haml').render {
Tilt.new('body.haml')
}
end
```
Should result in a nested span that looks like this: 
This project began with the intention of instrumenting `Tilt::Template#prepare`, to discover this is a protected method. I decided to pivot to instrument `#initialize` instead, for …

[TILT-2] Tilt::Template#render instrumentation

---

CHANGELOG.md
lib/new_relic/agent/logging.rb
test/new_relic/agent/logging_test.rb

Adds a call to`#scrub` with a replacement character to avoid raising a `JSON::GeneratorError` when non-unicode characters are included in log messages.
`#scrub` was chosen over `#encode` due to better performance when running benchmark tests.
Closes #842

Scrub non-unicode characters from logger

---

CHANGELOG.md
infinite_tracing/lib/infinite_tracing/agent_integrations/datastore_segment.rb
infinite_tracing/lib/infinite_tracing/agent_integrations/external_request_segment.rb
infinite_tracing/lib/infinite_tracing/agent_integrations/segment.rb
infinite_tracing/test/infinite_tracing/agent_integrations/datastore_segment_test.rb
infinite_tracing/test/infinite_tracing/agent_integrations/external_request_segment_test.rb
infinite_tracing/test/infinite_tracing/agent_integrations/segment_test.rb
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/transaction/datastore_segment.rb
lib/new_relic/agent/transaction/external_request_segment.rb
lib/new_relic/agent/transaction/segment.rb
test/multiverse/suites/rails/ignore_test.rb
test/new_relic/agent/transaction/datastore_segment_test.rb
test/new_relic/agent/transaction/external_request_segment_test.rb
test/new_relic/agent/transaction/segment_test.rb

`newrelic_ignore` is supposed to make it so that the agent doesn't record anything in the ignored transaction. This appears to work properly in almost all areas, except span events. As far as I can tell, this has never worked in span events since there is no check there to see if the transaction is ignored or not. Our [documentation](https://docs.newrelic.com/docs/apm/agents/ruby-agent/api-guides/ignoring-specific-transactions/#ignore) does state that events will not be recorded when using `newrelic_ignore` though, so this does appear to be a bug rather than an …

Do not record span events when transaction is ignored

---

lib/new_relic/agent/distributed_tracing/trace_context_payload.rb
lib/new_relic/agent/transaction/distributed_tracer.rb
test/new_relic/agent/distributed_tracing/trace_context_cross_agent_test.rb
test/new_relic/agent/transaction/distributed_tracer_test.rb
test/new_relic/http_client_test_cases.rb

Co-authored-by: Kayla Reopelle (she/her) <kaylareopelle@users.noreply.github.com>
Previously the agent would fail to create trace context payload and emit an error to the agent logs when the agent had not yet connected. The correct behavior in this situation is to not create these headers due to lack of required info needed from new relic servers after the agent connects. This change has been made and we have added a test to check this scenario.
closes #801
verify your changes don't …

Prevent distributed tracing headers from emitting errors when agent not connected

---

.github/workflows/ci.yml
CHANGELOG.md
infinite_tracing/test/support/fixtures.rb
test/environments/rails60/Gemfile
test/environments/rails61/Gemfile
test/multiverse/suites/httpclient/Envfile
test/multiverse/suites/memcache/Envfile
test/multiverse/suites/rails/Envfile
test/multiverse/suites/sidekiq/Envfile
test/performance/lib/performance/instrumentation/gc_stats.rb
test/performance/lib/performance/instrumentation/stackprof.rb
test/performance/lib/performance/platform.rb

Address test failures found when running Ruby 3.1.0-preview1 against the CI. 
Todo:

Add Ruby 3.1.0-preview1 to CI

---

CHANGELOG.md
lib/new_relic/agent/logging.rb
test/new_relic/agent/logging_test.rb

* Update `NewRelic::Agent::Logging::DecoratingFormatter#escape` to use `String#encoding` instead of `String#scrub`.
* Include test case for `Encoding::ASCII_8BIT` written by @nikajukic
* Update condition to call `#encoding` to look for both `valid_encoding?` and `Encoding::UTF_8`
Closes #863 
[here for …

Run #encode on ASCII-8BIT encoded log messages

---

CHANGELOG.md
lib/new_relic/agent/adaptive_sampler.rb
test/new_relic/agent/adaptive_sampler_test.rb

Co-authored by: Tanna McClure <tannalynn@github.com>
It was reported that our AdaptiveSampler sampling algorithm was using integer division rather than floats: 
```ruby
rand(@seen) < (@target ** (@target / @sampled_count) - @target ** 0.5)
```
@target and @sampled_count will always be Integers, causing the middle part of the formula to be floored by Ruby, resulting in zero. The entire formula could then only return zero or a negative number. This would cause the comparison to always evaluate false.
Our solution coerces @target into a float to allow non-zero …

Use float division for #exponential_backoff

---

.github/workflows/ci.yml
test/multiverse/suites/sidekiq/Envfile

Ruby 2.6.9, 2.7.5, and 3.0.3 were released on November 24, 2021. 
This PR adds them to the CI and makes adjustments to the code as needed to get the existing tests to pass.
Closes: #866 

Update CI to run on latest supported Ruby versions

---

infinite_tracing/newrelic-infinite_tracing.gemspec
lib/new_relic/agent/parameter_filtering.rb
lib/new_relic/control/frameworks/sinatra.rb
newrelic_rpm.gemspec
test/helpers/minitest.rb
test/multiverse/suites/agent_only/start_up_test.rb
test/multiverse/suites/mongo/helpers/mongo_server.rb
test/multiverse/suites/sinatra_agent_disabled/Envfile
test/multiverse/suites/sinatra_agent_disabled/config/newrelic.yml
test/multiverse/suites/sinatra_agent_disabled/shim_test.rb
test/new_relic/license_test.rb

The `NewRelic::Control::Frameworks` sub-classes are responsible for the behavior of identified frameworks when the agent is disabled during startup. The `NewRelic::Agent::Instrumentation::ControllerInstrumentation::Shim` class creates empty methods with the same names as methods directly called within customer applications. Though the Rails subclasses of `NewRelic::Control::Frameworks`  added the `NewRelic::Agent::Instrumentation::ControllerInstrumentation::Shim` class to the appropriate ancestor chain, the Sinatra class did not.
This PR adds the shims to …

Bugfix: Add ControllerInstrumentation::Shims for Sinatra

---

Rakefile

Redefine the `test:env` rake target so that it will accept any number of
input arguments (as previously defined the maximum number was 6), while
also updating the target's `desc` value to help retain useful usage
information.
resolves #908 
For most contributions it is strongly recommended to add additional …

rake test:env - support more than 6 arguments

---

test/environments/rails52/Gemfile
test/environments/rails60/Gemfile
test/environments/rails61/Gemfile

this PR adds suitable versions of jdbc adapters to rails 5.2 - 6.1 gemfiles
* rails 7 isn't supported on jruby yet
-
-

[ci] update jdbc adapters

---

test/environments/rails61/Gemfile

Removes the `webrick` installation from the Rails61 test environment. It seems the web server getting picked up on some occasions is `webrick` instead of `passenger`. None of the other Rails environments have `webrick` installed at all. This addition may have been a premature fix to address the lack of `webrick` in Ruby 3+. 
Closes #916

Remove webrick from rails61 environment

---

CHANGELOG.md
lib/new_relic/agent/parameter_filtering.rb

This PR updates the constants in the ParameterFiltering module so that they are not redefined when the module is reloaded. 
closes #934 …

Eliminate redefined constant warnings from ParamterFiltering

---

.github/workflows/ci.yml
test/environments/rails50/Gemfile
test/multiverse/lib/multiverse/runner.rb
test/multiverse/suites/active_record/Envfile
test/multiverse/suites/active_record_pg/.gitignore
test/multiverse/suites/active_record_pg/Envfile
test/multiverse/suites/active_record_pg/Rakefile
test/multiverse/suites/active_record_pg/active_record_test.rb
test/multiverse/suites/active_record_pg/app/models/models.rb
test/multiverse/suites/active_record_pg/ar_method_aliasing.rb
test/multiverse/suites/active_record_pg/before_suite.rb
test/multiverse/suites/active_record_pg/config/database.rb
test/multiverse/suites/active_record_pg/config/database.yml
test/multiverse/suites/active_record_pg/config/newrelic.yml
test/multiverse/suites/active_record_pg/db/migrate/20141105131800_create_users_and_aliases.rb
test/multiverse/suites/active_record_pg/db/migrate/20141106082200_create_orders_and_shipments.rb
test/multiverse/suites/active_record_pg/db/migrate/20150413011200_add_timestamps_to_orders.rb
test/multiverse/suites/active_record_pg/db/migrate/20150414084400_create_groups.rb

This PR adds a new multiverse suite `active_record_pg` that runs the active record tests with postgres instead of mysql like the `active_record` suite uses. Mysql2 gem is difficult to get working on ruby 3.0+, so we moved to Postgres for all ruby 3.0+ active record tests. 
* Run jruby tests on Rails 5.0, 5.2, 6.0, 6.1 
* Add Postgres service to the multiverse CI actions
* Add activerecord-jdbcmysql-adapter and activerecord-jdbcsqlite-adapter to active record suite
* Refine Postgresql tests to support Rails 7.0+
#902

Run active record tests on ruby 3.0+

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/middleware_tracing.rb

It was brought to our attention that this error continues to occur despite previous attempts to prevent this error. I believe I have identified the root cause and prevented this from occurring in the future. I was no longer able to see the error happening using the reproduction provided. 
During my investigation, I found similar issues in a couple other gems:
https://github.com/rack/rack/issues/589
https://github.com/getsentry/sentry-ruby/issues/1183
https://github.com/airbrake/airbrake/issues/233
closes #933 (original #573)
The agent includes a suite of unit …

Bugfix: Puma "can't add a new key into hash during iteration"

---

.github/actions/build-ruby/dist/index.js
.github/actions/build-ruby/index.js
.github/workflows/ci.yml
test/script/install_mysql55

**Provide MySQL 5.5 from source**
For older (< v2.4) Rubies and the Rubies that are still tested against
Rails environments via `mysql2` v0.3.x (Ruby < 2.6), provide an instance
of MySQL 5.5 on the machine built from source and then cached for
subsequent runs. The newer MySQL versions require a higher version of
`mysql2` and the older (< 2.5) Rubies require OpenSSL v1.0, which MySQL
5.5 comes bundled with.
**Upgrade Ubuntu 18 to 20**
Upgrade from GitHub's 18.04 containers to 20.04
**Use MySQL as a service**
Ignore the MySQL server available (but not started) on the GitHub Ubuntu
20.04 image and use a separate service for MySQL instead. This brings
MySQL on a peer level with Postgres, Redis, etc.
resolves #678

CI: Ubuntu 20.04

---

lib/new_relic/version.rb

when defining `NewRelic::VERSION::STRING`, don't bother loading a file
that won't be there, rescuing, compacting an array, splatting an arg
list, joining an array, etc.  Just build a string.

NewRelic::VERSION optimisations

---

.github/workflows/label_community_cards.yml

Remove the echo statements from the label workflow as per [GitHub's
recommendation](https://securitylab.github.com/advisories/GHSL-2020-183-checkstyle-checkstyle-workflow/)

remove the echo statements from the label workflow

---

test/multiverse/README.md
test/multiverse/lib/multiverse/runner.rb

the current consensus is that when a suite name "filter" is passed to
the multiverse rake task, that filter should require an exact match with
a suite directory name.
for example, with the following command:
```shell
bundle exec rake test:multiverse[active_record]
```
the desired result is to have the `active_record` suite ran, but the
`active_record_pg` suite be excluded.

multiverse runner: exact directory name matching

---

lib/new_relic/agent/hostname.rb

Without this, all my cronjobs, servers etc will always output to stderr:
```
hostname: unknown option -- f
usage: hostname [-s] [name-of-host]
```

Silence stderr output on *BSD

---

CHANGELOG.md
newrelic.yml

removed duplicate `browser_monitoring.auto_instrument` from
`newrelic.yml`. This configuration option (for RUM) defaults to `true`
and is appropriately commented out in the config so as to not be
redundantly applied. The confusing duplicated config file entry with a
`false` value (also commented out) has now been removed.
resolves #955

remove browser_monitoring.auto_instrument dupe

---

test/performance/Gemfile
test/performance/lib/performance/baseline.rb
test/performance/lib/performance/baseline_compare_reporter.rb
test/performance/lib/performance/console_reporter.rb
test/performance/lib/performance/runner.rb
test/performance/lib/performance/table.rb
test/performance/script/runner

enhancements for the performance tests:
* `redis` is a required gem, so add it to `Gemfile` and alphabetize the
list
* Make the baseline output file location configurable via an environment
variable while still defaulting to the user's home directory
* Add a `--markdown` / `-M` flag to generate the comparison table in
Markdown format. Usage: `script/runner -C --markdown`

performance test enhancements

---

lib/new_relic/agent/log_event_aggregator.rb
test/new_relic/agent/log_event_aggregator_test.rb

Adds a guard statement to `NewRelic::Agent::LogEventAggregator#record` to return if the `formatted_message` argument is `nil` or an empty string.
Closes #984 
Adds unit tests for not recording empty or nil messages

Logging: Don't send payloads with empty message attributes

---

lib/new_relic/agent/log_event_aggregator.rb
test/new_relic/agent/log_event_aggregator_test.rb

Adds a private method, `#truncate_message` to shorten messages to the maximum allowed bytes, 32 * 1024 (1 kibibyte). This method is called when an event is created if the message's bytesize exceeds the limit.
Closes #997
Adds unit tests for truncating the message if over the bytes and leaving the message as-is if equal to or less than the required bytes.

Logging: Apply attribute value limit on messages

---

lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/log_event_aggregator.rb
newrelic.yml
test/multiverse/suites/agent_only/log_events_test.rb
test/new_relic/agent/log_event_aggregator_test.rb
test/new_relic/marshalling_test_cases.rb

Finesse the config options with the correct `newrelic.yml` documentation, default values, and on/off switches in code: 
* `application_logging.metrics.enabled`
* `application_logging.forwarding.enabled`
* `application_logging.forwarding.max_samples_stored`
Closes #983
Tests for the forwarding configs have been created as part of Jason C.'s initial PR. Tests have been added for the metrics config.

Logging: Add configuration options for logging

---

lib/new_relic/agent/new_relic_service.rb
test/new_relic/agent/new_relic_service_test.rb

Updates existing metrics to the new format outlined in the [Data Usage Supportability Metrics Agent Spec (Internal)](https://source.datanerd.us/agents/agent-specs/blob/main/Data-Usage-Supportability-Metrics.md):
* `Supportability/invoke_remote_size` => `Supportability/{language}/Collector/Output/Bytes`
* `Supportability/invoke_remote_size/{method}` => `Supportability/{language}/Collector/{method}/Output/Bytes`
Closes #976 
Existing unit tests updated to use new format

Logging: Implement data usage supportability metrics

---

test/agent_helper.rb
test/multiverse/suites/active_record_pg/active_record_test.rb

minitest: When defining an expected "call count" value, support the
inclusion of any one of the ">", "<", ">=", and "<=" operators instead
of always requiring an exact "==" style match.
to demonstrate this new functionality, the ActiveRecord test for
Postgres SELECT statements has been updated to use ">=" and permit the
extra schema/type cache query calls to be present and permitted by the
test.
resolves #969 
This will provide immediate an immediate resolution for #969 (flaky/flickering test) while we continue to discuss whether the query/type cache calls should be ignored in the first place. The results of that discussion will be tracked with a separate Issue.

tests: allow call counts to be operator based

---

lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/logger.rb
lib/new_relic/agent/instrumentation/logger/instrumentation.rb
lib/new_relic/agent/log_event_aggregator.rb
test/multiverse/suites/logger/logger_instrumentation_test.rb
test/new_relic/agent/configuration/default_source_test.rb
test/new_relic/agent/log_event_aggregator_test.rb
test/new_relic/agent/transaction_test.rb

Adds `application_logging.enabled` config option to toggle logging features
* The default value of `instrumentation.logger` is dependent on the default of `application_logging.enabled`
* Within the LogEventAggregator, the feature is `@enabled?` when both `instrumentation.logger` and `application_logging.enabled` have truthy values.
* When `application_logging.enabled` is false, all logging-related config options are disabled:
* `application_logging.forwarding.enabled`
* `application_logging.metrics.enabled`
* The work to set `application_logging.local_decorating.enabled` with the overall toggle will be completed in #988
* When `application_logging.enabled` is false, supportability metrics will still be recorded
* When `application_logging.enabled` is true, all logging-related config …

Logging: Create overall application logging enabled flag

---

lib/new_relic/agent.rb
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/logger/instrumentation.rb
lib/new_relic/agent/local_log_decorator.rb
lib/new_relic/agent/log_event_aggregator.rb
newrelic.yml
test/agent_helper.rb
test/multiverse/suites/logger/logger_instrumentation_test.rb
test/new_relic/agent/local_log_decorator_test.rb
test/performance/suites/logging.rb

Add local log decoration with linking metadata when `application_logging.local_decoration.enabled` is true.
Closes #988 
* Adds unit tests for new class, LocalLogDecorator
* Adds integration tests to Logger instrumentation
* Adds performance tests for log decorating

Logging: Add log decoration

---

test/agent_helper.rb

TestUnit's `assert_operator` takes arguments in the order that makes
sense when read left to right: `[6, :>=, 5]`, and we had the first and
third values swapped.
fixes buggy syntax introduced by #1013

agent_helper: fix for 'assert_operator' usage

---

README.md

Update the README's "Background Jobs" link to match the correct docs
site location.
resolves #1017
thank you @matthewhively for bringing the broken link to our attention

README: fix "Background Jobs" link

---

test/new_relic/agent/log_event_aggregator_test.rb
test/new_relic/common_aggregator_tests.rb

The CommonAggregatorTests are used in all of the Ruby Agent's Aggregator test suites. They were missing from the LogEventAggregator in its initial PR. These changes add the tests and allow them to pass.
Closes #1012 
CommonAggregatorTests and LogEventAggregatorTests updated to accommodate the LogEventAggregator class

Logging: Add CommonAggregatorTests to LogEventAggregatorTest

---

lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/active_support_logger.rb
lib/new_relic/agent/instrumentation/active_support_logger/chain.rb
lib/new_relic/agent/instrumentation/active_support_logger/instrumentation.rb
lib/new_relic/agent/instrumentation/active_support_logger/prepend.rb
lib/new_relic/agent/instrumentation/logger.rb
newrelic.yml
test/multiverse/suites/rails/active_support_logger_test.rb

The Rails server command has an option, `--log_to_stdout`, that defaults true in development and when the server is not daemonized. The output gets doubled by a method called `ActiveSupport::Logger.broadcast`, that sends all logs to both `development.log` and `STDOUT`. This caused our logging instrumentation to forward emitted logs twice.
This PR prepends/aliases `ActiveSupport::Logger.broadcast` to mark any logger passed to the method with `@skip_instrumenting`. This instance variable is currently used by our Logging instrumentation to skip the NewRelic loggers `newrelic_agent.log` and `newrelic_audit.log`.
Closes #1005
Added integration tests with ActiveSupport::Logger

Logging: Mark ActiveSupport::Logger.broadcast arguments as @skip_instrumenting

---

CHANGELOG.md
test/test_helper.rb

Previously, unit tests would fail with unexpected invocation errors when `NEW_RELIC_LICENSE_KEY` and `NEW_RELIC_HOST` environment variables were present. For example: `unexpected invocation: #<Mock:0x28438>.sync=(true) (MiniTest::Assertion)`
Now, tests will discard these environment variables before running. This doesn't remove environment variables from the actual machine, just for the ruby process.

Fix test failures from env variables

---

README.md

Updated capitalization of "New Relic Ruby agent" to be consistent with marketing materials. Added punctuation and defined "CLA" for clarity. Updated README sign-off.
[here for our unit tests](https://github.com/newrelic/newrelic-ruby-agent/blob/mai …

Update README for clarity and consistency

---

LICENSE
README.md
THIRD_PARTY_NOTICES.md
test/new_relic/license_test.rb

* Remove the "Versions 6.12.0 and above" note from `LICENSE` so that
that file will exactly match the Apache License, version 2.0 text.
* Update `README.md` to reference the fact that other licenses may be in
play for versions older than 6.12.
* Update `README.md` to directly reference `LICENSE` instead of the
Apache web site.
* Update `README.md` to explain that third party software _may_ be used
* Update `THIRD_PARTY_NOTICES.md` to explain that third party software
_may_ be used, but that none is currently used. Call attention to the
fact that the actual development of the agent absolutely depends on
third party software even though that software is not itself
distributed with the agent.

License documentation updates

---

lib/new_relic/agent/log_event_aggregator.rb

instead of checking with #tty?, check if #class equals IO
Local dev testing and Docker based testing seemed fine with the TTY check, but GitHub Actions failed the tests with it.

logger stdout/stderr check: check for IO class

---

lib/new_relic/agent/local_log_decorator.rb
lib/new_relic/agent/log_event_aggregator.rb
test/multiverse/suites/agent_only/log_events_test.rb
test/new_relic/agent/local_log_decorator_test.rb
test/new_relic/agent/log_event_aggregator_test.rb
test/new_relic/marshalling_test_cases.rb

* Append `entity.name` to the linking metadata used by the `LocalLogDecorator`
* Remove the `#delete` call on the constant holding `entity.name` information
Closes #1031
Existing tests updated to include the new attribute

Logging: Add entity name to log events and local log decoration

---

lib/new_relic/agent/log_event_aggregator.rb
test/new_relic/agent/log_event_aggregator_test.rb

As per the agent specs, set the log event severity as "UNKNOWN" is the severity is empty or nil.
Closes #1042 
Unit tests added for this change

Logging: Set severity as "UNKNOWN" if nil or empty

---

newrelic.yml

The `application_logging.enabled` configuration option needs an entry in `newrelic.yml`

Logging: Add overall enabled config

---

lib/new_relic/agent/configuration/default_source.rb
lib/tasks/config.rake

I updated a bunch of wordings and other things that were changed on the docs site so that we are matching that.
I also updated the config rake task to allow grouping for config options with more than 2 parts (ex: `application_logging.forwarding.enabled`). 
I also updated the script to use `documentation_default` from the default_source configs if that field is present. 
#810
Github Actions when a pull …

Update script to generate config html docs

---

test/multiverse/suites/memcache/Envfile

for memcached tests, don't bother to install the 'memcached' gem for
Ruby 3.2. we can likely discard this gem entirely in future, but for now
we'll scope the removal to Ruby 3.2 to avoid gem build issues.

tests: don't install 'memcached' for Ruby 3.2

---

test/multiverse/suites/mongo/Envfile

for Mongo multiverse tests:
* drop coverage of 'mongo' gem <= v1.10. this allows us to stop
bothering with compiling 'bson_ext' which doesn't work with Ruby 3.2
and is slow for others
* stop testing the older (<= v2.9.0) 'mongo' gem versions with Ruby
version 2.5 and above
* specify the latest 'bson' gem version

tests: update Mongo tests for Ruby 3.2

---

test/multiverse/suites/config_file_loading/Envfile
test/multiverse/suites/config_file_loading/config_file_loading_test.rb

These changes get the config file tests working with Ruby 3.2+
* For Ruby v2.4.0+ (lowest version supported), start using the latest
version of FakeFS, v1.4.1
* For all Rubies, don't allow Bundler to require FakeFS when `Envfile`
gets processed. This prevents a known collision issue with `FileUtils`
that the FakeFS README lists under "Caveats".

config tests: update FakeFS usage for Ruby 3.2+

---

test/multiverse/suites/delayed_job/Envfile

for the delayed job tests, use sqlite3 v1.4.2 instead of v1.3.13
this addresses a compilation issue with Ruby 3.2 and the new version
should be backwards compatible with older Rubies as well.

delayed job tests: use a newer sqlite3 version

---

.github/actions/build-ruby/action.yml
.github/workflows/ci.yml

Upgrade CRubies 2.6+ to their latest minor versions in order to address
[CVE-2022-28739](https://www.ruby-lang.org/en/news/2022/04/12/buffer-overrun-in-string-to-float-cve-2022-28739/)
which involes a String-to-Float conversion buffer overrun.
Versions 3.0.4 and 3.1.2 also deliver fixes for [CVE-2022-28738](https://www.ruby-lang.org/en/news/2022/04/12/double-free-in-regexp-compilation-cve-2022-28738/)

CI: upgrade CRubies for CVE-2022-28739

---

test/environments/rails42/Gemfile
test/multiverse/lib/multiverse/runner.rb
test/multiverse/lib/multiverse/suite.rb
test/multiverse/suites/active_record/Envfile
test/multiverse/suites/agent_only/Envfile
test/multiverse/suites/bunny/Envfile
test/multiverse/suites/capistrano/Envfile
test/multiverse/suites/capistrano2/Envfile
test/multiverse/suites/curb/Envfile
test/multiverse/suites/datamapper/Envfile
test/multiverse/suites/deferred_instrumentation/Envfile
test/multiverse/suites/delayed_job/Envfile
test/multiverse/suites/grape/Envfile
test/multiverse/suites/httprb/Envfile
test/multiverse/suites/padrino/Envfile
test/multiverse/suites/rack/Envfile
test/multiverse/suites/rails/Envfile
test/multiverse/suites/rails_prepend/Envfile
test/multiverse/suites/rake/Envfile
test/multiverse/suites/redis/Envfile
test/multiverse/suites/resque/Envfile
test/multiverse/suites/sidekiq/Envfile
test/multiverse/suites/sinatra/Envfile
test/multiverse/suites/sinatra_agent_disabled/Envfile
test/new_relic/agent_test.rb

assume Ruby version 2.2.10 or higher is used for all tests and disable
or rework any checks that previous tested for older versions

tests: assume Ruby 2.2.10+

---

lib/new_relic/agent/vm/mri_vm.rb

Ruby 3.2 uses a new `RubyVM` stat to track more fine grained constant
cache invalidation data. Sum the fine grained values together to produce
a Ruby 3.1 compatible value for now and leave a TODO for possibly
reporting the individual constant key/value pairs later.

Support Ruby 3.2+ cache invalidation stats

---

lib/new_relic/agent.rb
lib/new_relic/agent/method_tracer.rb
lib/new_relic/agent/method_tracer_helpers.rb

* implement a caching system for MLT (not needed for manual tracing, but
critical for Rails controller methods)
* stop passing MLT info downstream with unscoped metrics - these don't
appear to have segments created for them

satisfy remaining MLT todos

---

CHANGELOG.md
lib/new_relic/agent/configuration/environment_source.rb
test/new_relic/agent/configuration/environment_source_test.rb

Though Environment Source accepts configuration values with a type of Array, there was not an option to convert the received string into an array
None
Tests updated to include the case where comma-separated lists with and without spaces are accepted: 
ex: `NEW_RELIC_ATTRIBUTES_INCLUDE=hi,bye` and `NEW_RELIC_ATTRIBUTES_INCLUDE=hi, bye`

Add Array conversion for Environment Source values

---

test/new_relic/agent/configuration/event_harvest_config_test.rb

The "big red button" sets the harvest limits for log_event_data to zero for all applications in an account. This PR adds a test that uses a connect reply of 0 for `event_harvest_config.harvest_limits.log_event_data` to see how the agent responds.
Relates to #1046 
Adds unit test to evaluate response to a connect reply of zero.

Logging: Test agent response when connect reply is zero

---

test/performance/suites/method_tracer.rb

* This PR adds performance tests with `:'code_level_metrics.enabled'` set to true and false.
* Each of the `:add_method_tracer` options are tested.
* The test file can be run within the `test/performance` directory using `script/runner -n code_level_metrics`
Relates to #1075

CLM: Performance tests for :add_method_tracer

---

lib/new_relic/agent/configuration/default_source.rb
newrelic.yml
newrelic_rpm.gemspec

Sets the default for `application_logging.forwarding.enabled` to true.
Closes #1022
Updat[ing] tests to reflect the new default
~~- [ ] Add CHANGELOG entry (once available)~~ - Moved to #1109

Logging: Turn log forwarding on by default

---

README.md

The Community Plus header on our README does not have alt text describing the image. This PR adds alt-text describing the banner and duplicating the text that appears so that it is more accessible.

Add alt-text to README banner

---

test/multiverse/suites/rails/Envfile
test/multiverse/suites/rails_prepend/Envfile

Rails 5.2.7.1 inadvertently broke Ruby 2.2 compatibility by including a
'~>>` style heredoc. For Rubies below 2.4 that don't support that
heredoc syntax, stick with Rails 5.2.7 or below.

rails tests: keep Ruby 2.2 below Rails 5.2.7.1

---

lib/new_relic/agent/instrumentation/active_merchant.rb
lib/new_relic/agent/instrumentation/sidekiq.rb
lib/new_relic/agent/instrumentation/sinatra.rb

While I was looking into an unrelated issue, I discovered that there were errors in the agent log for these lines, since it doesn't like the string VS Gem::Version comparison. This pr converts the strings to version objects to avoid that issue.

Fix comparison for string vs Gem::Version

---

docker-compose.yml

`docker-compose.yml` was inadvertently made to require a 'RUBY_VERSION'
environment variable because passing an empty value to `Dockerfile`
caused the `Dockerfile` build argument default value to be overridden.
Now when the `RUBY_VERSION` environment variable is not set, a default
version will be defined by `docker-compose.yml`.

docker-compose.yml: supply a default Ruby version

---

lib/new_relic/agent/autostart.rb
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/action_controller_subscriber.rb
lib/new_relic/language_support.rb

`NewRelic::LanguageSupport.constantize`, which returns a Ruby constant
corresponding to the given string, is very similar to
`ActiveSupport::Inflector#constantize`.
With
https://github.com/rails/rails/commit/7057ccf6565c1cb5354c1906880119276a9d15c0
the Rails team has updated `#constantize` to simply call
`Object.const_get` on the given input string and reaped performance
benefits from doing so. We're unable to update the agent's
`constantize` method until we drop support for Ruby 2.5, given that
`Object.const_get` does not provide the same functionality we desire
until Ruby 2.6.
Before Ruby 2.6 `Object.const_get('Namespace1::MyClass')` will return
`MyClass` if `Namespace2::MyClass` exists, even though
`Namespace1::MyClass` (the desired constant) does not.
But, we can still make some …

rework constantize calls

---

CHANGELOG.md
lib/new_relic/agent/transaction_error_primitive.rb
test/multiverse/suites/agent_only/error_events_test.rb

This fixes a bug in how we're creating error events when not in a transaction.
Currently, when notice_error is called while not in a transaction, the priority is not set on the event because we are only taking it from the transaction payload passed in, which does not exist in this situation. This only begins to cause errors once the error event aggregator is full and we begin sampling.
I did check other event types to make sure this situation isn't possible for any other events.
- Span events are not created outside of a transaction
- Transaction events don't …

Bugfix: Error events missing priority when created outside of a transaction

---

Rakefile

The previous passing of `-u` to `rsync` (don't overwrite the destination
content if it has a newer timestamp than the source content) was
problematic because it assumed that a developer would have both the Ruby
agent and the cross agent specs cloned, then have new specs authored and
pulled down, and then perform the sync. If the cross agent specs haven't
been updated in a while, then the clone order of the repos becomes a
factor in the timestamp comparison.
Now, the pull and push rake targets will always overwrite the
destination content with the source content. To compensate for this, the
user is now prompted to continue or cancel with a warning that any
unsaved changes will be overwritten, and the previous source code
comment based warning is now presented to stdout as well.
resolves …

rework cross agent pull/push rake tasks

---

lib/new_relic/agent/configuration/default_source.rb
newrelic.yml
test/new_relic/agent/instrumentation/rails/action_controller_subscriber.rb
test/new_relic/agent/method_tracer_helpers_test.rb
test/new_relic/agent/method_tracer_test.rb

The test results and value add for CLM are in favor of enabling the
functionality by default, but we will follow the same approach taken for
logging and default to having the option off for an initial opt-in
rollout.

default to Code Level Metrics support disabled

---

lib/new_relic/agent/method_tracer_helpers.rb
test/new_relic/agent/method_tracer_helpers_test.rb
test/new_relic/agent/method_tracer_test.rb

Especially to disambiguate them from instance methods with the same
names, prefix class method names with 'self.' in the 'code.function'
attribute.

CLM: prefix class functions with 'self.'

---

.rubocop.yml
lib/new_relic/agent/instrumentation/active_job.rb
test/multiverse/suites/rails/activejob_test.rb

fetch and then pass code level metrics related attributes downstream to
segment creation when ActiveJob `perform` calls are traced

code level metrics for ActiveJob

---

.rubocop.yml
CHANGELOG.md
lib/new_relic/agent/new_relic_service.rb
test/new_relic/agent/new_relic_service_test.rb

For supportability metrics, record the uncompressed payload byte size
prior to sending the payload off for possible compression, so that we
are guaranteed to a) be consistent with always reporting the
uncompressed value to guarantee that two instances of the same metric
can reliably be compared, and b) be aligned with New Relic's cross agent
specification describing supportability metrics byte sizes.
resolves #1135

supportability metrics: record uncompressed bytes

---

.github/workflows/ci.yml

because jruby takes too long
Our Jruby unit tests keep timing out, so I've bumped the limit to 30 minutes to give jruby some extra time
and [here …

Increase timeout limit for unit tests in github actions

---

.yardopts
lib/new_relic/traced_thread.rb

I noticed that our rubydocs was [missing](https://www.rubydoc.info/gems/newrelic_rpm/NewRelic/TracedThread) the new TracedThread class we added in the last version. I figured out how to generate it locally and I was able to get it updated it to make it show up and also fixed some syntax since markdown is not what it uses.
Github Actions when a …

Fix TracedThread yard documentation

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml

The new ci_cron workflow will run all ruby versions after a push to main/dev, so this isn't also needed in our ci workflow. 
I also updated the multiverse jobs to split up more so more jobs will run concurrently to see if that improves things.
Github Actions when a pull request is made. More details on running the tests locally can be found …

Update CI github action to only run on PR

---

test/environments/railsedge/Gemfile

help older Bundlers realize that the primary rails/rails branch is
`main`

railsedge: explicitly target 'main' branch

---

CHANGELOG.md
lib/new_relic/agent/new_relic_service.rb
test/new_relic/license_test.rb

lower the compression byte threshold:
`> 64 KiB`  ->  `>= 2 KiB`
previously the agent had a minimum byte size threshold of 64KiB. for any
payload equal to or below that size, compression would not be applied.
this relatively high threshold was originally established to prevent
segfaults from taking place in older versions of Ruby trying trying to
wrap C zlib/gzip libraries to compress small payloads.
with the currently supported Rubies (2.2 - 3.1), segfaults aren't a
problem for even the tiniest of payloads, so we are free to come up with
a value that balances cpu usage and bandwidth savings.
resolves #1136

lower min compression threshold to 2048 bytes

---

.github/workflows/ci_cron.yml

I noticed that our scheduled nightly runs were having some odd failures I was unable to reproduce locally, and the PR ci runs were passing. Looks like just our jruby multiverse tests are still running on ubuntu 18.04 in our ci.yml, unlike in ci_cron.yml. I've updated ci_cron to use 18.04 and I've created a [ticket](https://github.com/newrelic/newrelic-ruby-agent/issues/1173) for us to address updating jruby test runs to 20.04
I also removed rails edge from running on jruby because rails edge requires ruby 2.7+, and jruby 9.3.4.0 is still 2.6, so it was giving …

Fix jruby failures on ci_cron runs

---

lib/new_relic/agent/log_event_aggregator.rb
test/multiverse/suites/agent_only/log_events_test.rb
test/multiverse/suites/logger/logger_instrumentation_test.rb
test/new_relic/agent/log_event_aggregator_test.rb
test/new_relic/agent/logging_test.rb
test/new_relic/marshalling_test_cases.rb

The agent spec changed the log severity key (ex. DEBUG) from `log.level` to `level`. The code has been updated to use this new reference.
Existing tests with the old value have been updated.

Change log.level to level

---

lib/new_relic/agent/instrumentation/active_record_helper.rb
lib/new_relic/agent/instrumentation/active_record_subscriber.rb

This PR adds support for [makara](https://github.com/instacart/makara) database adapters so that proper SQL query obfuscation can be done for the underlying database type. Makara defines its own database adapters for the following databases: mysql2, postgresql, jdbcmysql and jdbcpostgresql. Makara customizes the way ActiveRecord handles it connection pools. Previously, when a makara database connection was being traced by the newrelic gem, it would view it as `ActiveRecord` and not pick up on the underlying database type. This prevented the ability to utilize the proper SQL query obfuscation rules for any makara adapter database connections.
https://github.com/newrelic/newrelic-ruby-agent/issues/507
I've manually confirmed in a local environment that this works for the postgresql_makara …

add support for makara database adapters

---

.rubocop.yml
test/helpers/minitest.rb
test/multiverse/suites/agent_only/service_timeout_test.rb
test/new_relic/agent/rpm_agent_test.rb
test/new_relic/agent/sampler_test.rb
test/new_relic/agent/samplers/cpu_sampler_test.rb
test/new_relic/agent/transaction_sampler_test.rb
test/new_relic/metric_data_test.rb

Added two new Rubocop Performance updates to rubocop.yml: [concurrent_monotonic_time](https://github.com/rubocop/rubocop-performance/blob/master/lib/rubocop/cop/performance/concurrent_monotonic_time.rb) and [string_identifier_argument](https://github.com/rubocop/rubocop-performance/blob/master/lib/rubocop/cop/performance/string_identifier_argument.rb). 
Edited files where Rubocop was upset about string_identifier_argument. Codebase was already looking good for concurrent_monotonic_time.

Rubocop Performance

---

lib/new_relic/agent/pipe_channel_manager.rb
test/new_relic/agent/pipe_channel_manager_test.rb

and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/tes …

Use read_nonblock instead of read in PipeChannelManager

---

lib/tasks/tests.rake

I've had a hard time reading test output since I started working on this repository. One culprit seems to be the inclusion of all files being tested in each run's output. Removing `verbose = true` from `Rake::TestTask(:newrelic)` seems to remove the file list output.

Remove verbose = true from Rake::TestTask

---

.github/workflows/label_community_cards.yml

Previously, CI runs triggered by pull requests opened by community members would fail automatically due to a permissions issue. Based on some guidance from https://github.community/t/github-actions-are-severely-limited-on-prs/18179#M9249, we want to see if this change resolves the problem.
Closes #971 
To test this, we'll need to merge the PR and attempt to open a PR using a non-allowlisted username. I'm willing to use @kreopelle 🌻

Label community on pull_resquest_target

---

test/multiverse/suites/rack/Envfile
test/multiverse/suites/rack/puma_rack_urlmap_test.rb

update the testing of our Puma instrumentation:
- point to the latest package of each of the 3 most recently released
major Puma versions
- stop having newer Rubies test multiple versions of Rack. Now simply
test with the latest Rack for those Rubies that can (Ruby 2.3+) and
the latest Ruby 2.2 compatible Rack for Ruby 2.2
- add a test for Puma URLMap handling which was previously instrumented
but not covered by multiverse testing
Pumas are less than half as fast as cheetahs and over 1.5 times as
heavy.
But Pumas can live 19 years as opposed to 11 for cheetahs. If the Ruby
Puma project had been named Cheetah when it began in 2011, it might have
been on its last legs now in 2022.
resolves #1189

update Puma multiverse tests

---

lib/tasks/config.rake
lib/tasks/install.rake
lib/tasks/multiverse.rake
lib/tasks/tests.rake
test/multiverse/suites/capistrano2/config/deploy.rb
test/new_relic/license_test.rb

for the license tests
- remove the 'scary' terms checker
- reimplement the license header test in a simpler and more efficient
manner
NOTE that `.rake` files are now required to have the license header as well

license tests: remove 'scary', rework header test

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml

use libcurl4-openssl-dev to fetch libcurl

CI: be sure to run `apt-get update` before `apt-get install`

---

.rubocop.yml
infinite_tracing/lib/infinite_tracing/transformer.rb
infinite_tracing/newrelic-infinite_tracing.gemspec
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/sunspot.rb
lib/new_relic/agent/threading/thread_profile.rb
lib/new_relic/dependency_detection.rb
lib/new_relic/metric_data.rb
lib/new_relic/metric_spec.rb
newrelic_rpm.gemspec
test/multiverse/lib/multiverse/suite.rb
test/multiverse/suites/config_file_loading/config_file_loading_test.rb
test/multiverse/suites/rails_prepend/newrelic_prepender/newrelic_prepender.gemspec
test/new_relic/agent/agent/connect_test.rb
test/new_relic/agent/span_event_primitive_test.rb
test/new_relic/agent/span_events_test.rb
test/new_relic/metric_data_test.rb
test/performance/lib/performance/baseline.rb

- default to enabling new cops as they are released
- address all current issues with cops we didn't previously have enabled
- disable certain cops and place TODO reminders alongside them for
future enabling

RuboCop - enable new cops, address new issues

---

test/helpers/minitest.rb

To have MiniTest "fail fast" and halt after encountering the first
failed test, set the "MT_FAIL_FAST" environment variable and then
proceed to run the tests as normal.

MiniTest: optionally fail fast

---

lib/new_relic/agent/instrumentation/grpc/client/chain.rb
lib/new_relic/agent/instrumentation/grpc/client/instrumentation.rb
lib/new_relic/agent/instrumentation/grpc/client/prepend.rb

the gRPC client methods for sending data all accept an optional
`metadata` keyword argument. Because this argument is optional, the
traditional approach of prepending a method that accepts `*args` as
input is problematic given that the arguments aren't guaranteed to
contain the `metadata` keyword. We need to add additional key/val pairs
to the metadata hash, at all times - both when the caller supplied
metadata, and when it is missing and defaults to an empty hash. Given
our instrumentation's approach of calling `super` within a block, we
need to ensure that modified metadata always reaches `super` as input.
Switching away from the `*args` approach to explicitly defining all
input params allows us to accomplish this.
Many thanks to @tannalynn for her help in discussing this approach. …

gRPC: define all individual method args

---

test/performance/suites/marshalling.rb

* only the marshalling tests needed an update
* in addition to making the strings that need to be mutable as such,
remove compatibility with older (< v2.2) Rubies

get perf tests working with frozen strings

---

.github/workflows/ci_cron.yml
.github/workflows/scripts/slack_gem_notifications/notifications_methods.rb
.github/workflows/scripts/slack_gem_notifications/notifications_script.rb
newrelic_rpm.gemspec
test/new_relic/gem_notifications_tests.rb

A ruby script that checks for and notifies the Ruby agent team slack channel of new gem version releases.
closes #1195 
Inside `ci_cron.yml`, a newly added`gem_notifications` job stores a list of gems the team has determined to be core technologies. When the nightly CI runs, this list of gems is passed to the script, `notifications_script`. 
Gem updates are determined by calling the Ruby Gems API and using the `created_at` timestamp. If the release is within the past 24 hours, we know a new version is our and send a POST request to an internal Slackbot.
Files Added:
- `.github/workflows/scripts/slack_gem_notifications/notifications_methods`
- `.github/workflows/scripts/slack_gem_notifications/notifications_script`
- `test/gem_notifications_tests`
Files Edited:
- `ci_cron.yml`
_Before …

Add initial structure for gem slack notifications

---

.github/actions/simplecov-report/README.md
.github/actions/simplecov-report/action.yml
.github/actions/simplecov-report/dist/index.js
.github/actions/simplecov-report/package.json
.github/actions/simplecov-report/src/report.ts

The gem's name is spelled with a capital 'C'. The action's comment used a lowercase 'C'. This brings our action into alignment with the maintainer's spelling.

Update capitalization of SimpleCov

---

lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/grpc/client/instrumentation.rb

Adds the configuration option `instrumentation.grpc.host_denylist` as an array of regexes that the agent will use to ignore certain grpc connections. Currently is only set up for the grpc client. We have a few other configs that use `denylist`, so I opted to use that over blocklist for consistency. 
#1245
Github Actions when a pull request is made. More details on running the tests …

Add configuration for grpc blocklist

---

test/multiverse/lib/multiverse/suite.rb

This block was being run on versions of Ruby that do not generate SimpleCov coverage results, causing an error to be raised on the CI run. This if statement should prevent the errors from being raised.
Also, the rescue has been limited to NameError instead of globally rescuing any exception.

Execute @@after_run check only for Ruby >= 2.7

---

newrelic.yml

This is so that uncommenting any of these options and setting a value will be correctly included in the `common: &default_settings` block. I discovered this while investigating https://github.com/newrelic/newrelic-ruby-agent/issues/731#issuecomment-1192073156.
Github Actions when a pull request is made. More details on running the …

Correctly indent default configs in newrelic.yml template

---

lib/new_relic/agent/instrumentation/grpc/client/instrumentation.rb

calling `#add_request_headers` on the segment will add DT headers, so
there's no need to manually, redundantly do so again later.
the confusion came from the DT headers not being present in testing
because the agent hadn't yet finished connecting when the first gRPC
client stream was performing.

gRPC client: remove redundant DT header setting

---

.github/workflows/ci.yml

use a different conditional to rule out forks from performing SimpleCov
operations (which require write access to our artifact storage)
resolves #1278

GHA: don't run SimpleCov on forks

---

lib/new_relic/agent/instrumentation/grpc/server/instrumentation.rb
test/multiverse/suites/grpc/grpc_server_test.rb

- fix distributed tracing by flipping the order of operations and having the
code that creates a transaction fire first before the code that processes
distributed tracing data, which requires a transaction
- in the gRPC server instrumentation, move the distributed tracing logic out
into a dedicated method
- in the gRPC server instrumentation, do not check if distributed tracing is
enabled before invoking a distributed tracing method, as that method will
itself perform the very same check
- send the entire metadata headers hash (not just a single value) over to the
distributed tracing method, which will short circuit if not given a hash
- in the gRPC server instrumentation, rescue, notice, and re-raise exceptions
- in #handle_with_tracing, prefix the last argument with an underscore to …

gRPC server: distributed tracing fixes

---

lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/method_tracer_helpers.rb
newrelic.yml
test/new_relic/agent/method_tracer_helpers_test.rb

following the successes reported by a good number of opting-in adopters,
the decision has been made to enable code level metrics reporting in the
Ruby agent by default. users may still come up with feature requests for
additional CLM functionality or instrumented library coverage, but the
core functionality in place currently is thought to be stable and ready
for enabling by default.
resolves #1260

enable CLM by default

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/logger/instrumentation.rb
test/multiverse/suites/logger/logger_instrumentation_test.rb

This PR adds checks for if the logger is frozen before attempting to set/change the `@skip_instrumenting` instance variable. Since this variable is only used internally in the agent and we know those instances of Logger are not frozen, this shouldn't interfere with the purpose of this variable. 
closes #1288
Github Actions when a pull request is made. More details on running the …

Don't modify frozen Logger instance

---

lib/new_relic/agent/instrumentation/grpc_client.rb
lib/new_relic/agent/instrumentation/grpc_server.rb
test/new_relic/dependency_detection_test.rb

* Pass `supportability_name` argument to gRPC client instrumentation
* Pass `supportability_name` argument to gRPC server instrumentation
* Add test for DependencyDetection::Dependent#log_and_instrument to make sure the supportability_name is applied to the metric and log message when present.
Relates to #1303 
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/mu …

Update gRPC instrumentation supportability_name

---

test/performance/Gemfile
test/performance/lib/performance/runner.rb
test/performance/suites/trace_context.rb

This commit reverts the addition of minitest to performance tests. Additionally, prevents a string freeze.
and [here for our …

Revert perf minitest addition

---

CHANGELOG.md
lib/new_relic/agent/configuration/yaml_source.rb
test/new_relic/agent/configuration/yaml_source_test.rb

The agent was not correctly identifying the `apdex_f` value that is expected when setting `transaction_tracer.transaction_threshold` in the newrelic.yml if the config option was a one liner. The agent was only checking for the structure expecting it to be defined using two lines, like:
```
transaction_tracer:
transaction_threshold: apdex_f 
```
This PR fixes this issue to also check for the existence of a one liner and adds a test to make sure it is working.
closes https://github.com/newrelic/newrelic-ruby-agent/issues/1294
The agent …

Bugfix for one line yaml config transaction_tracer.transaction_threshold: apdex_f

---

test/multiverse/lib/multiverse/envfile.rb
test/multiverse/suites/sidekiq/Envfile

while waiting on Sidekiq v6.5.4 to remove the unwanted dependency on
`concurrent-ruby`, pin to v6.5.1 for now

CI: temporary Sidekiq fix

---

lib/new_relic/agent/instrumentation/grpc/client/instrumentation.rb

In ruby 2.5, [`merge!`](https://ruby-doc.org/core-2.5.9/Hash.html#method-i-merge-21) only accepts a single argument even though on [2.6+](https://ruby-doc.org/core-2.6.1/Hash.html#method-i-merge-21) multiple hashes can be passed in. 
Since the first argument being passed in was the same object that was calling `merge!`, I just removed it from being passed in as an argument since it was not needed. 
verify your changes don't break existing functionality. These …

Bugfix grpc instrumentation on ruby 2.5

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/story.md

* Add a GitHub Issue template for the "Story" issue type, to be used for development work
* Update the label added when generating a Feature to be `feature request`
Relates to: #1285

Update GitHub issue templates

---

CHANGELOG.md

* note that we flipped the code-level metrics default to on in v8.10.0
* bold markdown formatting fix

CHANGELOG: v8.10.0 updates

---

test/multiverse/suites/rake/Envfile

I noticed that background_2 runs seemed to be taking even longer than normal so I looked into it and noticed there were 2 calls to `create_gemfiles` in the envfile, which was actually doubling the number of multiverse runs. This change brings it more in line with how the rake tests were being run before `create_gemfiles`. I didn't see an obvious way to have the rails and the no rails ones both being called by `create_gemfiles`, so I changed the rails rake test run to use the old style of `gemfile`, and kept the non rails runs using `create_gemfiles`. 
I also …

Remove duplicate rake multiverse runs

---

.github/actions/annotate/package-lock.json
.github/actions/annotate/package.json

For CVE-2022-35954 / CWE-74 / CWE-77, upgrade @actions/core to v1.9.1

CVE-2022-35954: update @actions/core to 1.9.1

---

lib/new_relic/agent/instrumentation/grpc/client/chain.rb
lib/new_relic/agent/instrumentation/grpc/client/instrumentation.rb
lib/new_relic/agent/instrumentation/grpc/client/prepend.rb
lib/new_relic/agent/instrumentation/grpc/helper.rb
test/multiverse/suites/grpc/grpc_client_test.rb

for the gRPC client instrumentation, we had been prepending/chaining
`initialize` calls to get at the host argument in order to apply our
gRPC host denylist behavior. when other libraries are themselves
bringing in the gRPC client library (via the `grpc` gem) and using their
own `initialize` chaining and `super` calls, we run the risk of passing
the wrong number of arguments to the `initialize` method in the chain
that we are handing things off to.
notably, this causes `google-ads-googleads` based apps to encounter
issues.
to address this, let's get out of the business of touching `initialize`
entirely, and source the host information from the gRPC client
instance's own `@host` ivar.
resolves #1337

gRPC client: don't touch initialize

---

lib/tasks/coverage_report.rake

Every multiverse test run will accumulate new coverage directories. This task removes all directories in `lib` that begin with "coverage_"

Add coverage:clear task to remove coverage dirs

---

.simplecov

`SimpleCov::Formatter::SimpleFormatter` does not add a line about coverage
percentages at the end of every test run. It also does not create an HTML
output file. Instead, it only generates JSON files with the result
information and the last run data.
We don't use the HTML information very frequently for individual test runs, we can get that by running `coverage:report` if it's needed.

Use SimpleFormatter for test runs

---

test/multiverse/lib/multiverse/envfile.rb
test/multiverse/lib/multiverse/runner.rb
test/multiverse/lib/multiverse/suite.rb

The message that read something like: 
```
Running "/Users/jbunch/git/public/newrelic-ruby-agent/test/multiverse/suites/grpc" in 2 environments in serial
``` 
was slightly misleading, as the `2 environments` would be from a single Envfile-produced Gemfile for both `chain` and `prepend` instrumentation permutations. It would also get re-printed when the next instrumentation permutation would be executed.
Now, the message reads something like:
```
Running "logger" suite in 1 CHAIN environment and 1 PREPEND environment in serial
```
and will only be printed at the top of the suite's run.

Update multiverse run message

---

test/new_relic/agent/system_info_test.rb

Addresses deprecation warning when running using Minitest 5.16.3: 
```
DEPRECATED: Use assert_nil if expecting nil from /Users/kreopelle/dev/newrelic-ruby-agent/test/new_relic/agent/system_info_test.rb:219. This will fail in Minitest 6.
DEPRECATED: Use assert_nil if expecting nil from /Users/kreopelle/dev/newrelic-ruby-agent/test/new_relic/agent/system_info_test.rb:220. This will fail in Minitest 6.
```
and …

Use assert_nil for compatibility with Minitest 6

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml

with mongo:latest now pointing to v6, we have some work to do to figure
out our compatibility stance on Mongo v6 given that some of our older
Ruby versions are failing CI checks with it. it's possible that the
failures are exclusively limited to very old versions of the mongo gem
that are no longer supported anyhow. Until we determine if that's the
case, let's lock the mongo image tag to v5.

CI: lock mongo tag to a known good v5 version

---

newrelic_rpm.gemspec
test/environments/norails/Gemfile
test/environments/rails32/Gemfile
test/environments/rails40/Gemfile
test/multiverse/lib/multiverse/suite.rb
test/multiverse/suites/agent_only/Envfile
test/multiverse/suites/delayed_job/Envfile
test/multiverse/suites/rails/Envfile

With the exception of Rails 3.2- and Rails 4.0-related tests, our suites can successfully run on Minitest version 5.3.3. This gives us the opportunity to use Minitest 5.x related improvements and tools. 
Where Rails 3.2 and 4.0 are tested, version 4.7.5 has been preserved. 
Minitest 5.3.4 introduces a change that shuffles runnable objects before the test suite starts. This introduces some errors into our unit test suite, such as IO test failures. We'll work on jumping the 5.3.4 hurdles in another PR.
[here for …

Bump minitest to 5.3.3

---

test/new_relic/agent/configuration/server_source_test.rb
test/new_relic/agent/error_collector_test.rb
test/new_relic/agent/linking_metadata_test.rb
test/new_relic/agent/log_priority_test.rb
test/new_relic/agent/span_event_primitive_test.rb
test/new_relic/dependency_detection_test.rb

This PR addresses warnings thrown by Minitest during test runs related to duplicate names and unused variables.

CI: Minitest warnings

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml
test/multiverse/suites/typhoeus/Envfile

Use Ubuntu 22 for JRuby CI tests
- The GitHub Actions Ubuntu 22 image defaults to using JVM version 11.
Our CI tests cause JRuby to crash with that default. Switch to JVM 8,
which is preinstalled on the image and what we used with Ubuntu 18
- The Typhoeus multiverse suite still causes JRuby crashes. For now,
disable them when the specific JRuby and Ubuntu 22 combination is
present.
- Given that JRuby tests are permitted 60 minutes to run, don't bother
retrying them on failure

CI: Use Ubuntu 22 for JRuby

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml
.github/workflows/gem_notifications.yml
.github/workflows/scripts/setup_bundler
.github/workflows/scripts/setup_bundler_multiverse
.rubocop.yml
test/multiverse/suites/datamapper/Envfile
test/multiverse/suites/mongo/Envfile
test/multiverse/suites/redis/Envfile

updates to have our CI based entirely on Ubuntu 22, with Ruby v3.1 used
by default
- Update the CI Bundler setup scripts
- Ruby 2.2 needs `update_rubygems`, not `gem update --system`
- The setup-ruby action appears to leave us with the desired Bundler
version already installed. Check the version and don't bother with
installations and uninstallations if it exists
- Add debugging statements everywhere
- Don't attempt `bundle config` until the desired Bundler version is
known to be present
- Stop testing Datamapper with Ruby 2.2, to avoid Ruby crashes
- Stop testing Rails 2.3 with Ruby 2.5 (Ruby 2.2, 2.3, and 2.4 will still test it)
- Update the Mongo suite to fall back to a default Mongo version if a
`mongo` executable can't be found in `PATH`
- Don't test `redis` v5 yet
resolves #1112

CI: Use Ubuntu 22.04 LTS w/Ruby v3.1

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml

standardize on using the currently maintained `ruby/setup-ruby` action
and not the deprecated `actions/setup-ruby` one

CI: standardize on ruby/setup-ruby

---

lib/new_relic/agent/instrumentation/action_controller_subscriber.rb
newrelic_rpm.gemspec
test/agent_helper.rb
test/helpers/ruby_rails_mappings.rb
test/new_relic/agent/monitors/trace_context_request_monitor_test.rb
test/new_relic/agent/span_event_primitive_test.rb
test/new_relic/agent/transaction/segment_test.rb
test/new_relic/license_test.rb

- ActionControllerSubscriber instrumentation: don't attempt to grab @req
unless it's known to exist
- gemspec: remove the unused listen, rb-inotify, pry-nav,
pry-stack_explorer, guard, and guard-minitest. less surface area =
fewer issues
- update mocha in the hopes of addressing warnings from v1.9
- replace the removed pry gems with pry itself, but only for local dev
- stop (redundantly?) monkeypatching MiniTest assert_match
- stop shadowing outer variables

CI: address warnings

---

.github/workflows/ci.yml

We've had pretty consistent 92% coverage since the latest SimpleCov updates. Since we can expect that number, increase the threshold to 90% to ensure coverage does not drop too far.

Set failedThreshold to 90

---

.rubocop.yml

Enforce a line length max with RuboCop, with a TODO to actually have the
value be reasonable in the future

RuboCop: stop permitting infinitely long lines

---

lib/tasks/coverage_report.rake

We use the SimpleFormatter by default for regular test runs. The HTML
format is most useful to use when we generate a collated report.
This PR will make sure HTML is created when the rake task is called.

Use HTMLFormatter in rake task

---

CHANGELOG.md
infinite_tracing/lib/infinite_tracing/worker.rb
infinite_tracing/test/infinite_tracing/worker_test.rb
lib/new_relic/agent/threading/agent_thread.rb
lib/new_relic/agent/tracer.rb
test/new_relic/agent/threading/agent_thread_test.rb

Missing unscoped metrics were found to be erroneously marked as an unscoped metric on a long running puma transaction that does not finish. This pr makes the following changes to prevent any unscoped metrics from being attached to transactions incorrectly. 
- All Threads created by the agent now use AgentThread (infinite tracing was not previously)
- AgentThread disables tracing when spawning threads
- When tracing threads
-  the agent will no longer copy over the current_transaction if tracing is disabled
- the agent will not attempt to create a segment if …

Bugfix: thread tracing causes missing unscoped metrics

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml
test/new_relic/agent/tracer_test.rb
test/new_relic/agent/transaction/datastore_segment_test.rb

address CI deprecation warnings
- upgrade actiona/checkout to v3
- actions/checkout performs `git init` before the checkout, which a) defaults to using a `master` branch, and b) emits a stream of "hint" warnings letting us know how to set a default branch name. Globally set a `main` branch name to address these items.
- Mocha: use an explicit `nil` response
- RabbitMQ: stop using the deprecated health check, switch to a modern "fine grained" check

CI: deprecation warning fixes

---

.github/workflows/scripts/slack_gem_notifications/notifications_methods.rb
newrelic_rpm.gemspec
test/new_relic/gem_notifications_tests.rb

When Gabby notifies us about a new gem version that has recently become
available, it would be preferable to:
- mention rc1/beta/preview releases for the newly released version to
give the team a heads up about development work being done on the gem
- only report stable versions for the previously released version.
This way, if a gem goes `v1.5 -> v2.0.preview -> v2.0.rc1 -> v2.0.rc2`
then the notifications will always tell us about the previous stable
version, not the previous beta version.
Currently, the notifications look like this:
- v1.5 to v2.0.preview
- v2.0.preview to v2.0.rc1
- v2.0.rc1 to v2.0.rc2
With the included changes, the notifications would instead read:
- v1.5 to v2.0.preview
- v1.5 to v2.0.rc1
- v1.5 to v2.0.rc2
This way we are notified of beta releases and don't have …

Gabby: report only stable versions for 'previous'

---

test/multiverse/suites/rake/Envfile

when rake is tested with Rails, sprockets is brought in and has a `rack < 3` dependency. the multiverse suite helpers see the unpinned rack version and bring in `rackup`, which won't work with `rack < 3`.
lock rake + rails to rack v2 to let the multiverse suite helpers know to not bring in `rackup`.

CI: for rake + rails, use rack v2

---

newrelic_rpm.gemspec
test/multiverse/suites/sequel/Envfile

- Sqlite3 1.5.0 was released and has a minimum ruby version of 2.6, so we now pin the version on rubys < 2.6 …

Sqlite3 1.5.0 not compatible with ruby < 2.6

---

.rubocop_todo.yml
test/agent_helper.rb
test/multiverse/suites/rails/error_tracing_test.rb
test/new_relic/agent/configuration/default_source_test.rb
test/new_relic/agent/configuration/yaml_source_test.rb
test/new_relic/agent/external_test.rb
test/new_relic/agent/threading/backtrace_service_test.rb
test/new_relic/agent/threading/thread_profile_test.rb
test/new_relic/agent/transaction/slowest_sample_buffer_test.rb

For #1403
For most contributions it is strongly recommended …

Fix Minitest/AssertEmpty Rubocop exclusions

---

.rubocop_todo.yml
infinite_tracing/test/infinite_tracing/agent_integrations/datastore_segment_test.rb
infinite_tracing/test/infinite_tracing/agent_integrations/segment_test.rb
test/multiverse/suites/sidekiq/sidekiq_instrumentation_test.rb
test/new_relic/agent/external_test.rb
test/new_relic/agent/new_relic_service_test.rb
test/new_relic/agent/transaction/external_request_segment_test.rb

For #1403
For most contributions it is strongly recommended …

Adjust code for RefuteEmpty rubocop rule

---

.github/workflows/performance_tests.yml

The performance path name was recently changed to `performance_results.txt`, which is more specific to the results than the previous name. However, the original saved filename wasn't changed, which caused a failure. This PR updates that name.
Github Actions when a pull request is made. More details on running the tests locally can be …

Update performance results filename

---

.github/workflows/ci.yml

SimpleCov is currently running on forks, making our CI fail when contributors make PRs. This commit tests a logic change to hopefully stop SimpleCov on forks. …

Stop SimpleCov on forks

---

test/multiverse/suites/sidekiq/Envfile

sidekiq v6.5.6 is now available, time to go back to testing the latest version of sidekiq by specifying `nil` for the version constraint

CI: re-enable 'latest' testing for sidekiq

---

.github/workflows/ci_cron.yml
lib/new_relic/agent/samplers/vm_sampler.rb
lib/new_relic/agent/vm/mri_vm.rb
lib/new_relic/agent/vm/snapshot.rb
test/new_relic/agent/samplers/vm_sampler_test.rb
test/new_relic/agent/vm_test.rb

* Start using Ruby 3.2.0-preview2 for CI
* Support Ruby 3.2's two separate VM stats, `:constant_cache_invalidations` and `:constant_cache_misses`.
Prior to Ruby 3.2, Ruby offered a `:global_constant_state` VM stat that the New Relic Ruby agent used to report on constant cache invalidations.
Ruby 3.2 offers improved statistics for constants and has replaced `:global_constant_state` with 2 new attributes,
`:constant_cache_invalidations` and `:constant_cache_misses`. The New Relic Ruby agent will use `:constant_cache_invalidations` for its existing reporting of invalidations and will also start to report on constant cache misses when Ruby 3.2+ is present.
Resolves #1059
NOTE: the CI cron tests against 3.2.0-preview2 were confirmed with …

Ruby 3.2 updates

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml

* MongoDB v6 does not work on Ruby 2.4 and below
* We'd like to have newer Rubies continue to test on the latest MongoDB to help us know when there's breaking changes to our instrumentation
* This change conditionally installs a compatible mongo image based on the `matrix.ruby_version` value
Closes: #1351 
All Rubies tested with the database group in #1449 
~~- [ ] Include a security review link, if applicable~~

Add condition to select MongoDB image to install

---

.rubocop.yml
infinite_tracing/lib/infinite_tracing/channel.rb
infinite_tracing/lib/infinite_tracing/client.rb
infinite_tracing/lib/infinite_tracing/connection.rb
infinite_tracing/test/infinite_tracing/channel_test.rb
infinite_tracing/test/infinite_tracing/client_test.rb
lib/new_relic/agent/configuration/default_source.rb
newrelic.yml

- Introduce a new `infinite_tracing.batching` config parameter with a boolean value defaulting to `false`. When `true`, Infinite Tracing's RecordSpanBatch RPC (previously existing but inaccessible) will be used to batch requests to the Trace Observer
- Introduce a new `infinite_tracing.compression_level` config parameter with a string value defaulting to `'none'`. When changed to a value of `'low'`, `'medium'`, or `'high'`, Infinite Tracing's gRPC client will use that compression level for outbound data.

Infinite Tracing: support batching and compression

---

test/new_relic/agent/transaction/segment_test.rb
test/new_relic/agent/transaction_test.rb

Using infinite loops to saturate Ruby ObjectSpace on every single CI run is not ideal.
Our guid generation logic used to be `SecureRandom` based, and used to run into issues when a systems resource limit was hit and access to `/dev/urandom` would fail.
When we
[switched](https://github.com/newrelic/newrelic-ruby-agent/commit/1294c5bb50640752378b9d9faa2f55ac3dd0dbcd) away from `SecureRandom`, a decision was made to test the new more fault tolerant guid generation logic by inducing the exhaustion of the host machine's file descriptors and proving that guid generation still works.
These tests are slow on modern cloud based devices with lots of resources, problematic when ran by multitasking devs locally, and simply do not provide us with value anymore. The `refute` lines inside the infinite …

CI: remove file descriptor exhaustion tests

---

lib/new_relic/agent.rb
lib/new_relic/agent/attribute_filter.rb
lib/new_relic/agent/new_relic_service.rb
lib/new_relic/agent/vm/mri_vm.rb

refactorings with an aim of keeping the ABC size per method below the RuboCop default of 17

some refactorings to satisfy ABC size limits

---

test/multiverse/suites/rails_prepend/prepended_supportability_test.rb
test/multiverse/suites/tilt/Envfile
test/multiverse/suites/tilt/tilt_instrumentation_test.rb

Many of our Rails tests as well as tests for other instrumented gems use Haml. With Haml's new release yesterday, a few areas that have unlocked Haml versions (some areas we control, some we seemingly don't) upgraded to version 6.0 when it was released September 21, 2022. Here's an overview of the changes made to our test suite to get things passing again.
* Use Haml::Template for Tilt metric name if Haml 6.0+
* Use Haml ~> 5.2.2 for testing with Tilt 1.4.1 (this version doesn't have a lock on accepted Haml versions, but seems incompatible with Haml 6.0)
* Create a conditional value for `rails_prepend` Action View metrics based on Haml version
Closes: #1456 
verify your changes don't break …

Haml 6.0 Release Fixes

---

test/multiverse/suites/padrino/Envfile

sinatra v3 (released 2022-09-26) seems to have frozen the `CALLERS_TO_IGNORE` array, which padrino tries to concatenate onto
for now, stick with testing sinatra < 3 until there's a new padrino release

padrino tests: lock to sinatra < 3

---

test/multiverse/suites/grpc/Envfile

grpc 1.49.1 is not compatible with Ruby 2.5 due to a dependency requiring Ruby 2.6+. This update should allow our CI to pass.

Add Ruby version constraints to grpc Envfile

---

test/multiverse/README.md
test/multiverse/lib/multiverse/runner.rb

when performing multiverse tests, one can now specify a 'method' filter
ex: `bundle exec rake test:multiverse[rake,method=prepend]`

CI: add a 'method' filter

---

test/multiverse/lib/multiverse/suite.rb

now that #1475 has delivered a 'method' filter, we should update the notification message at the start of a run accordingly.
before:
```
$ bundle exec rake test:multiverse[grpc,method=chain]
Running "grpc" suite in 2 CHAIN environments and 2 PREPEND environments in parallel
```
after:
```
$ bundle exec rake test:multiverse[grpc,method=chain]
Running "grpc" suite in 2 CHAIN environments in parallel
```
(this is in response to PR feedback on #1475)

multiverse: update "Running..." notification

---

test/multiverse/suites/rack/rack_builder_test.rb
test/multiverse/suites/rake/instrumentation_test.rb

until we figure out how to get the entirety of our CI suite into the year 2013, skip the use of MiniTest's v5's 3 argument `stub` method when running tests under old MiniTest versions

CI: skip MiniTest v5 syntax under MiniTest v4

---

.rubocop.yml
lib/new_relic/agent/instrumentation/memcache.rb
lib/new_relic/agent/new_relic_service.rb
lib/new_relic/collection_helper.rb
test/new_relic/agent/tracer_test.rb
test/new_relic/agent/transaction_test.rb
test/performance/suites/active_record_subscriber.rb

Enable rubocop's `style/commentannotation` and address errors. Documentation on this cop [lives here](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/CommentAnnotation) and is enabled `true` by default.
Closes #998
[here for …

Enable rubocop style/commentannotation

---

.rubocop_todo.yml
test/agent_helper.rb
test/multiverse/suites/agent_only/error_events_test.rb
test/multiverse/suites/agent_only/transaction_events_test.rb
test/multiverse/suites/rails/parameter_capture_test.rb
test/multiverse/suites/sequel/sequel_plugin_test.rb
test/new_relic/agent/agent/connect_test.rb
test/new_relic/agent/attribute_processing_test.rb
test/new_relic/agent/commands/agent_command_router_test.rb
test/new_relic/agent/configuration/manager_test.rb
test/new_relic/agent/configuration/security_policy_source_test.rb
test/new_relic/agent/connect/request_builder_test.rb
test/new_relic/agent/database_test.rb
test/new_relic/agent/heap_test.rb
test/new_relic/agent/method_visibility_test.rb
test/new_relic/agent/new_relic_service_test.rb
test/new_relic/agent/priority_sampled_buffer_test.rb
test/new_relic/agent/transaction/trace_node_test.rb
test/new_relic/agent/transaction/tracing_test.rb
test/new_relic/agent/transaction_sampler_test.rb
test/new_relic/noticed_error_test.rb

Address Minitest/AssertEmptyLiteral
- Remove from `rubocop_todo`
- Resolve offenses

Address Minitest/AssertEmptyLiteral

---

.rubocop_todo.yml
test/multiverse/suites/config_file_loading/config_file_loading_test.rb
test/new_relic/agent/configuration/default_source_test.rb
test/new_relic/agent/error_trace_aggregator_test.rb
test/new_relic/agent/method_tracer_helpers_test.rb
test/new_relic/agent/method_tracer_test.rb
test/new_relic/agent/transaction_sampler_test.rb
test/new_relic/metric_data_test.rb

Fix `assert_equal` errors and remove from `rubocop_todo` file. …

Address Minitest/AssertEqual

---

.rubocop_todo.yml
test/agent_helper.rb
test/multiverse/suites/rails/active_support_logger_test.rb
test/multiverse/suites/sequel/sequel_plugin_test.rb
test/multiverse/suites/sinatra_agent_disabled/shim_test.rb
test/new_relic/agent/audit_logger_test.rb
test/new_relic/agent/configuration/manager_test.rb
test/new_relic/agent/configuration/orphan_configuration_test.rb
test/new_relic/agent/error_trace_aggregator_test.rb
test/new_relic/agent/javascript_instrumentor_test.rb
test/new_relic/agent/method_visibility_test.rb
test/new_relic/agent/sampler_test.rb
test/new_relic/agent/tracer_state_test.rb
test/new_relic/control/instance_methods_test.rb
test/new_relic/environment_report_test.rb
test/new_relic/metric_data_test.rb

Address `Minitest/AssertIncludes` offenses and remove from `rubocop_todo`

Address Minitest/AssertIncludes offenses

---

.rubocop_todo.yml
test/new_relic/agent/agent_test.rb
test/new_relic/agent/pipe_channel_manager_test.rb
test/new_relic/agent_test.rb

Address `Minitest/AssertKindOf` and remove from `rubocop_todo`

Address Minitest/AssertKindOf

---

bin/nrdebug

bring `bin/nrebug` in line with RuboCop's ABC size score of 17 per method

ABC size improvements for bin/nrdebug

---

.rubocop_todo.yml
test/multiverse/suites/config_file_loading/config_file_loading_test.rb
test/new_relic/agent/agent_test.rb
test/new_relic/agent/configuration/manager_test.rb

Address `Minitest/RefuteEqual` offenses and remove from `rubocop_todo`

Address rubocop Minitest/RefuteEqual

---

lib/new_relic/agent/stats.rb
lib/new_relic/metric_data.rb

Refactor MetricData to adhere to Rubocop Metrics/AbcSize

---

.rubocop_todo.yml
test/multiverse/suites/agent_only/error_events_test.rb
test/multiverse/suites/rack/puma_rack_urlmap_test.rb
test/multiverse/suites/sequel/sequel_safety_test.rb
test/new_relic/agent/commands/thread_profiler_session_test.rb
test/new_relic/agent/configuration/environment_source_test.rb
test/new_relic/agent/configuration/manager_test.rb
test/new_relic/agent/configuration/security_policy_source_test.rb
test/new_relic/agent/configuration/yaml_source_test.rb
test/new_relic/agent/distributed_tracing/distributed_trace_payload_test.rb
test/new_relic/agent/distributed_tracing/trace_context_payload_test.rb
test/new_relic/agent/priority_sampled_buffer_test.rb
test/new_relic/agent/transaction/distributed_tracing_test.rb
test/new_relic/agent_test.rb
test/new_relic/language_support_test.rb

Address `Minitest/AssertTruthy` and remove from `rubocop_todo`

Address Minitest/AssertTruthy

---

.rubocop_todo.yml
test/multiverse/suites/rails/active_support_logger_test.rb
test/new_relic/agent/configuration/environment_source_test.rb
test/new_relic/agent/connect/request_builder_test.rb
test/new_relic/agent/error_trace_aggregator_test.rb
test/new_relic/agent/instrumentation/controller_instrumentation_test.rb
test/new_relic/agent/new_relic_service_test.rb
test/new_relic/agent/samplers/cpu_sampler_test.rb
test/new_relic/agent/samplers/memory_sampler_test.rb
test/new_relic/agent/stats_test.rb
test/new_relic/agent/transaction/abstract_segment_test.rb
test/new_relic/agent/transaction/datastore_segment_test.rb
test/new_relic/agent/transaction_sampler_test.rb
test/new_relic/marshalling_test_cases.rb
test/new_relic/noticed_error_test.rb

Address  rubocop `Minitest/LiteralAsActualArgument` and remove from `rubocop_todo`

Address Minitest/LiteralAsActualArgument

---

lib/tasks/helpers/format.rb

Refactor the Format module to adhere to Rubocop's Metrics/AbcSize linter as well as other Metrics/* linters

Rubocop Metrics/AbcSize for Format

---

lib/new_relic/recipes/capistrano3.rb
lib/new_relic/recipes/helpers/send_deployment.rb

Refactor Capistrano3 task for Metrics/*

---

lib/new_relic/agent/instrumentation/curb/instrumentation.rb

On long-running connection Curb use-cases like Elasticsearch clients with Curb transport the `request` variable points to the same Curb object not just for one request but for all.
Therefore, for each succesful request following the first one, `original_callback` points to the previous `on_failure` callback set by newrelic. So, an infinite chain of callbacks is created since newrelic's `on_failure` callback maintains a reference to `original_callback`.
The changes force `original_callback` to point to the actual original callback on subsequent requests instead of pointing to the newrelic's callback. That way no reference is maintained for newrelic's callback of the previous request & the memory leak is prevented by the GC.
_Before contributing, please read our [contributing …

Fix memory leak in the curb instrumentation

---

.github/actions/simplecov-report/README.md
.github/actions/simplecov-report/action.yml
.github/workflows/ci.yml

On the road to 100%/100%, it's important to not relapse with the introduction of new pockets of uncovered code. Let's keep the forward momentum by having the thresholds creep towards 100%/100% along with the tests.

Raise SimpleCov thresholds

---

CHANGELOG.md

backport of edits made by the docs team to the docs site version of the v8.11.0 release notes.
https://github.com/newrelic/docs-website/commit/2ac795a5d3879f52c5d750cdfe82847d993de4bd

CHANGELOG updates for v8.11.0

---

test/multiverse/lib/multiverse/suite.rb

A part of https://github.com/newrelic/newrelic-ruby-agent/issues/1181#issue-1251019953.
This PR addresses warnings thrown by Minitest during test runs related to unused variables.
1. `bundler_version`
- the local variable has been unused since it's introduced in https://github.com/ohbarye/newrelic-ruby-agent/commit/8e5886124ec017990400884285ad23dc6ccb9581#diff-5c92585b1f81da4bb4c96bff0e84e668725467ce36ed0b1915c68e866c50bbfdR140
2. `message`
- the local variable has been unused since it's introduced in https://github.com/ohbarye/newrelic-ruby-agent/commit/1dd1650afd840f90acfe51e4df96651bb3c5932a#diff-5c92585b1f81da4bb4c96bff0e84e668725467ce36ed0b1915c68e866c50bbfdR688
ref https://github.com/newrelic/newrelic-ruby-agent/actions/runs/3228491027/jobs/5284669752
The agent …

CI: Remove unused variables in test

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
newrelic.yml
test/multiverse/suites/agent_only/custom_analytics_events_test.rb
test/multiverse/suites/agent_only/event_data_collection_test.rb

The previous default value for `custom_insights_events.max_samples_stored` was 1000. The new default is 3000.
This new number is based on OATS results from multiple language agents in an effort to reduce the number of dropped custom insights events.
Closes #1540

Increase custom_insights_events.max_samples_stored

---

CHANGELOG.md

Add CHANGELOG entry announcing the deprecation of support for Ruby 2.3 in agent v9.0.0. 
#1452 …

Ruby 2.3 deprecation

---

lib/new_relic/agent/instrumentation/elasticsearch/instrumentation.rb
newrelic.yml
test/multiverse/suites/elasticsearch/elasticsearch_instrumentation_test.rb

* Set Elasticsearch datastore segment's operation attribute dynamically from `caller_locations`
* Elasticsearch 8 Playground tested here: https://staging.onenr.io/0dBj3VPrvRX (internal)
* Elasticsearch 7 Playground tested here: https://staging.onenr.io/0dBj3VWe2RX (internal)
* Previously, the operations were all `query`, the fallback value is proposed to become `perform_request` since the dynamic operations are set to the methods called, it seems odd to have the operation default be unrelated to any Elasticsearch method name. Totally down to revert this change, however!
* **BONUS**: Reorganizes and indents the `instrumentation.elasticsearch` config value in `newrelic.yml`
Relates to #1525

Set Elasticsearch operation dynamically

---

lib/new_relic/agent.rb

I found `BackgroundLoadingError` class is no longer used anywhere.
The class is introduced by [this commit](https://github.com/newrelic/newrelic-ruby-agent/commit/f2168ff0d446faa0e43968cfad9561817d2d473f#diff-61a8aeaee4649719c4136512deca7e826560b227c576e18114154a6082311830R47) (Apr 23, 2009), and it became unused by [this commit](https://github.com/newrelic/newrelic-ruby-agent/commit/9e1b428460dd954f3037864c7b2309901261e241#diff-918c7f140adbe155d6f5234c69b3373615a0e2bb395ee3339182e229c60f0156L52) (Feb 10, 2010).
GitHub Actions when a pull request is made. More details on running the tests locally can be …

Remove unused error class `BackgroundLoadingError `

---

CHANGELOG.md

update the cleanup entry for the v8.12.0 release to include the work done with #1548

update v8.12.0 cleanup entry for changelog

---

newrelic.yml

Found a few small typos while reading through the newrelic.yml file

Fix newrelic.yml typos

---

test/environments/rails32/Gemfile
test/environments/rails40/Gemfile
test/environments/rails41/Gemfile
test/environments/rails42/Gemfile
test/environments/rails50/Gemfile
test/environments/rails51/Gemfile
test/environments/rails52/Gemfile
test/environments/rails60/Gemfile
test/environments/rails61/Gemfile
test/environments/rails70/Gemfile
test/environments/railsedge/Gemfile
test/multiverse/lib/multiverse/suite.rb
test/multiverse/suites/config_file_loading/Envfile

Previously, jruby-openssl was being brought in for both CRuby where it is absolutely not needed and JRuby 9k+, where it is likely not needed as a separate Gemfile entry. The gem is now no longer brought in.

don't explicitly include jruby-openssl

---

test/multiverse/suites/sidekiq/Envfile

Sidekiq 7.0 changed the way logging works in the gem. Our tests for Sidekiq rely on the logger.
Disable the tests for the latest version (7.0) until we can address issue #1567

Temporarily disable Sidekiq 7.0 testing 

---

README.md

The previous source for the Community Plus header used `master` as the default branch. The source the repolinter looks for pulls from `main`.
Resolves #1569

Update Community Plus header image source

---

.github/workflows/ci_cron.yml

This removes the rubocop dependency for the our test jobs in our ci_cron.yml. We will still be notified of the rubocop failure, but we will also still have all of our tests run each night as well. This will make sure we don't miss any new failures unrelated to a new rubocop version.
GitHub Actions when a pull request is made. More details on running the tests locally can be found …

Scheduled CI tests run despite rubocop failures

---

lib/new_relic/agent/configuration/default_source.rb

Reordered configuration file modeled after [our docs page](https://docs.newrelic.com/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration/). A comment adds grouping structure and inside each group is alphabetized. Closes #1524 
The order is:
- Critical
- General
- Transaction tracer
- Error collector
- Browser monitoring
- Analytics events
- Transaction events
- Application logging
- Attributes
- Audit log
- Autostart
- Code level metrics
- Cross application tracer
- Custom attributes
- Custom events
- Datastore tracer
- Disabling
- Distributed tracing
- Elasticsearch
- Heroku
- Infinite tracing
- Instrumentation
- Message tracer
- Mongo
- Process host
- Rake
- Resque
- Rules
- Sidekiq
- Slow SQL
- Span events 
- Strip exception messages
- Thread profiler
- Utilization
- …

Group critical and optional configs

---

lib/new_relic/local_environment.rb
test/multiverse/suites/unicorn/Envfile

With version 3.0.0 of Rack in play, the agent can be fooled into thinking that web dispatching duties are being handled by Webrick. This is because the agent performs a less strict test for Webrick compared to other dispatchers; checking only for the existence of related namespaces to be defined.
With these changes, the agent will now treat Webrick as the last dispatcher checked after all other anticipated production use dispatchers have not been located. Specifically, this means that Webrick is checked after Unicorn, Rainbows, and FastCGI; all of which may have been incorrectly reporting as having Webrick as the dispatcher if Rack v3.0.0 was being used.
Resolves #1394

Correctly identify Unicorn when used with Rack v3

---

lib/new_relic/rack/browser_monitoring.rb
test/multiverse/suites/rails/Envfile
test/multiverse/suites/rails/action_controller_live_rum_test.rb

As of v2.0.0, rack-test defaults to HTTP/1.0 to work around the fact some apps return Transfer-Encoding: chunked responses, which rack-test doesn't have a decoder for. See [rack-test discussion](https://github.com/rack/rack-test/issues/300) on this decision.
Only HTTP/1.1 supports chunking, which our [`steaming?`](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/rack/browser_monitoring.rb#L106-L111) method checks for. For streaming tests to work with rack-test v2, we need to specify HTTP/1.1 when using streaming.
Closes #1222

NR-1222/rack-test-v2

---

CHANGELOG.md
lib/new_relic/agent/tracer.rb
test/new_relic/agent/tracer_test.rb

When support for Ruby 2.0 was dropped in version 8.0.0 of the agent, the agent API methods were updated to use the required keyword argument feature built in to Ruby, rather than manually raising `ArgumentError`'s. The API method NewRelic::Agent::Tracer.in_transaction removed the ArgumentError raised by the agent, but did not update the method arguments to identify category as a required keyword argument. resolves #1583 
verify your changes don't break existing …

Update NewRelic::Agent::Tracer.in_transaction to identify category as a required kwarg

---

infinite_tracing/test/infinite_tracing/channel_test.rb
infinite_tracing/test/infinite_tracing/config_test.rb
test/agent_helper.rb
test/multiverse/suites/agent_only/audit_log_test.rb
test/multiverse/suites/grpc/grpc_server_test.rb
test/multiverse/suites/grpc/helper_test.rb
test/multiverse/suites/rack/rack_builder_test.rb
test/multiverse/suites/rails/error_tracing_test.rb
test/multiverse/suites/rails/parameter_capture_test.rb
test/multiverse/suites/resque/instrumentation_test.rb
test/new_relic/agent/agent/connect_test.rb
test/new_relic/agent/autostart_test.rb
test/new_relic/agent/error_collector_test.rb
test/new_relic/agent/event_aggregator_test.rb
test/new_relic/agent/hostname_test.rb
test/new_relic/agent/instrumentation/rails/active_record_subscriber.rb
test/new_relic/agent/method_tracer_params_test.rb
test/new_relic/agent/monitors/synthetics_monitor_test.rb
test/new_relic/agent/new_relic_service/json_marshaller_test.rb
test/new_relic/agent/new_relic_service_test.rb
test/new_relic/agent/rules_engine_test.rb
test/new_relic/agent/stats_test.rb
test/new_relic/agent/system_info_test.rb
test/new_relic/agent/transaction_test.rb
test/new_relic/agent/utilization_data_test.rb
test/new_relic/language_support_test.rb
test/new_relic/slack_notifications_tests/gem_notifier_tests.rb

Resolve Minitest/EmptyLineBeforeAssertionMethods rubocop failures

---

CHANGELOG.md
lib/new_relic/agent/method_tracer_helpers.rb
test/new_relic/agent/method_tracer_helpers_test.rb

This resolves the error caused by setting add_method_tracer on a private method. Previously, the agent would fail to check the private method as an instance method because it was not included in the instance_methods array, so it attempted to record it as a class method, resulting in the following error in the logs
```
WARN : Unable to determine source code info for 'Example', method 'private_method' - NameError: undefined method 'private_method' for class '#<Class:Example>'
```
resolves #1589 Thanks @jdelStrother for the suggested fix!
The …

Bugfix: Record code level metric attributes for private methods

---

CHANGELOG.md

update the CHANGELOG to reference the [PR
1600](https://github.com/newrelic/newrelic-ruby-agent/pull/1600) change.

update v8.13.0 CHANGELOG for Rack::Builder#run

---

test/multiverse/suites/rack/example_app.rb

rework example app 3's `initialize` method to work properly with Rack 3 and Ruby 3.2.0-preview2

CI: address Rack 3 / Ruby 3.2.0-preview2 issue

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/sidekiq/client.rb
lib/new_relic/agent/instrumentation/sidekiq/extensions/delayed_class.rb
lib/new_relic/agent/instrumentation/sidekiq/server.rb
test/multiverse/suites/sidekiq/Envfile
test/multiverse/suites/sidekiq/sidekiq_instrumentation_test.rb

* Conditionally stop attempting to apply instrumentation to Delayed Extensions, which were dropped in v7.0. Attempting to do so was causing the installation of Sidekiq instrumentation by the agent to fail when used with Sidekiq v7.0.
* Have the agent's client and server middleware classes inherit from the new Sidekiq v7.0 middleware base classes.
resolves #1567

Support Sidekiq v7.0+

---

lib/new_relic/agent/instrumentation/redis.rb
lib/new_relic/agent/instrumentation/redis/chain.rb
lib/new_relic/agent/instrumentation/redis/instrumentation.rb
lib/new_relic/agent/instrumentation/redis/middleware.rb
lib/new_relic/agent/instrumentation/redis/prepend.rb
test/multiverse/suites/redis/Envfile
test/multiverse/suites/redis/redis_instrumentation_test.rb

Co-authored-by: hramadan <hramadan@newrelic.com>
Redis gem 5.x comprises a major structural refactor for the library.
* Calls to methods like get and set are no longer routed through `call`, but through a method named `call_v`
* The methods we instrument have been moved into a new library, redis-client, a dependency of the redis gem.
* Prepending onto the new library's class (::RedisClient) for the `call_v` and connect methods maintains consistent reporting behavior with earlier versions of Redis.
* The location, behavior, and arguments of pipelined and multi methods changed.
* In previous versions, pipeline and multi calls were routed through a method named `call_pipeline`. There is a similar method in Redis 5.x named `call_pipelined`. However, this method is not defined in …

Update Redis instrumentation to support v5

---

lib/new_relic/agent/instrumentation/sidekiq/extensions/delayed_class.rb

Added TODO to remove instrumentation for Sidekiq delayed extensions now that they are no longer available in Sidekiq v7+

Sidekiq delayed extensions support TODO

---

lib/new_relic/agent/instrumentation/excon.rb
test/multiverse/suites/excon/Envfile

Removes testing versions of Excon that aren't our minimum supported version or the latest version. There are no significant changes between versions that would require separate testing. 
Related to #794

Nr794 update excon version testing

---

CHANGELOG.md

Update the 8.13.0 changelog to include Redis v5 support

Add Redis v5 support to CHANGELOG

---

lib/new_relic/control/instrumentation.rb

This change will log a message to our users if they're on Ruby 2.3, warning them about the eventual removal of support.

Create Ruby 2.3 logged deprecation message

---

lib/new_relic/agent/instrumentation/active_merchant.rb
lib/new_relic/agent/instrumentation/acts_as_solr.rb
lib/new_relic/agent/instrumentation/authlogic.rb
lib/new_relic/agent/instrumentation/data_mapper.rb
lib/new_relic/agent/instrumentation/delayed_job_instrumentation.rb
lib/new_relic/agent/instrumentation/rainbows_instrumentation.rb
lib/new_relic/agent/instrumentation/sidekiq.rb
lib/new_relic/agent/instrumentation/sinatra.rb
lib/new_relic/agent/instrumentation/sunspot.rb
lib/new_relic/control/instrumentation.rb

This information can be accessed using other means. We don't need a metric.

Remove record_metric calls for deprecated gems

---

lib/new_relic/agent/instrumentation/excon.rb
test/multiverse/suites/excon/Envfile
test/new_relic/http_client_test_cases.rb

- Test the minimum supported version of Excon
- Add deprecation message
- Don't test JRuby on old versions of Excon
Related to #794

Test minimum supported version

---

lib/new_relic/agent/instrumentation/redis.rb
lib/new_relic/agent/instrumentation/redis/constants.rb
lib/new_relic/agent/instrumentation/redis/instrumentation.rb

the nightly CI system is reporting tens of thousands of 'already defined constant' warnings from the new Redis instrumentation changes.
moving the constants out into a class to help with this

move Redis instrumentation constants to a class

---

test/multiverse/suites/excon/excon_test.rb

to prevent older Excon gem versions from being unable to force encoding on a frozen string, use `String.new` to set the body string in the unit tests

CI: use non-frozen strings for Excon testing

---

test/new_relic/agent/distributed_tracing/distributed_trace_payload_test.rb

to fix a CI issue, don't assume that the `#instance_variables` responses from 2 objects of the same type will have identical ordering

CI: ensure 8T json test ivars are sorted similarly

---

CHANGELOG.md

I don't think we have any entries to add, after taking a look at the [PRs merged since our last release](https://github.com/newrelic/newrelic-ruby-agent/pulls?page=2&q=is%3Apr+merged%3A%3E%3D2022-10-26). 
However, I saw a few things I wanted to update: 
* Add links to the community member's GitHub profile (we did this on 8.12) 
* Make the version number abbreviation consistent (chosen form example: v5.0)
* Remove "we" from Redis entry
* Wrap `add_method_tracer` method name in backticks

Minor changelog edits

---

.github/workflows/ci_cron.yml

workflow_dispatch allows workflows to be run on demand in the GitHub UI

Add workflow_dispatch to ci_cron

---

test/multiverse/suites/rails/Envfile

Remove rack-test references from Rails envfile.
TODOs added with #1220
This issue was fixed by #1591
Closes #1442

Remove rack-test references from Rails envfile

---

test/new_relic/agent/new_relic_service_test.rb

rather than upgrade to `cgi` v0.3.5 to mitigate
[CVE-2021-33621](https://www.ruby-lang.org/en/news/2022/11/22/http-response-splitting-in-cgi-cve-2021-33621/), let's just stop using CGI

stop using CGI

---

test/new_relic/agent/system_info_test.rb

There are 3 ways to set the value of `num_logical_processors`: 1 primary and 2 fallback options. Previously, testing covered the second fallback option, but not the first. This commit adds a test for the first fallback value.
Closes #1431

Test darwin hw.logicalcpu > 0

---

lib/new_relic/recipes/helpers/send_deployment.rb

PR https://github.com/newrelic/newrelic-ruby-agent/pull/1498 introduced a regression in the resolution of `changelog` content. Originally, when `newrelic_revision` or `newrelic_changelog` was missing and SCM was in use, revision/changelog was taken from SCM (https://github.com/newrelic/newrelic-ruby-agent/pull/1498/files#diff-8617c3d884fd8d418ce71c6e5c8b3574b405debef725642d04cd1fa2db1d0596L39). 
However, refactoring kept this logic only for `revision` (https://github.com/newrelic/newrelic-ruby-agent/pull/1498/files#diff-62409e781fcfec20b77d79fd9f324cd395030f9b7ae9fb3a85c4a0e92f7add3dR39), not `changelog` (https://github.com/newrelic/newrelic-ruby-agent/pull/1498/files#diff-62409e781fcfec20b77d79fd9f324cd395030f9b7ae9fb3a85c4a0e92f7add3dR31). 
This PR adds a fallback to the changelog …

Capistrano - lookup fallback changelog from git

---

CHANGELOG.md
test/new_relic/recipes/helpers/send_deployment_test.rb

here are some unit tests and a CHANGELOG entry for the community submission delivered by PR #1653

tests and CHANGELOG entry for PR 1653

---

test/multiverse/suites/sidekiq/sidekiq_with_redis_test.rb

We recently introduced a regression test for issue 1639, which involved Sidekiq v7.0.1.
The test made use of Sidekiq's `CompatClient` class, and leveraged its `_client` method to get at the underlying Redis client object.
With Sidekiq v7.0.2, `_client` is gone, and the underlying client can now be accessed with `@client`.

CI: compatibility fix for Sidekiq v7.0.2

---

test/new_relic/agent/transaction_sampler_test.rb

Re-enable `test_harvest_during_transaction_safety` test within Transaction Sampler tests. It was commented out because it used to have problems with the CI. We've made a lot of changes to our CI since the comment was written. It doesn't seem to be a problem anymore.
Closes: #1433 
For most …

Re-enable test_harvest_during_transaction_safety

---

.rubocop.yml
CHANGELOG.md
lib/new_relic/agent/instrumentation/redis/instrumentation.rb
test/multiverse/suites/redis/redis_instrumentation_test.rb

Redis instrumentation:
* update `call_pipelined_with_tracing` to yield early (instead of crashing) if a db value cannot be obtained
* rename `_nr_client` to `_nr_redis_client_config` to make it more clear that it holds a config object and not a client object, even though config getters can be called directly on the `redis` gem's client object
* update `_nr_redis_client_config` to add support for `redis-client` gem versions older than v0.11
* update `_nr_redis_client_config` to raise upon failing to get at the underlying config object
* minor exception handling updates to include class names
* update the unit tests accordingly
resolves #1650 
resolves #1671

Redis instrumentation: support older redis-client

---

test/new_relic/latest_changes_test.rb

PR #1679 removed the # from the end of the title. This fixes the test to match the new title format

Remove # from end of release notes title

---

CHANGELOG.md

update v8.13.1 CHANGELOG entry for GitHub username formatting consistency

CHANGELOG: use '@' for GitHub usernames

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/rails_notifications/action_view.rb
lib/new_relic/control/instance_methods.rb
lib/newrelic_rpm.rb
test/README.md
test/environments/rails40/config/initializers/test.rb
test/environments/rails41/config/initializers/test.rb
test/environments/rails42/config/initializers/test.rb
test/environments/rails50/config/initializers/test.rb
test/environments/rails51/config/initializers/test.rb
test/environments/rails52/config/initializers/test.rb
test/environments/rails60/config/initializers/test.rb
test/environments/rails61/config/initializers/test.rb
test/environments/rails70/config/initializers/test.rb
test/environments/railsedge/config/initializers/test.rb
test/new_relic/newrelic_rpm_test.rb

For Rails applications, the agent initialized before all other initializers with the `before: :load_config_initializers` hook.
Though this enables initializers to reference the `add_method_tracer` API, there are actions within the agent's initialization that load Rails framework libraries (ActiveJob, ActiveRecord, ActionView). This caused initializers referencing these libraries to be skipped entirely.
Since we only need the `add_method_tracer` API to be available before the initializers are run, the modules that include this API will be loaded before config initializers. All other agent-initialization activity will be loaded after config initializers.
Furthermore, ActionView was the only Rails framework library that did not have an `ActiveSupport.on_load` block around the instrumentation …

Defer agent initialization in Rails until after :load_config_initializers

---

test/multiverse/suites/redis/redis_instrumentation_test.rb

A redis-rb instrumentation update for v8.14.0 was initially going to perform an early yield but was later changed to not have to. The corresponding test needs to be updated to no longer refer to a now missing yield related variable.

CI: fix redis-rb instrumentation test

---

test/new_relic/agent/distributed_tracing/trace_context_cross_agent_test.rb

Add test to ensure expected and actual `vendors` match. Resolve TODO.
closes #1434

Add test for vendors

---

test/fixtures/cross_agent_tests/distributed_tracing/trace_context.json
test/new_relic/agent/distributed_tracing/trace_context_cross_agent_test.rb

The trace_context test cases received through cross-agent testing are out of spec according to W3C header naming convention, which these tests should follow. `vendors` should be `tracingVendors`. This update has been made.
To resolve the TODO of testing `vendors` (aka `tracingVendors`), a new test reaches into `header_data` (vs `tracestate` where other similar tests are pulling in data). For testing purposes, `header_data.trace_state_vendors` was added to the `actual_attributes` hash that we are testing.
closes #1434

Update test and test case 'vendors' key

---

lib/new_relic/agent/configuration/default_source.rb
newrelic.yml

* update `newrelic.yml` with `defer_rails_initialization` parameter
* update `default_source.rb` to backport the "have run" grammar change that was made to the CHANGELOG for this config parameter

update newrelic.yml with defer_rails_initialization parameter

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb

To communicate to customers the broken state of the config value, this PR strikes out the original CHANGELOG entry for the Rails initialization bugfix and adds a link to the issue to access updates.
This PR also updates the configuration description for `defer_rails_initialization` to note it does not work at this time.
Relates to #662 
GitHub Actions when a pull request is made. …

Update Rails initialization bugfix CHANGELOG entry

---

test/multiverse/suites/padrino/Envfile

Now that Padrino 0.15.2 is out with support for Sinatra 3, let's test Padrino with both Sinatra 2 and 3.
thanks, @nesquena

CI: test Padrino with both Sinatra 2 and 3

---

.github/workflows/ci_cron.yml
.github/workflows/scripts/setup_bundler
test/agent_helper.rb
test/multiverse/suites/sidekiq/sidekiq_instrumentation_test.rb
test/new_relic/agent/distributed_tracing/distributed_tracing_cross_agent_test.rb

This PR fixes the new rubocop-minitest failures and fixes new failures related to the rubygems version.

Update new rubocop-minitest failures and rubygems version issues

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml
CHANGELOG.md

Updates the CI to use the official release of 3.2.0
For most …

update CI to run 3.2.0 official release

---

.github/actions/annotate/action.yml
.github/actions/simplecov-report/action.yml
.github/workflows/ci.yml
.github/workflows/ci_cron.yml

Node 12 is deprecated for GitHub Actions and Node 16+ is required. This PR upgrades actions from the marketplace that have been identified by GitHub as running on Node 12 to newer versions. It also updates our self-written actions to use Node 16.
Actions run with deprecation warnings: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/3795916450 
One issue I'm seeing in the output with this change is a warning related to caching mysql: "Failed to restore: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2" 
I believe this is because it's running for the first time, so there isn't a cache to restore. We should keep an eye on this when the PR is merged.

Use Node 16 GitHub Actions

---

lib/new_relic/agent/agent_helpers/connect.rb
lib/new_relic/agent/event_loop.rb
lib/new_relic/agent/heap.rb
lib/new_relic/agent/javascript_instrumentor.rb
lib/new_relic/agent/range_extensions.rb
lib/new_relic/agent/transaction.rb
lib/new_relic/agent/transaction/abstract_segment.rb
lib/new_relic/agent/transaction/transaction_sample_buffer.rb
test/new_relic/agent/new_relic_service_test.rb
test/performance/suites/active_record_subscriber.rb

The following new default linters have been addressed in our code: 
* Style/MinMaxComparison
* Style/YodaExpression 

Fix new Rubocop linters

---

infinite_tracing/test/infinite_tracing/agent_integrations/agent_test.rb
infinite_tracing/test/infinite_tracing/agent_integrations/datastore_segment_test.rb
infinite_tracing/test/infinite_tracing/agent_integrations/external_request_segment_test.rb
infinite_tracing/test/infinite_tracing/agent_integrations/segment_test.rb
infinite_tracing/test/infinite_tracing/client_test.rb
infinite_tracing/test/infinite_tracing/connection_test.rb
lib/new_relic/agent/configuration/default_source.rb

PR 1723 was intended to enable batching everywhere, but default_source.rb was unfortunately overlooked.
enable batching in default_source.rb and leave the tests as-is for now (to be revisited when we tackle code coverage for 8T), given that batching was already covered with unit tests previously.

8T: enable batching in default_source.rb as well

---

lib/new_relic/agent/configuration/default_source.rb

There were some differences on the config page that didn't match our default_source file. The two should be in sync again with this PR.

Update default_source to match config docs

---

lib/new_relic/agent/configuration/default_source.rb

Preparing for the 8.15.0 release, there were a few changes made to the configuration documentation by the docs-website reviewer and some recommendations made by the automated Vale linter. 
* Remove capitalization from "trace observer"
* Update Active Support Custom Events description to remove passive voice and accidental pluralization 
These changes should keep our `default_source` file in sync with the configuration page.

Config description updates

---

test/environments/rails60/Gemfile
test/environments/rails61/Gemfile
test/environments/rails70/Gemfile
test/multiverse/suites/sequel/Envfile

Specify sqlite3 version by Ruby version
* Version 1.6.0 supports Ruby 2.7+
* Version 1.5.x supports 2.6
* Version 1.4.x supports 2.5
Add security patch versions for Rails 6.0, 6.1, 7.0

Update Gemfiles for Rails testing

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/active_support.rb
lib/new_relic/agent/instrumentation/active_support_subscriber.rb
lib/new_relic/agent/instrumentation/custom_events.rb
newrelic.yml
test/new_relic/agent/instrumentation/active_support_subscriber_test.rb
test/new_relic/agent/instrumentation/rails/active_support_subscriber.rb

Active Support has notifications built in to instrument caching-related activities, including:
* `cache_read`
* `cache_generate`
* `cache_fetch_hit`
* `cache_write`
* `cache_delete`
* `cache_exist?`
The payload always includes the `:key` and the name of the `:store` class. `cache_read` also includes whether the read is a `:hit`, and `:super_operation` when a read is used with `#fetch`.
https://guides.rubyonrails.org/active_support_instrumentation.html#active-support
When these operations are executed, a new segment will be started that includes the payload within the params attribute.
Closes #1514

Add Active Support instrumentation

---

lib/new_relic/agent/instrumentation/action_view_subscriber.rb
test/new_relic/agent/instrumentation/rails/action_view_subscriber.rb

- subscribe to `render_layout.action_view`
- add test for `render_layout.action_view`
- refactor ActionViewSubscriber's `start` and `finish` to accommodate for new `start` and `finish` methods inherited from NotificationsSubscriber
closes #1512

Subscribe to additional Action View topic

---

.rubocop.yml
CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/action_dispatch.rb
lib/new_relic/agent/instrumentation/action_dispatch_subscriber.rb
newrelic.yml
test/new_relic/agent/instrumentation/action_dispatch_subscriber_test.rb
test/new_relic/agent/instrumentation/rails/action_dispatch_subscriber.rb

Provide instrumentation for Action Dispatch based middleware calls by subscribing to and creating segments for all related Active Support notifications based events.
addresses #1511

Action Dispatch instrumentation

---

test/performance/lib/performance/console_reporter.rb

* disable cop that is currently bugged
* refactor a formatting line so that we don't mix named and unnamed arguments in a single array. NOTE: we can rely on `Float#round` this way now that we no longer support Ruby 1.8

RuboCop fixes

---

.github/workflows/ci_cron.yml

the check for workflow_dispatch event isn't working right, it's continuing to notify slack on manual runs. I think it isn't playing nicely with the always() potentially, so I moved it down into the second check we do at the step level instead. I also added an echo for the event name, just in case there is something not working right with matching the event name.

Fix for slack not notifying on manual run

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/action_cable_subscriber.rb
lib/new_relic/agent/instrumentation/rails_notifications/action_cable.rb
test/new_relic/agent/instrumentation/rails/action_cable_subscriber.rb
test/new_relic/agent/instrumentation/rails/active_support_subscriber.rb

* Add `broadcast` to subscribe call
* Update metric name to use `broadcasting` if available
* Refactor ActionCable to use NotificationsSubscriber `start` and `finish` methods

Add broadcast instrumentation for Action Cable

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/active_job.rb
lib/new_relic/agent/instrumentation/active_job_subscriber.rb
test/new_relic/agent/instrumentation/active_job_subscriber_test.rb
test/new_relic/agent/instrumentation/rails/active_job_subscriber.rb
test/simplecov_test_helper.rb

Subscribe to Active Job notifications and process the 7 (at the time of Rails v7.1.0.0.alpha) related events to produce additional instrumentation for the library.
resolves #1515

Active Job notifications subscriber

---

test/multiverse/lib/multiverse/runner.rb
test/multiverse/lib/multiverse/suite.rb

This PR just updates it so that if you pass in `method=prepend` to multiverse for a suite that it doesn't apply to, it will just emit a warning and then continue on as if no method was passed in. Just makes it a bit easier to make a bash alias that always run prepend/env=0 on all suites without having to deal with errors popping up because there is no prepend (like on rails).

Invalid multiverse method filter outputs warning instead of error

---

test/environments/lib/environments/runner.rb

For local dev, `bundle exec rake test:env` will cause an `IO.popen` subshell to spawn yet another instance of Rake. Any arguments passed to the outermost Rake task get ignored. Now they get sent to the subshell.
It is now possible to perform something like:
```shell
bundle exec rake test:env[railsedge] --trace
```
and have the `--trace` argument and any other take effect.
NOTE that the hack that applies this local dev only functionality assumes that arguments will always come after the Rake task arguments array and not before it.

env tests: support --trace and other args

---

lib/new_relic/agent/instrumentation/action_dispatch.rb
lib/new_relic/agent/instrumentation/action_mailbox.rb
lib/new_relic/agent/instrumentation/action_mailer.rb
lib/new_relic/agent/instrumentation/active_storage.rb
lib/new_relic/agent/instrumentation/active_support.rb

Make sure that each ActiveSupport notifications based instrumentation class respects its `disable_` config parameter

wire up disable_ config params for notifications

---

test/environments/norails/Rakefile
test/environments/rails32/Rakefile
test/environments/rails40/Rakefile
test/environments/rails41/Rakefile
test/environments/rails42/Rakefile
test/environments/rails50/Rakefile
test/environments/rails52/Rakefile
test/environments/rails60/Rakefile
test/environments/rails61/Rakefile
test/environments/rails70/Rakefile
test/environments/railsedge/Rakefile
test/new_relic/agent/instrumentation/active_job_subscriber_test.rb
test/new_relic/agent/instrumentation/rails/active_job_subscriber.rb

rails 6.0 seems to have issues retrying a job if the arg passed in is a class. it raises the error `ActiveJob::SerializationError: Unsupported argument type: Class`. However it's totally fine and works well if you aren't attempting to retry the job. It also works fine on 6.1+.
This works around the issue by using a string instead if on rails 6.0.
I also noticed some warnings when running the env tests because the warning helper was being called later when starting the env tests. I added it to the env test rake files so it will start working immediately instead. 
passing all: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/4019560610

Fix active job 6.0 failures when retry job

---

.github/workflows/ci_jruby.yml
.github/workflows/scripts/retry_command

I noticed the jruby intermittent multiverse failures seem to still end up failing, so I've increased the retry count. Since we don't have to wait on this CI for our PRs, increasing to 5 doesn't seem like it should be too much of a problem in the case of real failures, because at least hopefully now we'll stop seeing the intermittent failures constantly. 
I also added an extra output from the retry script to state failure.
verify your changes don't break existing …

Increase jruby CI attempts

---

CHANGELOG.md
infinite_tracing/lib/infinite_tracing/client.rb
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/rake/instrumentation.rb
lib/new_relic/agent/tracer.rb
newrelic.yml
test/multiverse/suites/concurrent_ruby/concurrent_ruby_instrumentation_test.rb
test/multiverse/suites/rake/Rakefile
test/multiverse/suites/rake/instrumentation_test.rb
test/multiverse/suites/rake/multitask_test.rb
test/new_relic/agent/tracer_test.rb

Enabled the config option `instrumentation.thread.tracing` in the default config. 
Updates tests that aren't expecting this config to be enabled. 
closes https://github.com/newrelic/newrelic-ruby-agent/issues/1089  …

Enable `instrumentation.thread.tracing` by default

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml

Lately we keep getting a job failing due to mysql not being started when we check it before running our multiverse tests. 
```
Run mysql --host 127.0.0.1 --port 32768 -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"
Warning: arning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:32768' (111)
Error: Process completed with exit code 1.
```
This PR should retry this command several times and sleep in between if each failure. Hopefully this should give mysql enough time to get started and able to respond to our command.

Attempt to resolve mysql not starting intermittently in github actions

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
newrelic.yml
test/new_relic/agent/instrumentation/rails/action_dispatch_subscriber.rb

the ActiveSupport event notifications based instrumentation for ActionDispatch overlaps too greatly with our existing Rails middleware instrumentation, leading to confusing and potentially costly overlap for Rails users.
ideally, we'd like to standardize on leveraging Rails notifications for all Rails instrumentation and remove any custom Rails instrumentation that overlaps. But in this case with ActionDispatch the notifications aren't available until Rails v6, and we aren't prepared at this time to stop supporting earlier Rails versions.
so for now, retain the notifications based instrumentation for ActionDispatch but have it configured - privately - to be disabled by default.

disable, make private ActionDispatch notifications

---

.github/workflows/scripts/retry_command

I noticed the jruby CI failed again and it looks like the script is still only ever trying twice. Turns out `count+=1` just appends 1 to the end like a string, not actually doing math! So that is now fixed. Previously I had only tested it with a retry attempt of 2, so I never caught that, this time I tried a few different values to make sure it's working as expected

Fix jruby retry script

---

CHANGELOG.md
lib/new_relic/agent.rb
lib/new_relic/supportability_helper.rb
test/multiverse/suites/agent_only/script/public_api_when_disabled.rb
test/new_relic/agent/supportability_test.rb
test/new_relic/agent_test.rb

This PR removes references to `NewRelic::Agent.disable_transaction_tracing`, which was deprecated in Ruby agent 5.4.0. 
Users are encouraged to use `NewRelic::Agent.disable_all_tracing` or `NewRelic::Agent.ignore_transaction` instead.
Related to #745

Remove support for `disable_transaction_tracing`

---

CHANGELOG.md
lib/new_relic/agent/transaction.rb
test/multiverse/suites/agent_only/set_transaction_name_test.rb

This updates how `set_transaction_name` works so it functions more as expected and accomplishes what customers have expected it to do. Now, when set_transaction_name is called with a different category that is already assigned, the category and name will be changed to what is passed in. Previously, nothing would happen if the category was different. 
The `set_transaction_name` api docs did not need to be updated because the way it is worded already implies that this is how it was supposed to work in the first place. 
closes #1064

Allow `set_transaction_name` to change name and category of current transaction.

---

lib/new_relic/agent/database.rb

Removing an unused constant.
- [newrelic/newrelic-ruby-agent/issues/1130] 
For …

Remove orphaned constant MYSQL_EXPLAIN_COLUMNS

---

lib/new_relic/agent/rules_engine/segment_terms_rule.rb

Removing an orphaned constant
[newrelic/newrelic-ruby-agent/issues/1130] Include a link to the related GitHub issue, if applicable …

Remove orphaned constant VALID_PREFIXED_SEGMENT_COUNT

---

test/README.md
test/script/run_tests

- I turned my bash functions into a script! It should make running tests simple and consistent across all the test types. Using the script, now we can run the unit, env, and multiverse tests basically the same way. This will help prevent the issue of forgetting which tests require which way to specify a test name or file.
- Added instructions to the test readme on using the test script and setting up aliases in your .bash_profile or .zshenv files. 
- Also updated the test readme to include a better way to specify test file and test name for the unit and env tests that works with both, instead of the previously documented way that doesn't. I did leave the old way at the bottom of the file in case we wanted it in the future, although I can remove it if that is preferred.

Add test running script and update test readme

---

lib/new_relic/agent.rb
test/new_relic/agent/rpm_agent_test.rb
test/new_relic/agent_test.rb

We have a `NewRelic::Agent.tl_is_sql_recorded?` helper method that isn't used by any code outside of the `test` directory.
Remove that orphaned code and refactor the affected tests accordingly.

remove NewRelic::Agent.tl_is_sql_recorded?

---

newrelic_rpm.gemspec

When rubocop releases a new version that changes how a cop works, it breaks our CI, which isn't great. Now we'll have control over when our rubocop versions get upgraded so we can make the changes necessary to satisfy the changes to rubocop. The versions I chose were just the ones that ran last night.

Pin rubocop versions

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/active_job.rb
test/multiverse/suites/rails/activejob_test.rb

ActiveJob isn't considered a MessageBroker. This PR cleans up naming and associated tests.
Closes #1151

Remove MessageBroker metric for ActiveJob

---

.github/workflows/ci_jruby.yml

Fix the typo on RETRY_ATTEMPTS env variable for the retry script for jruby multiverse
multiverse agent group running: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/4127424807/jobs/7130617406

Fix jruby retry script issue

---

README.md

The header image on our README was [updated](https://github.com/newrelic/newrelic-ruby-agent/pull/1815) to be in compliance with [open source policy](https://github.com/newrelic/newrelic-ruby-agent/issues/1720). We removed the image alt text but wanted to keep it for accessibility, and so the text was moved into the README directly.

Add alt text to main paragraph

---

lib/new_relic/agent/new_relic_service.rb
test/new_relic/agent/new_relic_service_test.rb

As per internal agent specs PR 585, make sure the `MaxPayloadSizeLimit` supportability metric includes the agent language name ("Ruby").
NOTE that the `MaxPayloadSizeLimit` part of the name itself isn't great, but we've decided to keep it as-is for now. The metric actually keeps a running tally of violations of the size limit and doesn't actually report what the configured limit is.

MaxPayloadSizeLimit supportability metric rename

---

test/multiverse/suites/grpc/Envfile

Lock grpc dependency `google-protobuf` to 3.21.12 for Rubies less than 2.5.9. 
google-protobuf 3.22 depends on ruby >=2.6, so we need to pin the version.

Update grpc gemlist

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/sidekiq/server.rb
test/multiverse/suites/sidekiq/sidekiq_instrumentation_test.rb

The agent attempts to accept dt headers from sidekiq jobs if distributed tracing is enabled. If the jobs are not being created with an agent that also has dt enabled, then this can result in an excessive number of warnings in the agent logs. This change will make it so that we will only attempt to accept the headers if it is not empty.
closes #1725

Remove DT warnings for sidekiq

---

test/multiverse/suites/typhoeus/Envfile

This test suite wasn't running on CRuby because there wasn't a check for the presence of Java before the /etc files, which exist on my machine

Update typhoeus multiverse suite_condition

---

test/multiverse/lib/multiverse/suite.rb

Multiverse CI tests:
- Always report the options used, pass or fail
- Don't report "No tests found with those options." just because a test failed or errored out.
- Rename "run_test" to "passed" to better convey that it contains the boolean result of the tests having been performed
Unfortunately given that the v5.x `run` method instantiates its own reporter that falls out of scope as soon as the method completes, all we are left with is a boolean result of the run. We can't make a determination as to whether or not 0 tests were found and force that condition to be an error condition with a non-zero exit code. Perhaps in future we could hook into the reporter chain with our own plugin to relay the test count back to us at the end.

Multiverse: always show options, fix 'not found'

---

CHANGELOG.md
lib/new_relic/agent/http_clients/abstract.rb
lib/new_relic/agent/http_clients/curb_wrappers.rb
lib/new_relic/agent/http_clients/excon_wrappers.rb
lib/new_relic/agent/http_clients/http_rb_wrappers.rb
lib/new_relic/agent/http_clients/httpclient_wrappers.rb
lib/new_relic/agent/http_clients/net_http_wrappers.rb
lib/new_relic/agent/http_clients/typhoeus_wrappers.rb
lib/new_relic/agent/transaction/distributed_tracer.rb
test/agent_helper.rb
test/new_relic/agent/transaction/distributed_tracer_test.rb
test/new_relic/http_client_test_cases.rb

* Adds a `#headers` method to all `NewRelic::Agent::HTTPClients::AbstractRequest` subclasses that returns a hash of the headers for the request 
* Updates `NewRelic::Agent::Transaction::DistributedTracer#log_request_headers` to check the `headers` argument's class. If it is an instance of `NewRelic::Agent::HTTPClients::AbstractRequest`, the `#headers` method will be called and logged. If not, the argument as-passed will be printed
Resolves #1657

Log request headers

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/action_controller_other_subscriber.rb
test/multiverse/suites/rails/action_controller_other_test.rb

If the action controller instrumentation was being called for a class that didn't respond to `controller_path`, the agent would error when trying to create the metric name for the segment. Now it will always check to make sure that method will work before calling it. I also updated this section to use the safe navigation operator now that we only support ruby 2.4+.
closes #1842

Prevent undfined method error in Action Controller instrumentation

---

.rubocop_todo.yml
lib/new_relic/agent/agent_helpers/start_worker_thread.rb
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/transaction.rb
lib/new_relic/cli/commands/deployments.rb
lib/new_relic/control/frameworks/rails.rb
lib/new_relic/rack/browser_monitoring.rb

Address some Metrics/AbcSize issues to get our maximum ABC size down closer towards a reasonable value
helps with #1520

RuboCop: address some AbcSize issues

---

.rubocop_todo.yml
lib/new_relic/agent/instrumentation/curb/chain.rb
lib/new_relic/agent/logging.rb
lib/new_relic/agent/transaction.rb

- refactor the logger's `call` method to adhere to AbcSize guidelines
- exempt `Transaction.new`
- exempt curb's chain based instrumentation
helps with #1520

RuboCop AbcSize driven updates:

---

test/multiverse/suites/typhoeus/Envfile

The suite condition is supposed to prevent typhoeus from running on the jruby CI, but currently it is not, this update should fix that.

Fix typhoeus suite condition for jruby CI

---

test/new_relic/agent/method_tracer_helpers_test.rb
test/new_relic/agent/tracer_test.rb

Fixes a couple of warnings related to the way our tests were written
There was a test that was the same name as another test (test_provides_accurate_info_for_an_instance_method)
```
/Users/tmcclure/projects/ruby-agent/test/new_relic/agent/method_tracer_helpers_test.rb:94: warning: method redefined; discarding old test_provides_accurate_info_for_an_instance_method
/Users/tmcclure/projects/ruby-agent/test/new_relic/agent/method_tracer_helpers_test.rb:82: warning: previous definition of test_provides_accurate_info_for_an_instance_method was here
```
There were 2 regexs used in tests that wanted it surrounded by parens 
```
/Users/tmcclure/projects/ruby-agent/test/new_relic/agent/tracer_test.rb:403: warning: ambiguity between regexp and two divisions: wrap regexp in parentheses or add a space …
```

Fix warnings in unit tests

---

README.md

The open source snippet was updated again to use HTML instead of markdown to display the image.
Closes #1836

Replace markdown header with HTML snippet

---

lib/new_relic/agent/distributed_tracing/cross_app_tracing.rb
lib/new_relic/agent/transaction/synthetics_sample_buffer.rb

This change supports microbenchmarking tests on Ruby 3.0 and Ruby 2.7

Use !value.nil? instead of nil != value

---

.rubocop.yml
lib/new_relic/agent/configuration/yaml_source.rb
lib/new_relic/agent/error_collector.rb
lib/new_relic/agent/instrumentation/ignore_actions.rb
lib/new_relic/agent/instrumentation/redis/constants.rb
test/new_relic/agent/configuration/orphan_configuration_test.rb

`!value.nil?` is more performant. The Ruby Style Guide says double negation should be avoided. https://rubystyle.guide/#no-bang-bang

Replace !! with !value.nil? or other equivalent

---

lib/new_relic/noticed_error.rb

[1fcfbdd2f7970b68182895c5c792a8c288a01b53](https://github.com/newrelic/newrelic-ruby-agent/commit/1fcfbdd2f7970b68182895c5c792a8c288a01b53) introduced some custom logic to `NoticedError` to treat the request URI in a special manner.
[9f7636e5072db0c5d63257be59ec4701e16348de](https://github.com/newrelic/newrelic-ruby-agent/commit/9f7636e5072db0c5d63257be59ec4701e16348de) removed this custom logic, but did not do enough clean up. A comment and a code block remained that will no longer effect the noticed error's agent attributes hash.
Removed the defunct code.

NoticedError: remove defunct request.uri feature

---

test/script/run_tests

The `run_tests` script now supports partial filename matches, allowing us to run tests from a single file by providing a partial match for that file's name.
For example, instead of:
```shell
bert test/new_relic/noticed_error_test.rb
```
we can now simply do:
```shell
bert noticed_error
```

run_tests: support partial filenames

---

lib/new_relic/agent/instrumentation/active_record_helper.rb

This pull request adds the [Amazon Timestream ActiveRecord Adapter](https://rubygems.org/gems/activerecord-amazon-timestream-adapter) to the list of known AR adapters. I don't know which are the requirements for relevance here, but if this gem doesn't meet them, let me know.
- ~[ ] Include a link to the related GitHub issue, if applicable~ N/A
- ~[ ] Include a security review link, if applicable~ N/A

Adds Amazon Timestream ActiveRecord Adapter

---

lib/new_relic/agent.rb
lib/new_relic/supportability_helper.rb
test/new_relic/agent_test.rb

Adds the api method `NewRelic::Agent.set_user_id`.
closes https://github.com/newrelic/newrelic-ruby-agent/issues/1847

Error inbox add set_user_id API method

---

CHANGELOG.md
lib/new_relic/agent.rb
lib/new_relic/agent/error_collector.rb
lib/new_relic/agent/error_trace_aggregator.rb
lib/new_relic/noticed_error.rb
lib/new_relic/supportability_helper.rb
test/new_relic/agent/error_collector_test.rb
test/new_relic/agent/error_trace_aggregator_test.rb
test/new_relic/agent_test.rb
test/new_relic/noticed_error_test.rb

Allow the customer to register a proc to be invoked on each noticed error in order to associate each noticed error with an error group
Changes made:
- A new public `set_error_group_callback` API method exists. It must be given a Ruby proc or lambda (must be of type `Proc`)
- When a noticed error is created by the error collector, it will invoke the callback with a hash of information about the error, and apply the resulting error group string (if returned) as the error group.
- Any noticed error with an error group property set will have that error group name present in its agent attributes with the key `error.group.name`.
- Internal errors (of which we only have a single stats hash related type currently) will now be routed through the error collector's method for creating a noticed …

errors inbox fingerprinting

---

lib/new_relic/noticed_error.rb
test/new_relic/agent/error_collector_test.rb
test/new_relic/agent_test.rb

`NewRelic::Agent::ErrorCollector#create_noticed_error`, which is the sole consumer of `NoticedError#error_group=`, ends up calling `NoticedError#processed_attributes` fully 3 times in order to build the hash that is passed to the customer error group callback.
As a result, the agent attributes for the noticed error end up being memoized. Because of the memoization, the agent attributes hash is not rebuilt later on when it comes time to submit those attributes to the collector.
Updated `NoticedError#error_group=` to effectively bust the memoization cache and ensure that the error group name makes it into the agent attributes hash.

NoticedError: update attr cache for error group

---

lib/new_relic/agent.rb

The current location of this constant displays its content instead of the method definition in RDoc.
I haven't been able to test this, so it may not fix the problem. 
Here's a link to the page: https://rubydoc.info/github/newrelic/newrelic-ruby-agent/NewRelic/Agent
See the heading "Recording custom metrics"

Move constant above RDoc

---

lib/new_relic/agent/vm/mri_vm.rb

We now support only versions above Ruby 2.1, so the conditions that used to point to Ruby 2.1 can just be true.

Remove Ruby 2.1 conditions

---

lib/new_relic/noticed_error.rb
test/new_relic/noticed_error_test.rb

Previously, we were incorrectly adding error_group to agent attributes in the case of an unfrozen attributes hash. We are now correctly doing this and added a corresponding test!

What if agent attributes isn't frozen

---

CHANGELOG.md
lib/new_relic/agent/tracer.rb
lib/new_relic/agent/transaction/abstract_segment.rb

Asynchronous segments may not be finished before the current transaction finishes. This can cause segments to have inaccurate timing information. In Ruby agent 9.0.0, a `NoMethodError` may be raised in these scenarios while a transaction finishes: 
```
[2023-03-06 15:13:18 +0100 web-01 (8675309)] ERROR : Exception during Transaction#finish
[2023-03-06 15:13:18 +0100 web-01 (8675309)] ERROR : NoMethodError: undefined method `name' for nil:NilClass
```
This exception is thrown while issuing a `warn`-level log stating a segment without a parent was unfinished when the transaction finished. This exception should not stop transactions from being harvested.
We've issued a fix that does two things: 
1. Make sure the `NoMethodError` is not raised by adding a safe navigation operator to the nil …

Add safe navigation to parent.name in warn message

---

test/multiverse/suites/sidekiq/sidekiq_with_redis_test.rb

The error showed up on the CI last night for only Ruby 3.1
```
SidekiqWithRedisTest#test_redis_client_pipelined_calls_work:
Bundler::InstallError: Bundler::DirectoryRemovalError: Could not delete previous installation of `/opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/redis-5.0.6`.
The underlying error was ArgumentError: parent directory is world writable, Bundler::FileUtils#remove_entry_secure does not work
```
This PR skips the test for Ruby 3.1
There's a separate issue to fix the error: #1894

Skip errored Sidekiq/Redis test for Ruby 3.1

---

.github/workflows/ci_cron.yml

test Rails EDGE with Ruby 2.7+ on nightly CI runs
issue 1775 seems to have been addressed in the Rails code itself or possibly in a dependent gem update

restore railsedge testing

---

lib/new_relic/agent/javascript_instrumentor.rb
test/new_relic/agent/javascript_instrumentor_test.rb

Add debug level logging statements to the JavaScriptInstrumentor's handling of custom attributes.

JavaScriptInstrumentor: log about custom attrs

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/memcache/dalli.rb
lib/new_relic/agent/instrumentation/memcache/prepend.rb
test/multiverse/suites/memcache/Envfile

For the Dalli (memcached client) instrumentation:
* Update the TODO comments to remind us of what needs doing for the next major release.
* Test fewer individual Dalli versions
addresses #1439

Dalli: update TODOs, test fewer versions

---

.github/workflows/release_notes.yml
.github/workflows/scripts/generate_release_notes.rb

Introduces automatic release note generation and pull requests to newrelic/docs-website.
- `generate_release_notes.rb` uses information in CHANGELOG to build release notes
- `release_notes.yml` runs methods from `generate_release_notes.rb` to generate the release notes and the branch name, and then uses that information to submit a PR to docs-website on pushes to the agent's `main` branch.
Closes #1866

Automate docs site pr

---

lib/new_relic/agent/configuration/default_source.rb

The instrumentation_value_of method was used to bridge our earlier disable_{instrumentation_name} configuration options with our instrumentation.* configuration options.
The deprecated config options were removed in 9.0. This cleans up the dead code.

Cleanup instrumentation_value_of

---

lib/new_relic/agent/instrumentation/bunny.rb
lib/new_relic/agent/instrumentation/bunny/chain.rb
lib/new_relic/agent/instrumentation/elasticsearch.rb
lib/new_relic/agent/instrumentation/elasticsearch/chain.rb
lib/new_relic/agent/instrumentation/fiber.rb
lib/new_relic/agent/instrumentation/fiber/chain.rb
lib/new_relic/agent/instrumentation/memcache.rb
lib/tasks/instrumentation_generator/templates/chain.tt
lib/tasks/instrumentation_generator/templates/dependency_detection.tt

`DependencyDetection#log_and_instrument` takes the second to last namespace and uses it in the
`Supportability/instrumention/#{supportability_name}/#{chain|prepend}` metrics
This was common in new instrumentation because the instrumentation generator templates didn't include `::Chain` (and the class I based the generator off of didn't have this either!)

Add ::Chain to end of instrumentation class names

---

.github/workflows/assignproj.yml
.github/workflows/ci.yml
.github/workflows/ci_cron.yml
.github/workflows/ci_jruby.yml
.github/workflows/label_community_cards.yml
.github/workflows/performance_tests.yml
.github/workflows/release.yml
.github/workflows/release_notes.yml
.github/workflows/repolinter.yml
.github/workflows/slack_notifications.yml
.github/workflows/snyk.yml

As part of security updates, all Actions versions now use a full-length SHA. 
Each one is using the latest stable version.
closes #1901

Update all GHA to use SHAs

---

newrelic.yml

The config option `transaction_tracer.explain.enabled` is incorrectly written. According to `default_source.rb`, it should be `transaction_tracer.explain_enabled`

Fix transaction_tracer.explain_enabled example

---

.github/workflows/assignproj.yml
.github/workflows/ci.yml
.github/workflows/release.yml

Actions that use `GITHUB_TOKEN` will be affected when GHA permissions are set to read-only (#1904) as a part of security updates. To allow these actions to continue working properly (write), we need to add `permissions` to the job. 
`GITHUB_TOKEN` exists in the following places: 
- `release.yml` - updated
- `ci.yml` - updated
- `assignproj.yml` - updated
- `ci_cron.yml` - NOT updated. The job that uses this is only reading the results of the last run.
Closes #1904

Add permissions to GITHUB_TOKEN

---

lib/new_relic/agent/error_collector.rb
test/new_relic/agent/error_collector_test.rb

`newrelic_rpm` 9.1.0 introduced an inconsistency in `NewRelic::Agent.notice_error` method that wasn't fixed in 9.2.0 either. 
Previously, when `false` was passed at `expected` key, e.g
```ruby
NewRelic::Agent.notice_error(error, expected: false)
```
an error was marked as unexpected in NewRelic. But fixes for Rubocop's `Style/DoubleNegation` done in https://github.com/newrelic/newrelic-ruby-agent/commit/589d9c12db300276939336bb61c8d2aae2cd2d31 (specifically [THIS LINE](https://github.com/newrelic/newrelic-ruby-agent/commit/589d9c12db300276939336bb61c8d2aae2cd2d31#diff-5d01d1fe7521ba113d127ae244e73bb33f3f71cb47e54e17aa79bf8d84b1fc75R280)) introduced an issue with doing so, it started checking for passed option like so:
```ruby
!options.delete(:expected).nil?
```
it obviously evaluates to …

Make explicitly unexpected errors unexpected again

---

.github/workflows/release.yml

Pin onetimepass to v1.0.1 and resolve a [security alert](https://github.com/newrelic/newrelic-ruby-agent/security/code-scanning/3).

Pin onetimepass

---

newrelic.yml

update the `newrelic.yml` ERB template in the root of the repo to align with the comments for `:'instrumentation.mongo'` and `:'instrumentation.excon'` that state that the only allowed values are `'enabled'` and `'disabled'` by using `'enabled'` instead of `'auto'` in the commented out config param lines.
resolves #1956

Mongo/Excon instrumentation: use 'enabled'

---

.github/workflows/assignproj.yml

This workflow requires another permission to add issues to repository projects.
Closes #1951

Add permission to write to repository project

---

CHANGELOG.md
lib/new_relic/agent/configuration/manager.rb
lib/new_relic/dependency_detection.rb
test/new_relic/agent/configuration/default_source_test.rb
test/new_relic/agent/configuration/manager_test.rb
test/new_relic/dependency_detection_test.rb

For `:'instrumentation.*'` configuration parameters that are set to :auto (the default), the agent will automatically determine whether to use method prepending or chaining. The agent will now update its in-memory configuration to give each relevant parameter a value of either :prepend or :chain so that the result of the determination can be introspected. This is intended to help 3rd party libraries that wish to further enhance the agent's instrumentation capabilities by prepending or chaining additional logic. Environment variable, YAML file, and server-side configuration based values are not impacted.
resolves #1924

auto convert :auto to :prepend/:chain in config

---

CHANGELOG.md
lib/new_relic/agent/tracer.rb
lib/new_relic/agent/transaction.rb
lib/new_relic/agent/transaction/tracing.rb
test/new_relic/agent/tracer_test.rb
test/new_relic/agent/transaction/tracing_test.rb

This fixes a bug where the agent would continue to record segments on transactions that were already finished in another thread. This would lead to increased memory usage over time because the agent would continue to copy over the finished transaction as the still current transaction in the thread instrumentation, causing the agent to think it was still supposed to continue recording data on the actually finished transaction. Now the agent will check the finished state of a transaction before using it when a new thread is spawned. 
Additionally, if a transaction reaches the segment limit but the transaction is actually already finished on some other thread, the state will now reset, preventing future segments from being created and a supportability metric will be recorded.
#1936

Bugfix Thread instrumentation continuing to use finished transactions on other threads

---

test/new_relic/agent/pipe_channel_manager_test.rb

I have no idea why simply adding a failure message to the assert makes it not fail anymore, but it does.
https://github.com/newrelic/newrelic-ruby-agent/actions/runs/4822722532
I couldn't get it to happen locally, seems to only happen on the CI.

Fix CI failures on 2.5.9 and rails 61

---

test/new_relic/agent/transaction_test.rb

This test is a fast follow to support the change for version 9.2.2
Relates to #1981

Add test for #finished? on txn without segments

---

test/multiverse/lib/multiverse/suite.rb

The active_record_pg test suite intermittently fails when running in parallel due to multiple processes attempting to access/manipulate the same database. Running this suite in serial prevents this from occurring.
Closes #1979

Run active_record_pg suite in serial

---

test/new_relic/agent/pipe_channel_manager_test.rb

The NewRelic::Agent::PipeChannelManagerTest has two cases failing on Ruby 2.5.9 and Rails 6.0/6.1:
#test_listener_merges_error_events, #test_listener_merges_error_traces
These tests started failing after PR#1969 was merged: https://github.com/newrelic/newrelic-ruby-agent/pull/1969
The tests are now skipped in the specific conditions where they intermittently fail
This was tested locally using Ruby 2.5.9 and rails52 (where they should not be skipped), rails60, and rails61.

Skip intermittently failing tests

---

test/new_relic/agent/configuration/orphan_configuration_test.rb

update the orphaned config regex with a negative lookbehind

orphaned config test: ignore security configs

---

.github/workflows/assignproj.yml

Move permissions to job level. We should be able to set this at the workflow level (as previously), but that doesn't seem to work here. Seeing if job-level will fix this.

Assign permission at job-level

---

lib/new_relic/control/security_interface.rb

SecurityInterface: Ruby <= 2.4 compatibility

---

.github/workflows/ci_cron.yml

We support these versions and they weren't being tested

Add rails40, -41, -50 versions to ci_cron matrix

---

test/new_relic/agent/instrumentation/rails/action_cable_subscriber.rb

This test started failing when we added the rails50 tests back to the CI. It seems to be an intermittent failure, as some ci_cron runs pass without it, and some fail for different reasons. 
If you choose to accept this PR, please merge it at your discretion.

Skip flakey Rails 5.0 test

---

test/multiverse/lib/multiverse/suite.rb
test/multiverse/suites/grape/Envfile

We need to require `rackup` when using `rack` >=v3. 
The Rackup v1.0.0 release was missing an important file, Rackup v2.0.0 was released the same day with [the fix](https://github.com/rack/rackup/commit/ce660d517ed82158108c905c28269f415190b2ef). We should only ever use Rackup >=v2.0.0

Use rackup >=2.0.0

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml
.github/workflows/scripts/setup_bundler
test/environments/rails40/Gemfile
test/environments/rails41/Gemfile

Rails40 and Rails41 failed the CI due to an installation error of the mysql2 gem. When moving to agent v9.0, some bundler configuration code was ripped out that looked like it was only needed for rubies 2.2. and 2.3, but was also being used for 2.4. This method has been added back. And older version of Rack was also needed to properly run.

CI fix: Rails40 and Rails41

---

lib/new_relic/agent/configuration/manager.rb
lib/new_relic/dependency_detection.rb
test/new_relic/agent/configuration/manager_test.rb
test/new_relic/agent/local_log_decorator_test.rb
test/new_relic/dependency_detection_test.rb

With [1930](https://github.com/newrelic/newrelic-ruby-agent/pull/1930/) the agent will now automatically convert any configured instrumentation value of `:auto` into either `:prepend` or `:chain` once the determination of which approach to take has been dynamically determined.
This will allow the agent's config to be inspected after the `:prepend` / `:chain` determination is made to see what `:auto` actually becomes under the hood.
But 1930 left an edge case gap open in the form of not allowing the configuration to convey instrumentation with unsatisfied dependencies. If a config value is set to `:prepend` or `:chain` in the configuration (overriding the default `:auto` value) and a dependency is unsatisfied (the library to instrument is not found on the system, it is of an unsupported …

instrumentation config: use :unsatisfied

---

test/multiverse/suites/sidekiq/sidekiq_with_redis_test.rb

Pinning redis version for a test that is bundling redis inline vs using Envfile. 
Previously, bundle inline was attempting to grab the latest version of redis to test with. This caused an error where bundler could not remove a previously installed version of the same redis version (used in Envfile), perhaps because different versions of bundler installed the same version of redis. Either way, using a different version of redis prevents this error.
Full CI run (since this is a ruby 3.1 error: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/5028830638
Closes #1894

Pin redis version

---

test/new_relic/agent/instrumentation/rails/active_record_subscriber.rb

- unit test focused follow-up to PR 2023
- always stub the "have we already subscribed?" check to ensure idempotency of the individual tests and to simply remove that non-configuration-parameter check from the equation
- add an inverse test to confirm the default (enabled) behavior

Improved AR notifications disabling tests

---

lib/new_relic/agent/configuration/yaml_source.rb
test/new_relic/agent/configuration/yaml_source_test.rb

Config aliases were previously supported only for environment params and they are now supported for YAML params as well.
If a param is missing from config and its alias is present, the alias will now be respected. If both are present, the original wins.

support aliases in YAML config

---

.github/workflows/ci_cron.yml

backport the testing of Ruby 3.3 to main without the inclusion of other tests that require additional commits to be brought over from dev

backport (only) Ruby 3.3 to main

---

test/new_relic/agent/instrumentation/rails/active_record_subscriber.rb

this was a holdover from before the issue with YAML aliases was identified and addressed

typo fix in AR subscriber test

---

test/multiverse/suites/active_record_pg/before_suite.rb

When switching between the default_env and test Rails environments, the Rails database tasks will raise
`ActiveRecord::EnvironmentMismatchError`.
Rails can either be explicitly told that the environment being switched to is expected via a task that sets the target environment, or the check itself can be disabled via an environment variable.
For now we are opting for the latter with
`ENV['DISABLE_DATABASE_ENVIRONMENT_CHECK']`.

CI: ignore Rails environment switches for db tasks

---

test/multiverse/suites/rack/Envfile

For now, don't test Ruby v3.3 with any supported version of Puma, as it it currently thought to be incompatible.
resolves #2040

Don't test Puma with Ruby 3.3

---

test/new_relic/control/security_interface_test.rb

when relying on the 3 argument version of `stub`, make sure it's available

security interface tests: skip MiniTest 4

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/log_event_aggregator.rb
newrelic.yml
test/helpers/config_scanning.rb
test/new_relic/agent/log_event_aggregator_test.rb

This creates a new configuration, `application_logging.forwarding.log_level`. This configuration defines the
minimum log level a log event should have to forward to New Relic.
Filtering is done in the `LogEventAggregator#record` method.
The default is "debug" which will forward all logs.
Setting the configuration to another built-in Ruby log level, such as "error", will forward only logs with the severity of error or above. This would mean logs with "error", "fatal" or "unknown" would be forwarded to New Relic.
This setting uses [Ruby's Logger::Severity constants integer values](https://github.com/ruby/ruby/blob/master/lib/logger/severity.rb#L6-L17) to determine precedence.
If an invalid log level is given to the configuration, the agent will default to forwarding all logs/having a …

Introduce log-level filtering

---

CHANGELOG.md
lib/new_relic/agent/method_tracer_helpers.rb
test/README.md
test/environments/rails70/app/controllers/application_controller.rb
test/environments/rails70/app/controllers/no_method_controller.rb
test/environments/rails70/app/controllers/test_controller.rb
test/new_relic/agent/method_tracer_helpers_test.rb

Rails controllers can be a special case because by default, controllers in Rails automatically render views with names that correspond to valid routes. This means that a controller method may not have a corresponding method in the controller class.
This PR adds a check to see if we have a valid method that isn't attached to a controller, and if so, can we figure out what controller it belongs to. 
The check makes an assumption of a simple rails app with all controllers living inside app/controllers, so if a customer's app breaks this pattern, the check fails, we don't report on method metrics, and we also don't get false warnings. If we can determine the controller, the method information is inserted at the top of the file.
Community issue #2048

Controller methods not in controller class don't warn

---

test/multiverse/suites/rails/Envfile

JRuby 9.4.0.0 was known to have GitHub Actions issues with our Rails 7 tests. Let's try things with JRuby 9.4.3.0

CI: resume JRuby testing with Rails 7

---

CHANGELOG.md
lib/new_relic/agent/logging.rb
test/new_relic/agent/logging_test.rb

In a previous refactor, the method `NewRelic::Agent::Logging::DecoratingFormatter#clear_tags!` was included in the private section. This is a no op method that exists for rails compatibility, and should be public. This PR moves it back to public and adds a test to prevent this from happening in the future
closes #2077

Fix for incorrectly private method in DecoratingFormatter

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/concurrent_ruby/chain.rb
lib/new_relic/agent/instrumentation/concurrent_ruby/instrumentation.rb
lib/new_relic/agent/instrumentation/concurrent_ruby/prepend.rb
lib/new_relic/agent/instrumentation/fiber/chain.rb
lib/new_relic/agent/instrumentation/fiber/instrumentation.rb
lib/new_relic/agent/instrumentation/fiber/prepend.rb
lib/new_relic/agent/instrumentation/thread/chain.rb
lib/new_relic/agent/instrumentation/thread/instrumentation.rb
lib/new_relic/agent/instrumentation/thread/prepend.rb
lib/new_relic/agent/tracer.rb
lib/new_relic/traced_thread.rb
test/multiverse/suites/thread/Envfile
test/multiverse/suites/thread/thread_fiber_instrumentation_test.rb

The issue was that we were capturing `*args` and passing them on for our Fiber instrumentation. Actually though, you can't actually pass arguments to `Fiber.new` the same way you can as with `Thread.new` (you would accomplish it like `fiber.resume(args)`). This wasn't causing any issues on it's own, however Async released a new version with [fiber-annotation](https://github.com/ioquatix/fiber-annotation), that defines the Fiber initialize method as accepting only **kwargs, and not *args. 
[`lib/fiber/annotation.rb`](https://github.com/ioquatix/fiber-annotation/blob/main/lib/fiber/annotation.rb#L13)
```
def initialize(annotation: nil, **options, &block)
@annotation = annotation
super(**options, &block)
end
```
In older Fiber versions, it seems there are no params you can pass to …

Fix for compatibility issue with Async 2.6.2

---

.github/workflows/release_notes.yml

This PR adds a new job to the `release_notes` action to delete a newly created branch upon job failure. Without this step, we couldn't re-run the action before manually deleting the branch.
A test run demonstrates a branch successfully created in the job `send-pull-request` that fails at the `make pull request step`. In the `Delete branch on fail job` we are successfully deleting the branch: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/5294926446
Here is the job not running if successful: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/5294997587
Resolves #1919

Delete release notes branch on action fail

---

.github/actions/issue_closer/README.md
.github/actions/issue_closer/action.yml
.github/actions/issue_closer/index.js
.github/actions/issue_closer/package.json
.github/workflows/pr_closed.yml

GitHub will permit a PR comment to resolve an issue, but only if the PR is merged to the default branch. This new workflow and action combo permit the magic comments to work when PRs are merged into a non-default branch.
resolves #1382

add 'PR Closed' workflow and 'issue_closer' action

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/log_event_aggregator.rb
test/new_relic/agent/configuration/default_source_test.rb
test/new_relic/agent/log_event_attributes_test.rb

Adds the ability to set custom log attributes using the configuration option `application_logging.forwarding.custom_attributes`. When submitted using `newrelic.yml`, the value must be a hash. When submitted using an environment variable, the format must be "key1=value1,key2=value2".
Attributes will be added to all log events. 
Relates to: #1141

Set custom log attributes using newrelic.yml or environment variables

---

test/multiverse/suites/rack/Envfile

Puma 5.6.6 was recently released, which will raise an error if the rack version being used is rack 3.
```
puma-5.6.6/lib/rack/version_restriction.rb:12:in `<top (required)>': Puma 5 is not compatible with Rack 3, please upgrade to Puma 6 or higher. (StandardError)
```
This was failing one of our multiverse suites, so now it is pinned to the correct version.

Pin rack version to <3 when using Puma 5

---

test/multiverse/README.md
test/multiverse/lib/multiverse/envfile.rb
test/multiverse/lib/multiverse/suite.rb
test/multiverse/suites/active_record_pg/Envfile

Satisfy the Multiverse CI testing TODO to permit individual suites to insist on running serialized.
For any suite that needs to be ran serialized (and we only have 1 currently), simply call `serialize!` somewhere within `Envfile`.
Updated the relevant `Envfile` documentation.
resolves #1154

CI: permit `serialize!` in Envfile

---

test/multiverse/README.md

- Specifying multiple suite names hasn't worked in awhile, and can't be made to without refactoring the args parser and risking bugs. The current maintainers don't use multiple comma separated groups at once, so we've decided to update the docs.
- The maintainers do, however, use multiple suites at once by leveraging groups. So go ahead and document how to use groups.

CI: update multiverse usage documentation

---

.build_ignore
CHANGELOG.md

Added changelog entry for https://github.com/newrelic/newrelic-ruby-agent/pull/2089 
Also, I added a couple more things to the list that we hadn't included in the original ticket.

Add changelog entry for community pr 2089

---

CHANGELOG.md
lib/new_relic/agent/method_tracer_helpers.rb
test/new_relic/agent/method_tracer_helpers_test.rb

The regex the agent was using didn't account for the possibility of active record adding attributes to inspect, which resulted in trying to call `Object.const_get` with a class name that was like `"Foo(id: integer, created_at: datetime, updated_at: datetime, name: string)"`, instead of just `"Foo"`. This would cause an error `NameError: wrong constant name` that prevent code level metrics from gathering the information and would log a warning.
Now, the regex will only grab word characters and :: for the name, preventing the `(....` from being included as the class name. 
A test was also added to confirm this works properly and prevent issues in the future. 
closes #2064

Bugfix for code level metrics on active record classes

---

test/multiverse/suites/config_file_loading/Envfile

Now that psych v5 has seen some minor version updates since its release in December 2023, start testing it with our config file loading Multiverse suite.
resolves #1676

CI: test config file loading with psych 5

---

.github/workflows/repolinter.yml

Repolinter recently failed: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/5359581716/jobs/9723356323?pr=2102 
Let's see if this fixes it.

Add issue write permissions to repolinter

---

.github/workflows/prerelease.yml

Accidentally used `#{{}}` instead of `${{}}` when making the title for the PR on the prerelease workflow

fix title for prerelease PR

---

lib/new_relic/rack/browser_monitoring.rb

Updates a link to defunct website
Q: Would it be possible to add some "link checker" build step? Or have such a manual task, every year?

Link to github, not rubyforge [ci skip]

---

test/multiverse/suites/infinite_tracing/Envfile

The grpc gem version reconciliation is having some issues. This change makes sure 1.49.1, the last version to officially support Ruby 2.5, will be installed for Rubies below 2.6.

Specify grpc version for infinite tracing multiverse

---

CHANGELOG.md
newrelic_rpm.gemspec

The test/agent_helper.rb file was overlooked in our switch to the new file inclusion process introduced in
https://github.com/newrelic/newrelic-ruby-agent/pull/2089
This file is required for the public API
`NewRelic::Agent.require_test_helper`.
The file has been added back to the build. Furthermore, `build.rb` was still included. This file used to be generated with Jenkins during our release process and has not been created with a release since version 6.13.0.
Resolves #2113

Include `test/agent_helper.rb` in build

---

.build_ignore
lib/new_relic/cli/command.rb
newrelic_rpm.gemspec

While working on #2113, I found a few other things to clean up in our gemspec.
* Update `homepage` to current repo path
* Add `.github/`, as a directory to build ignore
* Create TODO to remove `newrelic_cmd`, deprecated since version 2.13

Small gemspec fixes

---

lib/new_relic/agent.rb
lib/new_relic/agent/distributed_tracing.rb

The NewRelic::Agent module overview in RDoc was missing, showing the license information instead.
Also fixes capitalization within a param name.
More issues like this are likely hiding in our codebase.

Fix RDoc issues

---

newrelic_rpm.gemspec
test/new_relic/gemspec_files_test.rb

Fixes to get the .gemspec test to work with our automated CI system:
- effectively fork `Gem::Specification.load` to bypass its internal caching mechanism
- In so doing, the CI logs now report the actual underlying issue that caused a .gemspec eval to fail
- Assert that the parse succeeded before working with the result
- Update `newrelic_rpm.gemspec` to use an absolute path to the `.build_ignore` file
- `chdir` to the agent root for the evaluation of the .gemspec file

CI: gemspec files test - bypass cache

---

test/new_relic/gemspec_files_test.rb

This PR adds a test to ensure the `test/agent_helper.rb` file is included in the distributed gem.
Thank you, @ajesler for your creative solution! 🌈  
Resolves #2117

Create test for agent_helper in gem files

---

.github/workflows/ci_cron.yml
.rubocop.yml
lib/new_relic/agent/configuration/environment_source.rb
lib/new_relic/agent/instrumentation/memcache.rb
lib/new_relic/agent/instrumentation/queue_time.rb
lib/new_relic/agent/instrumentation/sequel.rb
lib/new_relic/agent/pipe_service.rb
test/helpers/misc.rb
test/new_relic/healthy_urls_test.rb

- Add a new unit test class for testing the health of all URLs defined in the code base. See the comments in `test/new_relic/healthy_urls_test.rb` for more details
- Update `ci_cron.yml` to set a `CI_CRON` env var to true
- Update `.ruboycop.yml` to permit `throw` and `catch` calls without parens
- Add new `skip_unless_ci_cron` helper to permit tests to only run via `ci_cron.yml`
- Add new `skip_unless_newest_ruby` helper to permit tests to only run on the newest Ruby
- Add new `agent_root` helper to permit tests to quickly get to the agent root
- Fix 5 URLs that the new test caught
resolves #2126

CI: Test for the health of all code base URLs

---

lib/new_relic/agent/instrumentation/memcache.rb
test/new_relic/healthy_urls_test.rb

Implement the [suggested improvement](https://github.com/newrelic/newrelic-ruby-agent/pull/2127#pullrequestreview-1525607554) for the URLs hash to have an empty files array for the hash value by default.
Update an old library website to use RubyGems.org instead.

CI: URL checker - simplify hash value vivification

---

lib/new_relic/noticed_error.rb
test/new_relic/noticed_error_test.rb

NoticedError: grab the transaction id at initialization time, not harvest time

NoticedError: glean the txn id upon init

---

lib/new_relic/agent/instrumentation/controller_instrumentation.rb
test/multiverse/suites/sinatra_agent_disabled/shim_test.rb

`new_relic_trace_controller_action` is defined and added to customer Sinatra applications, but is never called.

Remove old method

---

infinite_tracing/test/support/fixtures.rb
lib/new_relic/agent/instrumentation/action_controller_other_subscriber.rb
lib/new_relic/agent/tracer.rb
lib/new_relic/agent/transaction.rb
lib/tasks/bump_version.rake
lib/tasks/helpers/version_bump.rb
lib/tasks/newrelicyml.rake
newrelic_rpm.gemspec
test/new_relic/agent/tracer_test.rb
test/warning_test_helper.rb

- upgrade RuboCop to v1.54
- apply newly recommended linting changes

upgrade RuboCop to v1.54

---

test/multiverse/lib/multiverse/suite.rb
test/new_relic/fake_collector.rb
test/new_relic/fake_server.rb

- Update the fake server based classes used for unit tests to run on the latest version of WEBrick (previously we were not compatible with v1.8.0+ and locked to v1.7.0)
- Update the fake server class to respect `ENV['DEBUG']`. Going forward if there are any errors happening that are fake server related, we need only to set the `DEBUG` environment variable to see what is going on.
- Update the fake collector class to stop attempting to call `#rewind` on objects that don't support it (for improved WEBrick compatibility)

CI: multiverse - unpin webrick

---

lib/new_relic/control/class_methods.rb
test/new_relic/control/class_methods_test.rb

The LanguageSupport's `camelize` method appears to be faster, so let's just standardize on using that whenever we need to convert from snake to camel.
```shell
newrelic-ruby-agent 17:03:40 $ ruby test.rb
Rehearsal ---------------------------------------------------
LanguageSupport  20.492525   0.126348  20.618873 ( 20.645389)
Control          29.277619   0.177723  29.455342 ( 29.524243)
----------------------------------------- total: 50.074215sec
user     system      total        real
LanguageSupport  21.267743   0.145529  21.413272 ( 21.493573)
Control          30.793050   0.221045  31.014095 ( 31.085878)
```
resolves #2151

NewRelic::Control - drop competing `camelize`

---

test/multiverse/lib/multiverse/envfile.rb
test/multiverse/suites/active_record/Envfile
test/multiverse/suites/rack/Envfile

* test Ruby 3.3 with Puma (via the Rack suite) now that [puma/puma#3165](https://github.com/puma/puma/pull/3165) has been merged
* update `add_version` to respect _any_ prefix a human maintainer might want to specify for a version, and not just `=`
* update `add_version` to allow you do whatever Bundler lets you do. You can use `github`, `git`, `path`, etc.

enable Rack and Puma tests with Ruby 3.3

---

test/multiverse/suites/rack/Envfile

Stop testing Rack 2 with Ruby 3.3+ (we previously stopped testing Rack 1 with Ruby 3.2+)

CI: require Rack 3 for Ruby 3.3+

---

CHANGELOG.md
test/helpers/misc.rb
test/new_relic/agent/transaction/request_attributes_test.rb

Technically allow_all_headers doesn't require Rails v5.2+ but rather Rack v2+

CI allow_all_headers requires Rack v2+

---

lib/new_relic/agent/log_event_attributes.rb

Don't attempt to read `@custom_attribute_limit_reached` until it has been defined
Addresses the following Ruby warning:
```shell
/Users/jbond007/git/public/newrelic-ruby-agent/lib/new_relic/agent/log_event_attributes.rb:17: warning: instance variable @custom_attribute_limit_reached not initialized
```

LogEventAttributes: instance var check

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/roda/instrumentation.rb

Add full namespace path for method needed to name a Roda transaction …

Specify method namespace

---

test/multiverse/suites/mongo/mongo2_instrumentation_test.rb

One mongo test is failing in the CI, but I can't reproduce it locally when i run it using docker compose. I'm not sure what the issue with github actions is, but i'll look into it. For now though, lets just skip the test

skip failing mongo test in the CI

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/roda.rb
lib/new_relic/agent/instrumentation/roda/roda_transaction_namer.rb
test/multiverse/suites/roda/roda_instrumentation_test.rb

Add missing require statement to `instrumentation/roda`

Add require statement

---

docker-compose.yml

the mysql container won't run on the new m1 macs, and fails with the error
```
no matching manifest for linux/arm64/v8 in the manifest list entries
```
I found this fix for it, and now it's running on my new laptop.

Fix docker compose when running it on m1 mac

---

test/multiverse/suites/sidekiq/Envfile
test/multiverse/suites/sidekiq/sidekiq_test_helpers.rb

Our CI system has recently errored out when running the Sidekiq multiverse suite for 2 reasons:
- `json` gem dependency issues: The `json` version specified by `Gemfile.n` conflicts with the one already activated. Given the recent reworking of the Sidekiq suite, we should no longer need anything but Sidekiq and the agent.
- CLI instance issues. For some reason, we occasionally end up with a nil `config` object for `Sidekiq::CLI.instance`. Set a config if this happens. Also fix memoization in the test helper.

CI: Sidekiq multiverse - remove old dependencies

---

lib/new_relic/agent/instrumentation/sidekiq.rb
test/multiverse/suites/sidekiq/Envfile

- Update the deprecation warning text for Sidekiq v5
- Update the CI testing of Sidekiq v5 to stop testing it with Rubies newer than 2.5

Sidekiq: update deprecation warning, CI testing

---

lib/new_relic/agent/transaction/abstract_segment.rb
lib/new_relic/supportability_helper.rb
test/multiverse/suites/active_record_pg/before_suite.rb
test/multiverse/suites/active_record_pg/external_request_from_within_ar_block_test.rb
test/new_relic/agent/transaction/abstract_segment_test.rb

The `AbstractSegment` base segment class has been updated with a `set_segment_callback` method that accepts a proc and then invokes that proc every time a segment is initialized.
Each segment class can have its own callback.
With feature request [#1556](https://github.com/newrelic/newrelic-ruby-agent/issues/1556) in mind, a callback could be registered for the `ExternalRequestSegment` class to confirm that external request segments are never created within an ActiveRecord transaction.
See the newly added`test/multiverse/suites/active_record_pg/external_request_from_within_ar_block_test.rb` test file for a full demonstration of how this new callback support could potentially address [#1556](https://github.com/newrelic/newrelic-ruby-agent/issues/1556), even though none of the new code …

support user defined segment creation callbacks

---

lib/new_relic/agent/instrumentation/notifications_subscriber.rb

Adds a code comment for future readers. The agent uses a non-traditional way to subscribe to Rails events. Instead of passing a block to `ActiveSupport::Notifications.subscribe`, the agent defines a `#start` and `#finish` method, which Rails responds to. This is due to a threading issue discovered on initial instrumentation.
- [Original Issue](https://github.com/rails/rails/issues/12069 )
- [Rails Code](https://github.com/rails/rails/blob/ed5af004598fa7645fec2210453cca00f4b59168/activesupport/lib/active_support/notifications/fanout.rb#L320)

Describe Rails subscriber implementation

---

lib/new_relic/agent/configuration/default_source.rb
test/multiverse/suites/stripe/stripe_instrumentation_test.rb

While the Stripe include list is only concerned with user data hash keys, the exclude list looks at both the keys and their corresponding values in case there's anything sensitive or otherwise unwanted in the value.
- Added a new test to demonstrate hash value filtration
- Updated existing exclusion test which was yielding a false positive by not setting an include list (excludes won't work without an include list)
- Updated the exclude list config option description

Stripe: exclude list works on user data values

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/elasticsearch/instrumentation.rb
test/multiverse/suites/elasticsearch/elasticsearch_instrumentation_test.rb

Previously, the `port_path_or_id` value for Elasticsearch segments was set to the path given to the `request_with_tracing` method. This caused a metrics grouping issue for a customer because a new instance metric ("Datastore/instance/Elasticsearch/<host>/<port>") was created for every Elasticsearch document ID.
The source of the host value is a hash that also contains a port key. This commit updates the value of `port_path_or_id` to use the port from the `nr_hosts` hash.

Update Elasticsearch port_path_or_id value

---

.github/workflows/performance_tests.yml
.gitignore

* invoke the script with `bundle exec` to focus on the right `Gemfile`
* ignore perf test Rails app logs

CI: perf tests - bundler, git ignore logs

---

lib/new_relic/agent/instrumentation/net_http/instrumentation.rb
lib/new_relic/agent/transaction/abstract_segment.rb
test/multiverse/suites/net_http/net_http_core_instrumentation_test.rb
test/new_relic/agent/transaction/abstract_segment_test.rb

- Rescue segment callback invocations so that exceptions cannot prevent segment creation from succeeding
- For Net::HTTP instrumentation, cynically anticipate that a segment might be `nil` come finish time
resolves #2213

Rescued segment callbacks, nil net_http segments

---

test/performance/script/runner
test/performance/suites/agent_module.rb

- now that we wrap the perf tests in a Rails wrapper, the outer `ARGV` needs to be passed to the inner one
- fix straggler that wasn't previously converted to use an iteration count
resolves #2212

perf tests: fix arg passing

---

.github/workflows/ci_cron.yml
test/multiverse/lib/multiverse/envfile.rb
test/new_relic/gemspec_files_test.rb

Test with Ruby v3.3.0-preview2
resolves #2223

CI: Ruby 3.3.0-preview1 -> preview2

---

CHANGELOG.md
lib/new_relic/agent/system_info.rb
test/new_relic/agent/system_info_test.rb

Previously the agent was only capable of gleaning a Docker container id by leveraging a cgroups v1 approach. Now, it will first attempt to leverage a cgroups v2 approach and fall back to the v1 approach if that doesn't work. All other Docker related behavior such as that seen with containers that don't have cgroups functionality enabled is not impacted.
resolves #2026

Support cgroups v1 and v2 for Docker containers

---

test/multiverse/suites/rack/Envfile

Now that Puma v6.4.0 has been published to RubyGems.org, unpin Puma when the Rack suite is used in conjunction with Ruby v3.3.
NOTE that `nil` will fetch the latest release and satisfy the TODO.

CI: Resume testing Rack w/latest Puma

---

test/multiverse/suites/rack/Envfile

Now that Puma v6.4.0 is out, we can resume testing with "nil" (latest) on Ruby v3.3.0, but we need to prevent Ruby v3.3.0 and future rubies from ever testing Pumas older than v6.4.0.

CI: Ruby v3.3.0+ requires Puma v6.4.0+

---

test/new_relic/agent/instrumentation/rails/active_job_subscriber.rb

Enhance the ActiveJob notifications test suite by adding a test for the `retry_stopped.active_job` notification that Rails 6+ fires when it stops retrying to perform a job.
resolves #1764

CI: test retry_stopped.active_job

---

test/multiverse/suites/sidekiq/sidekiq_instrumentation_test.rb

The singleton instance of `Sidekiq::CLI` needs to have a Sidekiq configuration set on it for certain operations to work.
Previously we had been lucking out by having the `cli` test helper method be called prior to the `test_captures_sidekiq_internal_errors` test (which does not make use of the helper) being ran.
To prevent flapping, have the test make use of the `cli` helper (which preps a CLI instance with a config) to make it always pass regardless of the run order.
resolves #2227

CI: fix flapping Sidekiq test

---

CHANGELOG.md
newrelic_rpm.gemspec

To address the relevant Ruby 3.3 warning and prepare for Ruby 3.4, declare our dependency on the `base64` gem.
See #2237 for more details.
resolves #2237

Declare Base64 as a dependency

---

.rubocop.yml
lib/tasks/tests.rake

Permit one or more individual tests to be referenced by line number instead of by name, permitting one to do the following:
```
TEST=test/my_test.rb:5 bundle exec rake test
bert test/my_test.rb:5
```
resolves #2241

CI: permit tests to be specified by line number

---

lib/new_relic/agent/instrumentation/active_support_logger.rb
test/multiverse/suites/rails/active_support_logger_test.rb

The private method ActiveSupport::Logger.broadcast has been removed
in Rails 7.1. This throws an error in our tests. It also prevents the
@skip_instrumenting instance variable from being set on broadcast
loggers. This may cause users of Rails 7.1 to send duplicate
log events to New Relic.
This change stops ActiveSupport::Logger instrumentation from being
installed on Rails 7.1 or above. This is intended to be a temporary
measure until a solution can be found to stop sending duplicate logs
in Rails 7.1.

Skip Active Support Logger instrumentation for Rails 7.1

---

test/new_relic/agent/configuration/manager_test.rb
test/new_relic/agent/monitors/synthetics_monitor_test.rb
test/new_relic/agent/tracer_test.rb
test/new_relic/dependency_detection_test.rb

- This PR removes all the unused variable warnings during the execution of test suites. 
- Resolves #2247 

#2247, removes unused variable warnings in tests suite

---

lib/new_relic/agent/instrumentation/active_record_helper.rb
lib/new_relic/agent/instrumentation/mongodb_command_subscriber.rb
lib/new_relic/agent/instrumentation/roda/roda_transaction_namer.rb
lib/new_relic/agent/instrumentation/sinatra/transaction_namer.rb
lib/new_relic/agent/messaging.rb
lib/new_relic/agent/rules_engine.rb
lib/new_relic/agent/transaction/message_broker_segment.rb
lib/new_relic/agent/transaction/request_attributes.rb
lib/new_relic/agent/utilization/gcp.rb
lib/new_relic/constants.rb

- This PR adds the SLASH and ROOT constants and replaces them throughout the agent.
- I created the ROOT (`/`) constant because I felt that we are using it in the path's context in many places as well
- I thought it would be handy to separate it out into a new constant.
Resolves #2153

Add and Replace SLASH and ROOT constants

---

lib/new_relic/agent/instrumentation/sidekiq.rb

Fix deprecation warning: `DEPRECATION: Sidekiq exception handlers now take three arguments...`
> DEPRECATION: Sidekiq exception handlers now take three arguments, see #<Proc:0x00007f9015db7ef8 /home/me/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/sidekiq.rb:36>
NOTE: This warning is shown when using sidekiq main branch.
- https://github.com/sidekiq/sidekiq/pull/6051
- https://github.com/sidekiq/sidekiq/pull/6073
- https://github.com/bugsnag/bugsnag-ruby/pull/796
- ~~[ ] Include a security review link, if applicable~~
GitHub Actions when a pull …

Fix deprecation warning from sidekiq error handler

---

lib/new_relic/agent/instrumentation/ethon/instrumentation.rb
test/multiverse/suites/typhoeus/typhoeus_test.rb

For an instance of `Ethon::Easy`, consider a `#return_code` result not equal to `:ok` to be the indicator of an error instead of the `#response_code` being equal to `0`. With direct Ethon usage, these equality checks seem interchangeable but with Typhoeus the underyling easy object is left with a 0 for its response code on success.

Ethon: focus on return_code for errors

---

lib/new_relic/agent/instrumentation/rails_notifications/action_controller.rb
test/multiverse/suites/rails/action_controller_other_test.rb

A [PR to add ](https://github.com/rails/rails/pull/49297)`send_stream` notifications is sitting with the Rails team and has been labeled to go out in Rails 7.2. Rather than hold this PR, let's just skip the send_stream subscriber test until Rails 7.2. is released. 
Closes #1588

send_stream subscriber

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/http_clients/httpx_wrappers.rb
lib/new_relic/agent/instrumentation/httpx.rb
lib/new_relic/agent/instrumentation/httpx/chain.rb
lib/new_relic/agent/instrumentation/httpx/instrumentation.rb
lib/new_relic/agent/instrumentation/httpx/prepend.rb
test/multiverse/lib/multiverse/runner.rb
test/multiverse/suites/httpx/Envfile
test/multiverse/suites/httpx/config/newrelic.yml
test/multiverse/suites/httpx/httpx_instrumentation_test.rb

adds instrumentation for [HTTPX](https://honeyryderchuck.gitlab.io/httpx/)
resolves: n/a (Hacktoberfest contribution)

add instrumentation for HTTPX

---

test/multiverse/suites/grape/Envfile

Active Support 7.1 introduced a change to the deprecator that is incompatible with version 1.5.x of grape.
Since version 7.1 is compatible with Ruby 2.7 and 3.0, this will cause the tests to fail unless we specify a lower `activesupport` version to run on those Ruby versions.
Full scheduled CI run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/6593602933 
(The failing suite on that CI run is unrelated to this change)

Update grape Envfile to handle activesupport 7.1

---

Rakefile
infinite_tracing/Rakefile
infinite_tracing/newrelic-infinite_tracing.gemspec
newrelic_rpm.gemspec
test/environments/norails/Gemfile
test/environments/rails40/Gemfile
test/environments/rails41/Gemfile
test/environments/rails42/Gemfile
test/environments/rails50/Gemfile
test/environments/rails51/Gemfile
test/environments/rails52/Gemfile
test/environments/rails60/Gemfile
test/environments/rails61/Gemfile
test/environments/rails70/Gemfile
test/environments/railsedge/Gemfile
test/multiverse/lib/multiverse/suite.rb
test/multiverse/suites/active_record_pg/active_record_test.rb

I update all the configuration files by removing Pry from the default setup and add a conditional configuration.
To Enable Pry for debugging, follow these steps:
1. Open a terminal in your project directory.
2. Set the `ENABLE_PRY` environment variable by running the following command:
```bash
export ENABLE_PRY=1
```
This command enables Pry for the current session.
To Disable Pry for debugging, follow these steps:
Set the `ENABLE_PRY` environment variable by running the following command:
```bash
unset ENABLE_PRY
```
*Note:* Pry is included only when the …

Removed the direct inclusion of Pry and make it conditional based on the ENABLE_PRY environment variable

---

test/new_relic/healthy_urls_test.rb

teach the URL tester to ignore 2 new patterns
- Ignore Ethon wrappers class' dynamically interpolated URL
- Ignore the sometimes unreachable HTTPX homepage

URLs test: ignore 2 new false positives

---

CHANGELOG.md
lib/new_relic/agent/span_event_primitive.rb
test/new_relic/agent/span_event_primitive_test.rb
test/new_relic/agent/transaction/datastore_segment_test.rb
test/new_relic/agent/transaction/external_request_segment_test.rb

3 attributes have been added to datastore segments and 3 attributes have been added to external request segments for improved alignment with OTel specifications.
resolves #2190

add additional attributes for OTel compatibility

---

lib/new_relic/agent/system_info.rb
test/new_relic/agent/system_info_test.rb

update the Docker cgroups v2 container id regex to insist on a sha256 formatted id string

docker container id: ensure sha256 format

---

test/new_relic/agent/instrumentation/rails/active_record_subscriber.rb

- do not call `#source` on a proc, cheat with a source code parsing hack instead
- DRY up some shared logic

ActiveRecord subscriber tests: fixes, cleanup

---

lib/new_relic/agent/http_clients/abstract.rb
lib/new_relic/agent/http_clients/async_http_wrappers.rb
lib/new_relic/agent/http_clients/curb_wrappers.rb
lib/new_relic/agent/http_clients/ethon_wrappers.rb
lib/new_relic/agent/http_clients/excon_wrappers.rb
lib/new_relic/agent/http_clients/http_rb_wrappers.rb
lib/new_relic/agent/http_clients/httpclient_wrappers.rb
lib/new_relic/agent/http_clients/httpx_wrappers.rb
lib/new_relic/agent/http_clients/net_http_wrappers.rb
lib/new_relic/agent/http_clients/typhoeus_wrappers.rb

Cleans up some duplication of constants that are the same across the HTTP wrapper classes, and moves them to the abstract class.
I've modified the Curb wrapper to also extend from the abstract class as well, it was the only one I saw that didn't, and couldn't see anything that jumped out on why that would be. I can adjust if that was done for a reason.
Pull request is related to https://github.com/newrelic/newrelic-ruby-agent/issues/2279
I didn't see any existing unit tests or anything for these wrapper classes, and I couldn't see a good way to test/review these changes manually, so wanted to put the PR up incase y'all have something internal that's separate to run regression tests.

Cleanup of duplicated constants from individual HTTP wrapper classes to abstract class

---

CONTRIBUTING.md

Update `CONTIBUTING.md` to remove the reference to the Slack workspace

CONTRIBUTING.md - remove Slack workspace mention

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml
infinite_tracing/newrelic-infinite_tracing.gemspec
test/multiverse/suites/infinite_tracing/Envfile

Infinite Tracing depends on the `grpc` gem, which requires Ruby 2.5+.
Frequently, the gRPC Ruby gem maintainers inadvertently break compatibility with Ruby 2.5 and 2.6 by publishing a new version of `google-protobuf` (which `grpc` depends on) that itself requires Ruby 2.7+.
We do not wish to pin our `grpc` dependency to an exact version that is known to be compatible with Ruby 2.5 and Ruby 2.6 so that we leave users free to use whatever 1.x version of `grpc` that they wish, especially if they are themselves using `grpc` in their application.
Whether the gRPC maintainers' frequent breaking of Ruby 2.5 and 2.6 compatibility is accidental or deliberate, supporting these Rubies with our CI system has simply caused too many issues.
We are not actively introducing any new Ruby code to Infinite …

stop testing 8T with Ruby < 2.7

---

bin/newrelic
bin/newrelic_cmd
bin/newrelic_rpm
lib/new_relic/cli/command.rb
newrelic_rpm.gemspec
test/new_relic/healthy_urls_test.rb

This addresses the issue opened [here](https://github.com/newrelic/newrelic-ruby-agent/issues/2240) where there's currently a naming conflict with `newrelic-cli` and the Ruby agent if both are installed.
It will require the `newrelic` binstub to be removed in a future major release before the actual name collision issue is solved.
It also removes the older binstub for `newrelic_cmd` when a previous rename was done, as such this has the potential to be a breaking change for anyone not moved over to the new name.
I've left the version number just a `xxx` as I'm unsure what version this will be merged into. Happy to update it to whatever, or leave that to y'all when it gets merged!

Rename bin/newrelic -> bin/newrelic_rpm and remove older bin/newrelic_cmd references and binstub

---

CHANGELOG.md

A GitHub contributor's profile and PRs are no longer reachable

CHANGELOG: remove dead links

---

test/multiverse/suites/async_http/Envfile

when testing the latest stable async-http gem, require Ruby 2.7+
depending on the outcome of async-io#74, a new version of async-io may be released in future that restores Ruby 2.5 and 2.6 compatibility

latest async-http: require Ruby 2.7+ for now

---

test/multiverse/suites/async_http/Envfile

Add a line to pin specifically async-io due to the ruby version support issue
ci cron: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/6871235976

Pin async-io to < 1.37.0 on ruby < 2.7

---

lib/new_relic/agent/vm/mri_vm.rb

Now that this gem requires Ruby 2.4+, we no longer have to worry about `GC` not responding to `:stat` or the `GC.stat` hash having different key names for the same stat between different Ruby versions.

Simplify CRuby GC.stat info fetching

---

test/multiverse/suites/grpc/Envfile

for now, don't test gRPC with Ruby 3.3 to prevent CI issues
CI cron run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/6911039829

avoid compiling gRPC with Ruby 3.3

---

test/multiverse/suites/async_http/Envfile

async-io PR 75 fixed async-io Issue 74 and that gem can again be used with Ruby 2.5 and 2.6

re-enable testing async-http with Ruby 2.5 & 2.6

---

lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/configuration/manager.rb
lib/new_relic/agent/new_relic_service.rb
lib/new_relic/constants.rb
test/new_relic/agent/configuration/manager_test.rb
test/new_relic/agent/connect/request_builder_test.rb
test/new_relic/agent/new_relic_service_test.rb

By default the license key isn't logged given a) the default non-debug log level, and b) the default of not enabling the audit log.
While accuracy in those 2 non-default contexts can be useful in general, the inclusion of the license key does not provide much value and can serve to make log data more sensitive than it needs to be.
Filter out the license key from all contexts.

don't log the license key even in debug/audit

---

lib/new_relic/agent/attribute_filter.rb
lib/new_relic/agent/datastores/mongo/metric_translator.rb
lib/new_relic/agent/instrumentation/sinatra/ignorer.rb
lib/new_relic/agent/rules_engine/segment_terms_rule.rb

resolves #2343
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/README.md …

replaced asterisk string literal occurrences with constant

---

lib/new_relic/agent/configuration/default_source.rb

Don't bother relaying the JS blob for JS agent to either the log file or to the server on connect.

Exclude the js_agent_loader JS from logs/connect

---

.github/workflows/ci_cron.yml

Add Ruby 3.3.0-rc1 to our cron CI. 
Release notes: https://www.ruby-lang.org/en/news/2023/12/11/ruby-3-3-0-rc1-released/

Test Ruby 3.3.0-rc1

---

lib/new_relic/agent/distributed_tracing/distributed_trace_payload.rb
lib/new_relic/agent/javascript_instrumentor.rb
lib/new_relic/agent/new_relic_service/encoders.rb
lib/new_relic/agent/obfuscator.rb
lib/new_relic/agent/pipe_channel_manager.rb
lib/new_relic/agent/sql_sampler.rb
lib/new_relic/base64.rb
newrelic_rpm.gemspec
test/agent_helper.rb
test/multiverse/lib/multiverse/suite.rb
test/multiverse/suites/agent_only/cross_application_tracing_test.rb
test/multiverse/suites/rails/ignore_test.rb
test/multiverse/suites/rails/request_statistics_test.rb
test/new_relic/agent/commands/thread_profiler_session_test.rb
test/new_relic/agent/javascript_instrumentor_test.rb
test/new_relic/agent/monitors/cross_app_monitor_test.rb
test/new_relic/agent/new_relic_service_test.rb
test/new_relic/agent/obfuscator_test.rb
test/new_relic/fake_collector.rb

The used portions of the base64 gem are just wrappers around unpack/pack, dependency added in #2238 for ruby 3.3 compat.
RuboCop as an example has taken a similar approach by simply inlining this on their one callsite.
For most contributions …

Remove runtime dependency on base64

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/elasticsearch/instrumentation.rb

Test to see if using the root endpoint `/` to access the cluster name is more performant than `/_cluster/health` or `/_cluster/stats`.
Relates to #2360

Use root path to access Elasticsearch cluster name

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml

Use the official release of ruby version 3.3.0

bump ruby version from 3.3.0-rc1 to 3.3.0

---

.github/actions/simplecov-report/action.yml
.github/workflows/ci.yml

SimpleCov coverage has suddenly dropped (again). We [lowered](https://github.com/newrelic/newrelic-ruby-agent/pull/2308) the threshold in November 2023 and have an open ticket to [investigate](https://github.com/newrelic/newrelic-ruby-agent/issues/2309). This PR lowers the threshold once more so it's not a PR blocker.

Lower simplecov threshold

---

lib/new_relic/local_environment.rb

Cleaned up methods to replace single if statements with early returns.
Ran `bundle exec rake` and there were 0 failures and 0 errors 🌈  (just 5 skips, which I had when I ran the command before refactoring).
Resolves #2388
_I wasn't sure if the `check_for_thin` method (line 173 old, 175 new) could be refactored as it seemed that the `NewRelic::LanguageSupport.object_space_usable?` if-else returned `@discovered_dispatcher = :thin` either way. But I'm a beginner so I am sure the if-else is needed as is! Wanted to flag though, just in case._

Refactor local_environment methods

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/fiber/instrumentation.rb
lib/new_relic/agent/instrumentation/thread/instrumentation.rb
lib/new_relic/agent/tracer.rb
lib/new_relic/agent/transaction/tracing.rb
test/multiverse/suites/thread/thread_fiber_instrumentation_test.rb
test/new_relic/agent/tracer_test.rb

To reduce confusing information being reported, the agent no longer creates the new spans for `Ruby/Thread` and `Ruby/Fiber`. The agent will still record anything happening inside of these threads/fibers correctly. The parents will still also be created correctly. We did have to make some adjustment to segment parent logic to accommodate the removal of these spans while maintaining consistently correct parent nesting. 
I decided to leave the concurrent ruby spans as is, since those are more likely to be useful information for customers compared to the ruby/thread spans.
resolves https://github.com/newrelic/newrelic-ruby-agent/issues/2371

Remove Ruby/Thread and Ruby/Fiber spans

---

lib/new_relic/agent/instrumentation/async_http.rb

If the traces-backend-newrelic instrumentation is being used, then skip async-http instrumentation installation since this gem provides instrumentation. 
https://github.com/newrelic/traces-backend-newrelic

Skip Async-http instrumentation installation when Traces::Backend::NewRelic is defined

---

lib/new_relic/agent/instrumentation/grpc_server.rb

Previously, the name for GRPC::Client was being applied.

Use GRPC::Server instrumentation name

---

test/multiverse/suites/deferred_instrumentation/Envfile
test/multiverse/suites/padrino/Envfile
test/multiverse/suites/resque/Envfile
test/multiverse/suites/sinatra/Envfile

Sinatra 4.0 came out today, which is what caused the failures. Older sinatra versions had pinned its rack dependency, but now with this new version, rack 3 can be installed causing the rackup file failures.

Fix for failing CI

---

lib/tasks/instrumentation_generator/instrumentation.thor
lib/tasks/instrumentation_generator/templates/chain.tt
lib/tasks/instrumentation_generator/templates/chain_method.tt

Fixes the insert point for the default_source.rb, since it was no longer working after updates we made to default_source.rm
Also, I fixed the extra line that we've had in the chain instrumentation. I always remove it, and I know we've discussed how that line is redundant in other PRs that used the scaffold, so I updated it. (The method gets redefined immediately after that line.)

Update thor scaffold command

---

lib/new_relic/agent/instrumentation/view_component/instrumentation.rb

Fixes a bug introduced in https://github.com/newrelic/newrelic-ruby-agent/pull/2367, where the render_in behavior was changed, suppressing errors.
We should be able to se error pages, specially in when Rails.env is development. The piece of code that was removed here prevented from happening. Instead, it would have the `render_in` method return `nil` when an error happened, resulting in either a blank page, or an incomplete page.
I believe we also want to raise errors in production. We should not make a decision here, whether the error should be suppressed. …

Don't suppress view component rendering errors

---

CHANGELOG.md
test/multiverse/suites/view_component/view_component_instrumentation_test.rb

ViewComponent errors are being suppressed, as  #2410 reported. Once the fix from that PR is merged, our new test should pass.
Update: fix merged and new test passing!

Add ViewComponent regression test

---

lib/new_relic/agent.rb
lib/new_relic/agent/llm.rb
lib/new_relic/agent/llm/chat_completion.rb
lib/new_relic/agent/llm/chat_completion_message.rb
lib/new_relic/agent/llm/chat_completion_summary.rb
lib/new_relic/agent/llm/embedding.rb
lib/new_relic/agent/llm/feedback.rb
lib/new_relic/agent/llm/llm_event.rb
lib/new_relic/agent/llm/response_headers.rb
test/new_relic/agent/llm/chat_completion_message_test.rb
test/new_relic/agent/llm/chat_completion_summary_test.rb
test/new_relic/agent/llm/chat_completion_test.rb
test/new_relic/agent/llm/embedding_test.rb
test/new_relic/agent/llm/feedback_test.rb
test/new_relic/agent/llm/llm_event_test.rb
test/new_relic/agent/llm/response_headers_test.rb

All the LLM event classes are nested within the `NewRelic::Agent::Llm` module. See the notes in `NewRelic::Agent::Llm::LlmEvent` for use.
Closes #2408 
Supersedes #2414

Create LLM event structure (team refactor)

---

.github/workflows/ci.yml

This will stop previous runs if we've pushed up changes to our PR.
Documentation on concurrency in GHA: https://docs.github.com/en/actions/using-jobs/using-concurrency

Add concurrency to PR Continuous Integration

---

test/fixtures/cross_agent_tests/sql_obfuscation/sql_obfuscation.json
test/fixtures/cross_agent_tests/sql_parsing.json

SQL Obfuscation work in https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/529 revealed we may have a gap in testing for queries prepended by comments in the style of [Marginalia](https://github.com/basecamp/marginalia) (pre-Rails 7) and [Active Record Query Logs](https://api.rubyonrails.org/classes/ActiveRecord/QueryLogs.html) (Rails 7+). 
This PR adds tests for those cases. If we choose to merge this PR, we'll need to follow-up with an update to the cross-agent tests, since these fixtures are synced with that repository. If we don't want to go that route, I'll move these tests so they're separate from the cross-agent tests.
This type of test may have cross-agent value because Google's [sqlcommenter](https://google.github.io/sqlcommenter/) tool supports many different …

Update SQL obfuscation tests to include cases for Active Record Query Logs

---

test/new_relic/agent/transaction/segment_test.rb

This test has failed on Ruby versions ranging from 2.5 to 3.2 (perhaps more, but I didn't look too deeply into this). Skip the test until we can figure out why it's broken.
#2429 is an issue to fix this test when we can get around to it.

Skip flaky scoped metric reporting test

---

lib/new_relic/agent/configuration/default_source.rb

The previous wording for error_collector.max_backtrace_frames could be interpreted that the beginning and end would be removed and the middle would be preserved. This update clarifies the code's behavior.

Update description for max_backtrace_frames

---

test/multiverse/suites/mongo/Envfile

bson 5.0 was released 13 Feb 2024. It is not compatible with `Mongo::Connection.new` on mongo 1.3.1. For a reason I do not yet understand, without limiting bson to versions less than 5.0, the CI installs mongo 1.3.1 instead of the current 2.19.3 for this `nil` version test. This also occurs locally.
The mongo Envfile has a lot of wild stuff going on. #2447 exists to try to bring it into alignment with the majority of our other Envfiles.

Limit bson version for mongo latest test

---

lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/configuration/high_security_source.rb
lib/new_relic/agent/configuration/security_policy_source.rb
lib/new_relic/agent/instrumentation/ruby_openai.rb

Add new configuration `ai_monitoring.enabled`. This configuration will automatically be set to `false` if high-security mode is on and has been added to the Security Policy Source, which allows customers to customize high-security settings. 
closes #2439

Add `ai_monitoring.enabled` configuration

---

lib/new_relic/agent/error_collector.rb
lib/new_relic/agent/instrumentation/ruby_openai/instrumentation.rb
lib/new_relic/agent/llm/chat_completion_summary.rb
lib/new_relic/agent/llm/embedding.rb
lib/new_relic/agent/llm/llm_event.rb
test/new_relic/agent/error_collector_test.rb
test/new_relic/agent/llm/chat_completion_summary_test.rb
test/new_relic/agent/llm/embedding_test.rb
test/new_relic/agent/llm/llm_event_test.rb

When an error is raised by a segment that has an associated LLM event, the agent will add the following to the NoticedError's `attributes_from_notice_error` instance variable:
* `http.statusCode` => status code of the response with the error
* `error.code` => Value of `code` attribute returned from exception body
* `error.param` => Value of `param` attribute returned from exception body
* `completion_id` => `id`  of the related Llm::ChatCompletionSummary if the LlmEvent was of that type
* `embedding_id` => `id` of the related Llm::Embedding if the LlmEvent was of that type
This currently is formatted specifically for OpenAI responses, and may need to change when Bedrock is supported.
Closes #2405

OpenAI: Error tracing

---

lib/new_relic/agent/instrumentation/ruby_openai/instrumentation.rb
lib/new_relic/agent/llm/chat_completion_summary.rb
lib/new_relic/agent/llm/embedding.rb
lib/new_relic/agent/llm/llm_event.rb
test/new_relic/agent/llm/chat_completion_message_test.rb
test/new_relic/agent/llm/chat_completion_summary_test.rb
test/new_relic/agent/llm/embedding_test.rb
test/new_relic/agent/llm/llm_event_test.rb

The specification has changed since we initially created LLM events.
This PR updates the attributes to reflect the current spec.
Removes:
api_key_last_four_digits
transaction_id
Adds:
assertion for request.temperature
Closes #2459

Update LLM event attributes 

---

lib/new_relic/agent/instrumentation/concurrent_ruby.rb

Verify that `Concurrent::VERSION` is defined prior to attempting to use it.
Closes #2464

concurrent-ruby: verify a version string exists

---

CHANGELOG.md
lib/new_relic/rack/browser_monitoring.rb
test/new_relic/rack/browser_monitoring_test.rb

These changes introduce hardening to the logic that determines whether or not to inject the browser agent script tag.
In particular, the following 2 issues have been addressed:
1. If either `#traced_call` or `#should_instrument?` encounter any exceptions, these exceptions should be handled and logged without impacting the observed web application.
2. Allow a response headers hash to use symbols for values.
Closes #2462

browser monitoring injection logic hardening

---

test/multiverse/suites/ruby_openai/openai_helpers.rb
test/multiverse/suites/ruby_openai/ruby_openai_instrumentation_test.rb

Change embedding tests to use embedding object.

Embeddings tests

---

lib/new_relic/agent.rb
lib/new_relic/supportability_helper.rb
test/new_relic/agent_test.rb

The API accepts one argument, a proc, that should contain the callback the agent will invoke if it cannot glean the token count from instrumentation.
A supportability metric is recorded when the API is called.
Closes: #2451

Create `set_llm_token_count_callback` API

---

lib/new_relic/agent.rb
lib/new_relic/supportability_helper.rb
test/new_relic/agent/llm/feedback_test.rb

Add supportability metric for Feedback API

Add Feedback API supportability metric

---

lib/new_relic/agent/instrumentation/ruby_openai/instrumentation.rb
lib/new_relic/agent/llm/chat_completion_summary.rb
lib/new_relic/agent/llm/embedding.rb
test/new_relic/agent/llm/chat_completion_summary_test.rb
test/new_relic/agent/llm/embedding_test.rb

The following attributes are no longer in ChatCompletionSummary events:
* response_usage.total_tokens
* response_usage.prompt_tokens
* response_usage.completion_tokens
The following attributes are no longer in Embedding events:
* response_usage.total_tokens
* response_usage.prompt_tokens
Closes: #2449

Remove outdated token-related attributes

---

lib/new_relic/agent/instrumentation/ruby_openai/instrumentation.rb
lib/new_relic/agent/llm/llm_event.rb
test/multiverse/suites/ruby_openai/ruby_openai_instrumentation_test.rb
test/new_relic/agent/llm/llm_event_test.rb

Adds custom attributes to LLM events when prefixed with `llm.`. 
Closes #2437

Add support for `llm.` custom attributes

---

lib/new_relic/agent.rb
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/threading/agent_thread.rb
lib/new_relic/agent/tracer.rb
lib/new_relic/agent/transaction/tracing.rb
lib/new_relic/thread_local_storage.rb
newrelic.yml
test/multiverse/suites/rake/instrumentation_test.rb
test/new_relic/agent/tracer_test.rb
test/new_relic/thread_local_storage_test.rb

We were working on a certain sidekiq job that was generating a large (300+mb) CSV file, and to deal with the growing memory usage, we've implemented streaming. That implementation included using custom Ruby Enumerators.
When we launched it in production, we've noticed that NewRelic no longer traces database calls within the sidekiq job transaction. After some debugging, it turned out that the reason for that was that NewRelic holds its tracer state in the `Thread#[...]` storage. However, `Thread#[...]` is actually a fiber-local storage, and our implementation specifically used `Enumerator#next`, which spawns a new `Fiber`. As a result, NewRelic lost track of the current tracer state and attributed everything within that enumerator to CPU burn.
Support case where this issue originated is …

Thread-local storage for Tracer.state

---

lib/new_relic/agent/configuration/manager.rb

The use of JRuby revealed a synchronization issue of threads accessing/editing configuration. Adding a 'synchronize do' block to mediate this.

Synchronize config hash

---

lib/new_relic/agent/llm/response_headers.rb
test/new_relic/agent/llm/chat_completion_summary_test.rb
test/new_relic/agent/llm/embedding_test.rb
test/new_relic/agent/llm/response_headers_test.rb

LlmEmbedding and LlmChatCompletionSummary events generated by OpenAI have attributes pulled from response headers.
The following response headers should be captured if they're available:
* response.headers.ratelimitLimitTokensUsageBased
* response.headers.ratelimitResetTokensUsageBased
* response.headers.ratelimitRemainingTokensUsageBased
We haven't been able to craft a request that returns these headers.
In addition, this PR updates the data types of the response headers to match [the spec (internal)](https://source.datanerd.us/agents/agent-specs/blob/main/LLMs.md#response-headers).
Closes #2461

OpenAI: Update response headers

---

lib/new_relic/agent/custom_event_aggregator.rb
lib/new_relic/agent/llm.rb
test/new_relic/agent/custom_event_aggregator_test.rb

The `content` attribute on `LlmChatCompletionMessage` and the `input` attribute on `LlmEmbedding` events are exempt from truncation rules. They can be over 4096 bytes and entire the value must be sent to the collector.
Spec: https://source.datanerd.us/agents/agent-specs/pull/664 (internal)
closes #2448

Send full llm content

---

lib/new_relic/agent/instrumentation/ruby_openai/instrumentation.rb

While doing an audit on the response header datatypes, I thought I'd check the other event types. It looks like only `request.temperature` and `request.max_tokens` needed updates.
Since these values come from the user, we can't be certain of the data type.
In the spec, `request.temperature` can be a float or an integer. To simplify the logic, I'm always assigning it as a float because a float is more specific than an integer. `request.max_tokens` must be an integer.
The LLM event tests already use the correct datatypes.

Update ChatCompletionSummary attribute datatypes

---

lib/new_relic/agent.rb
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/ruby_openai/instrumentation.rb
lib/new_relic/agent/llm/llm_event.rb
lib/new_relic/agent/llm/response_headers.rb
test/multiverse/suites/ruby_openai/config/newrelic.yml
test/multiverse/suites/ruby_openai/ruby_openai_instrumentation_test.rb
test/new_relic/agent/custom_event_aggregator_test.rb
test/new_relic/agent/llm/chat_completion_summary_test.rb
test/new_relic/agent/llm/embedding_test.rb
test/new_relic/agent/llm/feedback_test.rb

Some finishing touches after walking through the spec:
- DT needs to be enabled in order to use the record_feedback API
- `ai_monitoring.enabled` should be `false` by default
- Small refactors for recording metrics
- We no longer need to drop the `llm.` prefix from custom attributes
- Because AI monitoring is diabled by default, we enabled it in `newrelic.yml` for testing

OpenAI: Final spec review/changes

---

lib/new_relic/agent/instrumentation/active_support_broadcast_logger/instrumentation.rb

hotfix: prevent exception in record_one_broadcast_with_new_relic

---

CHANGELOG.md

add changelog entry for community PR https://github.com/newrelic/newrelic-ruby-agent/pull/2510

Add changelog entry for community PR 2510

---

lib/new_relic/local_environment.rb

Reorders dispatches based on suggestion from [#2387](https://github.com/newrelic/newrelic-ruby-agent/issues/2387). We want to increase chances of early-exiting this loop that checks which dispatcher is at play by moving more popular/ prevlant dispatchers to the top of the list.
closes [#2387](https://github.com/newrelic/newrelic-ruby-agent/issues/2387)

Reorder dispatchers check

---

lib/new_relic/agent/transaction_error_primitive.rb
test/new_relic/agent/error_event_aggregator_test.rb
test/new_relic/agent/transaction_error_primitive_test.rb
test/new_relic/noticed_error_test.rb

- The transaction's guid should be present for both the ErrorTrace and TransactionError types
- Be sure (tests added, no lib code altered) that distributed tracing isn't required for the transaction guid to be populated

Errors Inbox transaction tracing updates

---

test/new_relic/net_http_test_cases.rb

use a variable in combination with a proc to confirm the stubbed method was indeed invoked as expected or not invoked as expected.
this gives us an assertion in the non-invoked path, which is nice.
i believe this fixes (switching from `-> {}` to `proc { |_h| }` an issue to where if the `raise` actually was attempted in the non-invoked path, it would fail.
removed unused variables / mocks

simplify tests for AI header setting / not setting

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/ruby_openai/instrumentation.rb
test/multiverse/suites/ruby_openai/ruby_openai_instrumentation_test.rb

Add tests to validate the desired attributed exist on chat completion, message, and embedding events. 
Through testing, it was discovered that the `request_temperature` on chat completion events was not being assigned. That has been fix and a CHANGELOG reflects this change.
closes #2440

Event attribute validation

---

.rubocop.yml
lib/new_relic/agent.rb
lib/new_relic/agent/new_relic_service.rb
lib/new_relic/agent/serverless_handler.rb
test/new_relic/agent/serverless_handler_test.rb

- Default to serverless output payload format v2, but support v1 via an env var being set
- Use custom formatting for `metric_data` and `error_data`
- Don't allow custom attributes with serverless
- misc serverless improvements

serverless updates, including support for v1 payload formats

---

test/multiverse/suites/curb/curb_test.rb
test/multiverse/suites/httpx/httpx_instrumentation_test.rb
test/multiverse/suites/rake/instrumentation_test.rb
test/multiverse/suites/stripe/stripe_instrumentation_test.rb
test/new_relic/helper_test.rb

Rake removed its requirement of OpenStruct in version 13.2.0. This caused our stripe multiverse suite to fail.
Since our tests were executed using Rake, we were able to use OpenStruct without a require in the file.
Now, OpenStruct is explicitly required in all the files it is used.
See: https://github.com/ruby/rake/pull/545 
Resolves #2548

Require OpenStruct where missing in tests

---

config/database.yml

remove the `config` dir from the project root and insist that all Rails based tests that would be looking for a `config` directory make use of the `config` subdirectories beneath `test/` instead.
resolves #2501

remove 'config' dir from project root

---

test/new_relic/agent/llm/feedback_test.rb
test/new_relic/agent/serverless_handler_test.rb

When I was running some tests locally for #2546, I noticed we had a few "unused variable" warnings. This PR fixes those warnings.
Closes #2554

Fix unused variable warnings in unit tests

---

infinite_tracing/lib/infinite_tracing/config.rb
infinite_tracing/test/infinite_tracing/config_test.rb
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/configuration/manager.rb
lib/new_relic/agent/log_event_aggregator.rb
test/new_relic/agent/configuration/default_source_test.rb
test/new_relic/agent/log_event_aggregator_test.rb

Configuration hashes defined by `default_source.rb` now support an
additional `:allowlist` key set equal to an array of valid values.
If an invalid value is specified for a parameter that has an allowlist,
a warning will be logged that contains the allowlist and the default
value for the parameter will be used.
resolves #2555

Configuration: support allowlists

---

CHANGELOG.md

serverless changelog entry

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml
.github/workflows/ci_jruby.yml
.github/workflows/config_docs.yml
.github/workflows/performance_tests.yml
.github/workflows/pr_closed.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/release_notes.yml
.github/workflows/release_pr.yml
.github/workflows/repolinter.yml
.github/workflows/slack_notifications.yml
.github/workflows/snyk.yml

Update to use v4 of the GitHub Action "checkout"
resolves #2565

GHA checkout@v3 -> checkout@v4

---

test/new_relic/agent/instrumentation/rails/action_dispatch_subscriber.rb
test/new_relic/agent/instrumentation/rails/active_support_subscriber.rb

I saw a few unused args warning when I was running some of the Rails unit tests. This PR fixes them.

Resolve unused argument warnings in test

---

test/new_relic/rack/browser_monitoring_test.rb

- check for the exact ActionDispatch constant, not Rails
- escape the random characters ('+', etc.) that may interfere with regex matching
- use ///m for regex

improve nonce unit test

---

test/environments/rails61/Gemfile

Have the `rails61` environment stick to `sqlite3` v1

CI: require sqlite3 < 2 for Rails v6.1

---

test/environments/rails60/Gemfile

Seemingly both Rails v6.0 and v6.1 cause issues with the new `sqlite3` v2.

require sqlite3 < v2 for Rails 6.0

---

test/new_relic/agent/span_event_aggregator_test.rb

ramp up span event aggregator test numbers

---

test/multiverse/suites/async_http/Envfile

The `async_http` gem changed it's Ruby version requirement from v0+ to v3+ starting with v0.61. Stop testing the latest version with anything less than Ruby 3.

async_http: newer versions require Ruby 3+

---

test/multiverse/suites/async_http/Envfile

While async-http v0.60 is itself ok with Ruby 2, it's dependency on a newer async version is not.

async-http: Use v0.59 for Ruby 2

---

test/multiverse/suites/async_http/Envfile

the recently published async-pool v0.5 doesn't declare a Ruby v3.x requirement, but seems to need it

avoid async-pool v0.5 for Ruby v2.x

---

.github/workflows/scripts/setup_bundler

Where we use `=~`, can lead to unintended matches. This PR adds some additional lockdown. Previously, `=~ 2.4` could match `3.2.4`. We're now being more specific (ex: `=~ ^2\.4`) with how we are matching.

Tighten regex logic

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb

Add `Rails::Command::RunnerCommand` for `bin/rails runner` commands and `Rails::Command::RakeCommand` for `bin/rails db` command to the list of denylisted constants that will prevent the agent from autostarting when seen.
Now when `bin/rails runner` and `bin/rails db` commands are ran, the agent will recognize those contexts and not start
automatically.
Older agent versions that are still supported by New Relic can update to the new list of denylisted constants by having the following line added to the `newrelic.yml` configuration file:
```yaml
autostart.denylisted_constants: "Rails::Command::ConsoleCommand,Rails::Command::CredentialsCommand,Rails::Command::Db::System::ChangeCommand,Rails::Command::DbConsoleCommand,Rails::Command::DestroyCommand,Rails::Command::DevCommand,Rails::Command::E …
```

Don't start for 'rails runner' and 'rails db'

---

Rakefile

The Rake 'console' target should not require Pry and instead fall back to `binding.irb` when Pry is unavailable
resolves #2634

bugfix: Rake 'console' shouldn't require Pry

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb

It's been a wild Friday! 🦁 
This PR reverts the changelog updates made this morning and updates the documentation default to reflect the dynamic default value.

Rails CSP nonce changelog reversion and documentation default update

---

test/multiverse/suites/ethon/Envfile
test/multiverse/suites/httprb/Envfile
test/multiverse/suites/typhoeus/Envfile

ffi version 1.17.0 requires a version of Ruby gems that is incompatible with Ruby 2.5 and Ruby 2.6. This caused bundling to fail for our ethon, typheous, and HTTP.rb suites.
Link to example failure: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/9353651649/job/25744692956#step:12:5133

Limit ffi version for Rubies below 2.7

---

.github/workflows/ci_cron.yml
lib/new_relic/agent/instrumentation/elasticsearch/instrumentation.rb
lib/sequel/extensions/new_relic_instrumentation.rb
test/agent_helper.rb
test/environments/norails/Gemfile
test/environments/rails61/Gemfile
test/environments/rails70/Gemfile
test/multiverse/lib/multiverse/envfile.rb
test/multiverse/suites/elasticsearch/elasticsearch_instrumentation_test.rb
test/multiverse/suites/rails/Envfile
test/multiverse/suites/rails_prepend/Envfile
test/new_relic/agent/agent_logger_test.rb

- Introduce nightly testing against Ruby v3.4.0-preview1
- Update elasticsearch instrumentation to be Ruby 3.4+ compatible
- Update various test environment `Gemfile` files to include gems that were previously included with Ruby as part of the default installation but are no longer included with Ruby 3.4 or 3.5.
resolves #2636 
resolves #2665 
resolves #2670
resolves #2672

CI: test with Ruby v3.4.0-preview1

---

CHANGELOG.md
lib/boot/strap.rb
test/new_relic/boot/strap_test.rb

- Do not put any Ruby files in the root of `lib/` that do not match the
gem name, or Ruby lib path based issues can arise with other gems.
In this case, move `lib/bootstrap.rb` to `lib/boot/strap.rb` to avoid
colliding with `require 'bootstrap'` calls intended to be received by
the `bootstrap` gem.
- For bootstrapping, do not ever perform `exit`. Instead, simply use
`raise/rescue` for control flow. As a result, any future unintended
loading of the bootstrapping will simply `warn` and return instead of
causing the Ruby runtime to exit.
resolves #2675

lib/bootstrap.rb -> lib/boot/strap.rb

---

lib/tasks/instrumentation_generator/instrumentation.thor
lib/tasks/instrumentation_generator/templates/dependency_detection.tt
lib/tasks/instrumentation_generator/templates/newrelic.yml.tt

Our generator task hasn't been very compatible with gems that have hyphens in their names. This takes care of a few glitches I ran into while generating content for redis-clustering.
It also stops adding to the newrelic.yml file, since we have automation to update that file now. However, I stopped short of removing that code entirely.

Update instrumentation generator

---

.github/workflows/ci.yml

Branch coverage is wonky and not counting things correctly. We plan to look into it further in the future, but for now lets just not have branch coverage block PRs. I first tried removing the branch coverage but that didnt' seem to do anything somehow, so instead I lowered the value.

Remove branch coverage check from PRs

---

CHANGELOG.md
lib/new_relic/agent/aws.rb
lib/new_relic/agent/instrumentation/dynamodb/instrumentation.rb
test/multiverse/suites/dynamodb/dynamodb_instrumentation_test.rb
test/new_relic/agent/aws_test.rb

Not all aws credentials are credentials, but they do all seem to include credentials, so I've updated it to do credentials.credentials instead, which should work. I also added more safety/checks so that it won't cause an error and will just simply not try to make an arn if it doesn't have access to the necessary info.

Bugfix: Dynamodb instrumentation access_key_id error on some credential classes

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb

The inclusion of `Rails::Command::RakeCommand` prevented the agent from starting for background jobs in an application with ActiveJob and Solid Queue. Solid Queue uses a rake task to start, which can be invoked from Rails binstubs that leverage `Rails::Command::RakeCommand`. 
We encourage users who do not want the agent to run with `rails db:*`, or other rake tasks defined in Rails to include the constant in their `autostart.denylisted_constants` configuration. We are continuing to investigate options to be more specific about excluding rake tasks in modern versions of Rails.
Relates to #2677
Relates to #2691

Remove `Rails::Command::RakeCommand` from `autostart.denylisted_constants` default

---

.github/versions.yml
.github/workflows/ci.yml
.github/workflows/ci_cron.yml
.github/workflows/ci_jruby.yml
.github/workflows/config_docs.yml
.github/workflows/performance_tests.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/release_notes.yml
.github/workflows/release_pr.yml
.github/workflows/slack_notifications.yml
lib/tasks/gha.rake

to simplify 3rd party GitHub Actions versions specified across our various workflow files, put the versions in a `versions.yml` file and define a new `gha:update_versions` rake task to automatically reconcile the workflows with the versions specified
resolves #2702

add gha:update_versions Rake task

---

test/multiverse/suites/grape/Envfile
test/multiverse/suites/grape/grape_test.rb

Grape v1.x versions unhappy with the new Rack version. Let's lock down Rack when testing those versions.

CI: Lock down Rack for old Grape v1.x versions

---

test/multiverse/suites/rack/builder_map_test.rb
test/multiverse/suites/rack/url_map_test.rb

- assume all Rack testing will now involve a Rack at or above v1.4
- stop checking for `Rack::VERSION`, as modern Rack uses `Rack.release`
- remove 2 tests specific to Rack v1.

CI: stop checking for / testing against Rack v1

---

newrelic_rpm.gemspec

For Ruby v3.4/3.5 compatibility, declare `mutex_m` and `ostruct` as dev dependencies

mutex_m and ostruct as dev dependencies

---

CHANGELOG.md
lib/new_relic/agent/error_collector.rb
test/new_relic/agent/error_collector_test.rb

previously, errors that were noticed and treated as expected because the HTTP status code matched the list configured via
`:'error_collector.expected_status_codes'` would not actually end up with their `expected` attribute set to a `true` value.
the relevant agent error processing behavior has been updated so that `expected: true` should always be applied to all errors that are treated as expected by the agent.
resolves #2708

set `expected: true` for matching status codes

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/stripe_subscriber.rb
test/multiverse/suites/stripe/stripe_instrumentation_test.rb

When naming Stripe metrics, include only the first two (API version and category) portions of the path and not the id. Continue to start the metric name with "Stripe" and end it with the method (ex: "get"). This will prevent metric name exhaustion resulting from regular Stripe usage.
Given a 'get' request performed against a path of
'/v1/payment_methods/pm_8675309', the metric name will now be 'Stripe/v1/payment_methods/get'.
resolves #2654
resolves #2709

Stripe: do not include path ids in metric names

---

test/multiverse/suites/grape/Envfile

For Grape...
- Simplify the logic to pin Grape v1 to use Rack v3.0 while accommodating `nil` versions (signifying "latest") and looking at the Ruby version in play
- Require (as Grape itself does) Ruby v2.6+ for using the latest Grape

CI: Grape Envfile tweaks

---

.github/versions.yml
.github/workflows/ci.yml
.github/workflows/ci_cron.yml
.github/workflows/ci_jruby.yml

Update nick-fields/retry to v3.0.0 to use Node v20 and eliminate related Node v16 deprecation warnings
resolves #2584

CI: update GHA nick-fields/retry to v3.0.0

---

test/multiverse/suites/grape/Envfile
test/multiverse/suites/grape/grape_test_api.rb

- Enforce Ruby v2.7+ for the latest version of Grape, which has dropped support for Ruby v2.6 in Grape v2.1.0.
- Add a version entry for Grape v2.0.0.
- Conditionally use `error!` instead of `error_response` for Grape v2.1+
resolves #2723

CI: Grape v2.1.0 related updates

---

lib/new_relic/agent/configuration/default_source.rb
lib/tasks/helpers/format.rb
lib/tasks/instrumentation_generator/instrumentation.thor

* Make heredocs adhere to 120 character line length by adding newlines and indenting them
* Remove some extra characters, add spaces, etc.
* Set documentation defaults for instrumentation.* configs for consistent display in HTML
Deployment example: https://deploy-preview-17695--docs-website-netlify.netlify.app/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration/

Update config description formatting in default_source.rb

---

lib/tasks/helpers/newrelicyml.rb

When updating `newrelic.yml` via `rake newrelic:update_newrelicyml`, take into account the fact that the description text is indented one level (2 spaces) and therefore needs to be truncated at 78 columns instead of 80.

yaml formatting: accommodate for indentation

---

lib/new_relic/agent/local_log_decorator.rb
test/new_relic/agent/local_log_decorator_test.rb

if the log decorator is given a hash, merge the metadata into the hash

log decorator: support hashes

---

lib/tasks/helpers/config.html.erb
lib/tasks/helpers/format.rb

The docs team is replacing `<DoNotTranslate>` with `<DNT>`. We need to update this file to ensure we remain compatiable with docs parsing.

Replace `<DoNotTranslate>` with `<DNT>`

---

test/multiverse/suites/httpx/httpx_instrumentation_test.rb

When HTTPX 1.3.0 released, it caused one of our tests to fail, due to a change in the way the `HTTPX::ErrorResponse` class needs to be created. Previously you would pass in a hash that would be converted to an options object. Now, instead you do not pass in anything for options, and instead it uses the options present on the request object.

Fix for HTTPX 1.3.0 test failure

---

lib/new_relic/agent/instrumentation/bunny/instrumentation.rb
test/multiverse/suites/bunny/bunny_test.rb

Adds new attributes to consume and produce spans created in our bunny instrumentation.

Add new span attributes for bunny instrumentation

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml
test/environments/rails72/Gemfile
test/environments/rails72/Rakefile
test/environments/rails72/app/controllers/application_controller.rb
test/environments/rails72/app/controllers/no_method_controller.rb
test/environments/rails72/config/application.rb
test/environments/rails72/config/boot.rb
test/environments/rails72/config/database.yml
test/environments/rails72/config/environment.rb
test/environments/rails72/config/initializers/test.rb
test/environments/rails72/db/schema.rb
test/new_relic/agent/instrumentation/rails/active_job_subscriber.rb

Start CI testing against Rails v7.2 (in beta currently), which requires Ruby v3.1+

Introduce Rails v7.2 test environment

---

infinite_tracing/CHANGELOG.md
infinite_tracing/newrelic-infinite_tracing.gemspec

Grpc gem released a new version that no longer pins the google-protobuf version to 3.25. This resulted in a lot of test failures in infinite tracing. To resolve this issue, we've added a pinned dependency to infinite tracing gemspec to keep google-protobuf < 4.

Pin protobuf version to < 4 for infinite tracing

---

lib/new_relic/agent/configuration/default_source.rb

the Lambda docs have been reorganized to accommodate what are being referred to as "layerless", "containerized", and "non-containerized" approaches, with that last one being the closest analogue to what was linked to previously.

update Lambda docs link

---

lib/new_relic/agent/instrumentation/rails_notifications/action_controller.rb
test/multiverse/suites/rails/action_controller_other_test.rb

When subscribing to Action Controller topics for Rails notifications, include 4 new topics in the subscription regex:
- `exist_fragment?`
- `expire_fragment`
- `read_fragment`
- `write_fragment`

include additional AC topics in Rails subscription

---

CHANGELOG.md

PR 2745 (4 additional Action Controller notifications) changelog entry

CHANGELOG: entry for PR 2745

---

.github/workflows/ci_special.yml
test/helpers/misc.rb
test/new_relic/healthy_urls_test.rb

Due to random URL test issues that happen, let's move it out into it's own run that will notify us when it's messed up, instead of running with the regular CI tests. This will help us know at a quick glance that the failure is URL related, and also won't cause failures when running the ci cron for unrelated reason.

Run url test only on its own

---

lib/new_relic/agent/configuration/default_source.rb
newrelic.yml

Previously, config descriptions were edited to adhere to a 120 character line length.
This caused problems for some descriptions when the newrelic.yml file was generated.
The newrelic.yml task handles its own line lengths. We should revisit this another time.
Relates to changes made in https://github.com/newrelic/newrelic-ruby-agent/pull/2770/

Revert spacing changes

---

newrelic.yml

Put the special description above the security configs back into newrelic.yml

Add security agent content back to newrelic.yml

---

lib/tasks/helpers/newrelicyml.rb
newrelic.yml
test/new_relic/newrelicyml_test.rb

Update `newrelic.yml` generator to include Security agent comments and regroup security configs at the bottom of the file.
Test coverage: 100%

Add Security Agent comments to `newrelic.yml`

---

lib/new_relic/agent/configuration/default_source.rb

Docs Eng recently updated the mdx to html serializer for sending content to be translated. These spaces are needed to keep them happy. See: https://github.com/newrelic/docs-website/pull/18153/files#diff-9c4509bca32c1d4f10736558876f41a21c9b2e0032ffe68cbc9311d4bdcb0f30L1421

Update spacing for configs to aid translation tool

---

test/new_relic/healthy_urls_test.rb

This URL gets a 403 when visited from Net::HTTP. However, it works fine in the browser. Let's just ignore it.
Passing CI run on this branch: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/10205857835

Exclude learn.newrelic.com from HealthyUrlsTest

---

lib/new_relic/agent/agent_helpers/connect.rb
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/control/frameworks/grape.rb
lib/new_relic/control/frameworks/padrino.rb

- Grape and Padrino framework detection for environment report. 
This information is required for newrelic_security to show on UI whether application is supported or not.

Grape padrino framework detection

---

test/multiverse/suites/grape/grape_test.rb
test/multiverse/suites/padrino/padrino_test.rb
test/multiverse/suites/roda/roda_instrumentation_test.rb

Tests added for Grape, Padrino and Roda. Rails and Sinatra framework detection is already evaluated in the unit tests.
(Tests will fail until #2789 is merged)

Add tests to verify framework detection

---

CHANGELOG.md
lib/new_relic/local_environment.rb
test/new_relic/local_environment_test.rb

The `Falcon::Server` class is loaded into the object space after the environment report is sent by the agent. However, evaluating `File.basename($0)` returns 'falcon' in time.
This was our initial approach: https://github.com/newrelic/newrelic-ruby-agent/commit/ebc74b53c76dffa1b3d1ce3520807dde27c3c667 
Closes #2778

Revert falcon detection changes

---

CHANGELOG.md
lib/new_relic/agent/configuration/manager.rb
test/new_relic/agent/configuration/manager_test.rb

The configuration manager's alteration of its internal cache hash to preserve previously dynamically defined values has been known to cause problems with JRuby given its concurrent access to the hash object. We have used `synchronize` and `Hash#dup` fixes previously, but still have reports of issues.
When it comes down to it, the alteration of the hash was only added and still only needed for use by the security agent. So let's just not even attempt to alter the hash if JRuby is in play but the security agent is not.

JRuby fix for concurrency issue with manager cache

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/redis.rb
test/multiverse/lib/multiverse/gem_manifest.rb
test/multiverse/suites/redis/Envfile
test/multiverse/suites/redis/redis_instrumentation_test.rb

- Bugfix for https://github.com/newrelic/newrelic-ruby-agent/issues/2814
- Added relevant regression test (with logic taking place in `Gemfile` before the instrumentation is loaded)
resolves #2814

Bugfix: don't use `return` in Redis detection

---

.github/workflows/ci_cron.yml
test/environments/railsedge/Gemfile

activerecord now needs sqlite3 v2+

CI: use sqlite3 v2 for Rails EDGE

---

lib/new_relic/agent/instrumentation/active_merchant.rb
lib/new_relic/agent/instrumentation/delayed_job_instrumentation.rb
lib/new_relic/agent/instrumentation/excon.rb
lib/new_relic/agent/instrumentation/sidekiq.rb
lib/new_relic/agent/instrumentation/sinatra.rb

The versions mentioned in the deprecation messages have already been removed from our testing matrix.

Remove deprecation messages for completed actions

---

.rubocop.yml
lib/new_relic/agent/serverless_handler.rb
test/new_relic/agent/serverless_handler_test.rb

To address issues with the recent serverless enhancements discovered through local dev testing with the Node.js tool 'serverless':
- Don't append a port value to a URI string that already contains one
- If the URI string construction or parsing fails for any reason, log an error and return `nil` so that further processing of the function invocation is not impacted
These issues are thought to only be reproducible outside of AWS, but it's good to be proactive with a bit of extra caution.

ServerlessHandler: error handling for URI parsing

---

lib/new_relic/agent/database/obfuscation_helpers.rb

- for uuids and Oracle quoted strings, don't regex-escape characters unnecessarily
- for multi-line comment, borrow from OTel Ruby contrib, but discard the non-capturing parens from the pattern, as nothing is ORed.
- update the hash to Ruby v1.9+ syntax
- freeze the hash

update SQL obfuscation regexes

---

test/helpers/misc.rb
test/new_relic/healthy_urls_test.rb

- Update the `skip_unless_special_ci` helper to only perform the skip when in a CI context; allowing things to run in a local dev context
- Don't bother performing the "ignore" regex check against a URL that has already previously been tested
- In addition to ignoring 'http://#', ignore 'https://#' as well

CI: Healthy URL checker tweaks

---

lib/new_relic/agent/instrumentation/dynamodb/instrumentation.rb
test/multiverse/suites/dynamodb/dynamodb_instrumentation_test.rb

Since it's currently undecided how we want to handle getting the account id for the ARN, we are going to comment out this code and come back to it when we decide whether we are going to do things differently or continue doing this.

Comment out Dynamodb ARN attribute

---

test/multiverse/suites/sidekiq/sidekiq_instrumentation_test.rb

As discussed in #2195, add unit test coverage to demonstrate the agent's ability to instrument Sidekiq jobs when `perform_inline` is used.

Add unit test coverage for Sidekiq job `perform_inline`

---

lib/new_relic/agent/instrumentation/rdkafka.rb

Make sure that the `Rdkafka` class based instrumentation is not attempted on systems without it present by relocating the `require_relative` statements into the conditionally executed block.

Kafka instrumentation: code loading logic fix

---

CHANGELOG.md
lib/new_relic/agent/configuration/manager.rb

A previous change made to resolve a JRuby concurrency error inadvertently caused a new bug in the agent handling the configuration values when resetting the cache. 
resolves https://github.com/newrelic/newrelic-ruby-agent/issues/2846

Fix JRuby config manager bug

---

lib/new_relic/agent/instrumentation/rdkafka/chain.rb
lib/new_relic/agent/instrumentation/rdkafka/prepend.rb

I'm not seeing any failures on the CI, but locally the `test/new_relic/agent/instrumentation/instrumentation_test.rb` was failing for rdkafka files because we moved the requires into the execute in https://github.com/newrelic/newrelic-ruby-agent/pull/2841

fix for rdkafka on load tests

---

test/script/run_tests

I invoked `bert agent`, with a desire to run the tests located at `test/new_relic/agent_test.rb`. Instead the tests located at `test/new_relic/agent/rpm_agent_test.rb` were ran instead. This is because we were previously simply grabbing the very first `find` command.
Now, all results obtained by the `find` command will be considered, and the one with the shortest file path will be chosen.
In future we may want to detect the presence of `fzf` and prompt the human tester when multiple results are found, but for now this seems to yield pretty desirable behavior while still permitting the human to add more characters to the input string if they wish to disambiguate between multiple matches themselves.
Also, the `find` command was updated to only focus on files and not directories.

unit tests: scope to files, favor the shortest

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/ruby_kafka.rb
lib/new_relic/agent/instrumentation/ruby_kafka/chain.rb
lib/new_relic/agent/instrumentation/ruby_kafka/instrumentation.rb
lib/new_relic/agent/instrumentation/ruby_kafka/prepend.rb
test/multiverse/suites/ruby_kafka/Envfile
test/multiverse/suites/ruby_kafka/config/newrelic.yml
test/multiverse/suites/ruby_kafka/ruby_kafka_instrumentation_test.rb

Adds instrumentation for the ruby-kafka gem.
full ci run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/10795710672

Ruby kafka gem instrumentation

---

CHANGELOG.md
lib/new_relic/agent.rb
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/configuration/environment_source.rb
test/new_relic/agent/configuration/default_source_test.rb
test/new_relic/agent/configuration/environment_source_test.rb
test/new_relic/agent/configuration/orphan_configuration_test.rb
test/new_relic/agent_test.rb

A new `:automatic_custom_instrumentation_method_list` configuration parameter has been added to permit the user to define a list of namespaced method name strings representing methods that the agent should automatically add custom instrumentation tracers to.
resolves #2701

Apply method tracers automatically via config

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/configuration/manager.rb
lib/new_relic/agent/javascript_instrumentor.rb
test/new_relic/agent/configuration/default_source_test.rb

Enforces configs of type Boolean to contain either a boolean or a string/symbol of `true`, `false`, `yes`, `no`, `on`, or `off`
closes #2838

Lockdown Boolean configs

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/grape.rb
lib/new_relic/control/frameworks/rails4.rb
lib/new_relic/environment_report.rb
lib/new_relic/language_support.rb

The `Bundler::RubygemsIntegration.installed_specs` method was added in version 2.5.12. This PR updates the check to see if `Bundler.rubygems` responds to `installed_specs`.
2.5.11: https://github.com/rubygems/rubygems/blame/bundler-v2.5.11/bundler/lib/bundler/rubygems_integration.rb#L471 (all_specs only)
2.5.12: https://github.com/rubygems/rubygems/blame/bundler-v2.5.12/bundler/lib/bundler/rubygems_integration.rb#L479 (both all_specs and installed_specs)

Update min bundler version for installed_specs

---

CHANGELOG.md
lib/new_relic/agent/transaction/request_attributes.rb
test/new_relic/agent/transaction/request_attributes_test.rb

Rails 7.0 [changed](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#actiondispatch-request-content-type-now-returns-content-type-header-as-it-is) the behavior of `ActionDispatch::Request#content_type`, adding extra request-related details the agent wasn't expecting to collect, such as charset. Additionally, the agent's use of `content_type ` was triggering deprecation warnings. This PR updated the agent to use `ActionDispatch::Request#media_type` to capture the MIME type when available.
Closes #2506

Use `media_type` instead of `content_type` when avaliable

---

test/environments/railsedge/Gemfile

Updated 9 hours ago: https://github.com/rails/rails/commit/490004e35ef1dafb12e30affd7618366938c113d 
Full CI run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/11038047610

Rails edge now requires sqlite3 2.1+

---

.github/workflows/ci_cron.yml
test/multiverse/lib/multiverse/envfile.rb
test/multiverse/suites/active_record_pg/Envfile
test/multiverse/suites/active_support_broadcast_logger/Envfile
test/multiverse/suites/rails/Envfile
test/multiverse/suites/rails_prepend/Envfile

Rails 8.0 requires Ruby 3.2+.
~~Full CI run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/11110880352~~
~~Full CI run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/11111262251~~
Full CI run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/11111576874

Remove railsedge testing from Ruby 3.1

---

lib/new_relic/agent/instrumentation/view_component/instrumentation.rb

Issue: https://github.com/newrelic/newrelic-ruby-agent/issues/2869
Due to a recent change in the gem view_component 
https://github.com/ViewComponent/view_component/commit/451543a53f3c7c04036eb6109ac716511f3dcfc3#diff-b69c75ffd85596e0b5fca1327059ecf3b2930f3f77004c78a268fa85e8ec8d9eL601
We were getting:
`ActionView::Template::Error: undefined method `identifier'`
The method identifier on their base class has been removed.
This pull request make sure it returns nil if it is not found.

Safety guard when the self.class is not responding to method identifier

---

CHANGELOG.md
test/multiverse/suites/view_component/view_component_instrumentation_test.rb

unit test branch coverage and a CHANGELOG bugfix writeup to accompany PR #2870

unit test and CHANGELOG entry for 2870

---

docker-compose.yml

OpenSearch does not have a service, it's commented out. This was an oversight. The Docker compose file should start working again once this is merged.

Remove opensearch service from depends_on

---

test/multiverse/suites/stripe/Envfile

For now, limit Stripe testing to < v13

Stripe: restrict CI tests to Stripe <= v12

---

lib/sequel/extensions/new_relic_instrumentation.rb

Accommodate Sequel v5.85.0, which has made the timed connection pool the default for Ruby 3.2+ by always  permitting the use of a timed connection pool for explain plan generation in a Ruby 3.2+ context (previously only a Ruby 3.4+ context would work).
https://sequel.jeremyevans.net/rdoc/files/doc/release_notes/5_85_0_txt.html#label-Other+Improvements
resolves https://github.com/newrelic/newrelic-ruby-agent/pull/2888

Sequel: relax Ruby requirement for Timed pool

---

test/script/run_tests

clean up content on each fresh test run instance

tests script: perform cleanup

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/rdkafka/chain.rb
lib/new_relic/agent/instrumentation/rdkafka/prepend.rb

The rdkafka instrumentation gets installed on both the rdkafka gem and the karafka-rdkafka gem because it is a forked versions or rdkafka. However, they introduced a change in different versions that requires instrumentation to be installed different. 
resolves https://github.com/newrelic/newrelic-ruby-agent/issues/2879

Karafka rdkafka bugfix

---

test/script/run_tests

given than `berm` and `bermq` both follow the same path, prevent duplicate cleaning operations

berm/bermq: only clean once

---

lib/new_relic/agent/span_event_primitive.rb
test/new_relic/agent/transaction/datastore_segment_test.rb

increase the db.statement max from 2000 to 4096 as per the updated cross agent spec

increase db.statement threshold to 4096

---

.github/versions.yml
.github/workflows/ci.yml
.github/workflows/ci_cron.yml
.github/workflows/ci_jruby.yml
.github/workflows/ci_special.yml
.github/workflows/config_docs.yml
.github/workflows/performance_tests.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/release_notes.yml
.github/workflows/release_pr.yml
.github/workflows/slack_notifications.yml
lib/new_relic/agent/configuration/default_source.rb
test/agent_helper.rb
test/multiverse/suites/config_file_loading/Envfile
test/multiverse/suites/config_file_loading/config_file_loading_test.rb
test/new_relic/agent/configuration/manager_test.rb

New preview version out! 🎉 
[Release](https://github.com/ruby/setup-ruby/releases/tag/v1.196.0)
🟢 CI: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/11263849338

Test Ruby 3.4.0-preview2

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/view_component/instrumentation.rb
test/multiverse/suites/view_component/view_component_instrumentation_test.rb

View Component removed private method `.identifier` in v3.16.0, which is how the library used to identify components for instrumentation, and is what our was based off of as well. View Component now uses `source_location`. This PR updates our instrumentation to do the same and adds error handling in the case that the methods we rely on to build metric names are changed. `source_location` is a confirmed compatible call with the earliest version of View Component available on RubyGems, v1.16.0.
closes #2874

Update View Component metric building

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml
test/multiverse/lib/multiverse/runner.rb
test/multiverse/lib/multiverse/suite.rb

So this will make rdkafka run in it's own group for now. I named the group just kafka because i'd like to later include both kafka gems in it, but for now, for debugging our weird problems, I want it to only be rdkafka.
I also added the exit code to another string. We do already output the exit code in a different spot, but I wasn't seeing that message actually show up when we see our problem for some reason, so I've added it to a message that I do actually see, so maybe we'll get a little more info out of that.
```
Before:
"rdkafka" for Envfile entry 0 failed! 
Now
"rdkafka" for Envfile entry 0 failed! (exit: pid 9066 exit 1)
```

Rdkafka runs in its own multiverse group

---

test/new_relic/agent/configuration/manager_test.rb

Add the config that will allow the agent to do the behavior being tested in JRuby, since we will not do the extra config work in jruby unless the security agent is being used.

Fix for Jruby test failure that needs config enabled

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/grape.rb
lib/new_relic/control/frameworks/rails4.rb
lib/new_relic/environment_report.rb
lib/new_relic/helper.rb
lib/new_relic/language_support.rb
test/new_relic/helper_test.rb

This PR resolves a bug reported in #2885 to protect against scenarios where the version of Bundler used does not support `Bundler.rubygems.installed_specs` and needs to use `Bundler.rubygems.all_specs` to determine whether the third-party gem, `newrelic-grape` is installed in the environment.
Resolves #2885

Create helper to access Bundler.rubygems specs

---

lib/new_relic/dependency_detection.rb
test/multiverse/suites/sinatra/sinatra_test_cases.rb
test/new_relic/dependency_detection_test.rb

address 2 issues causing dependency detection to falsely label an instrumentation's dependencies as "unsatisfied".
- handle Padrino with a special case pending resolution of https://github.com/newrelic/newrelic-ruby-agent/issues/2912
- don't mark an item as unsatisfied the second (or higher) time it comes around through the `detect!` loop
resolves #2893

prevent false 'unsatisfied' dependency status

---

lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/configuration/environment_source.rb
lib/new_relic/agent/configuration/manager.rb
lib/new_relic/control/instance_methods.rb
test/multiverse/suites/agent_only/logging_test.rb
test/multiverse/suites/rake/instrumentation_test.rb
test/new_relic/agent/configuration/default_source_test.rb
test/new_relic/agent/configuration/environment_source_test.rb
test/new_relic/agent/configuration/manager_test.rb
test/new_relic/agent/hostname_test.rb
test/new_relic/agent/local_log_decorator_test.rb

Rework the processing of configuration parameters to address #2852.
- nils to produce errors when user-supplied for params that don't support them
- introduce a common shared type coercion layer for all config values so that things like environment variable and YAML values are both consistently coerced
- allow type coercion to Array/Hash to replace all of the equivalent default source  based`:transform` entries
- lay the foundation for increased server side and env var based support for certain params that are currently marked as YAML source only (functionally ready now, updating tests and docs for each affected param to be handled later)
- permit Integer values for Float params (using `#to_f`) and Float values for Integer params (using `#round`)
- prevent fatal interruptions and log …

type coercion for configuration parameters

---

lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/active_support.rb
lib/new_relic/agent/instrumentation/active_support_subscriber.rb
test/new_relic/agent/instrumentation/rails/active_support_subscriber.rb

Added a new :'instrumentation.active_support_notifications.active_support_events' configuration parameter to permit a user defined allowlist of Active Support notifications event names for the agent to subscribe to that are related to the Active Support library itself.
Event names that are not included on the list will be ignored by the agent

ActiveSupport notifications: allowlist event names

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/ruby_kafka/prepend.rb

`Kafka::Consumer#each_message` takes keyword arguments. In Ruby >= 3.0, prepending it with a method that takes only positional arguments causes an ArgumentError when calling `super`.

Use double splat for Ruby >= 3.0

---

lib/tasks/instrumentation_generator/templates/dependency_detection.tt

as per #2844, don't perform `require_relative` on content that won't be used unless all dependency detection checks succeed

DD templating: conditionally invoke requires

---

lib/tasks/instrumentation_generator/templates/dependency_detection.tt

the template's rendering of a `named` line was previously attempting to
wrap symbol values with single quotes when necessary.
but given that everything is routed through the `snake_name` method,
nothing will ever need the quotes if we simply use the output of that
method, held in `@snake_name`.

DD: update the rendering of the 'named' line

---

CHANGELOG.md
lib/new_relic/agent/aws.rb
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/dynamodb/instrumentation.rb
test/multiverse/suites/dynamodb/dynamodb_instrumentation_test.rb
test/new_relic/agent/aws_test.rb

Adds a config option `cloud.aws.account_id` that will allow customers to set their associated AWS account ID to provide more details and improve entity relationships in the UI. Currently, the only instrumentation using this is DynamoDB
resolves https://github.com/newrelic/newrelic-ruby-agent/issues/2895
resolves https://github.com/newrelic/newrelic-ruby-agent/issues/2896

Add config option for AWS account id

---

CHANGELOG.md
lib/new_relic/agent/configuration/manager.rb
test/new_relic/agent/configuration/manager_test.rb
test/new_relic/agent/serverless_handler_test.rb

v9.14.0 introduced improved handling of boolean based configuration parameters and inadvertently broke AWS Lambda layer based functionality due to a bypassing of config transformations for booleans.
Boolean based values will now again be routed through their transformations if defined.
resolves #2919

bugfix: always apply transformations on booleans

---

.github/versions.yml
.github/workflows/security.yml

Resolves #2843 
Example scan: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/11580092166 
Slack notifications only on scheduled runs that fail. Untested, but copied from our nightly cron.

Add security scan

---

.gitignore

My spellcheck stores saved words in a .vscode/ directory, and apparently thats not something we've had happen in our repo before, so I added it to the gitignore.

add .vscode/ to gitignore

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/instrumentation/aws_sdk_lambda.rb
lib/new_relic/agent/instrumentation/aws_sdk_lambda/chain.rb
lib/new_relic/agent/instrumentation/aws_sdk_lambda/instrumentation.rb
lib/new_relic/agent/instrumentation/aws_sdk_lambda/prepend.rb
test/multiverse/suites/aws_sdk_lambda/Envfile
test/multiverse/suites/aws_sdk_lambda/aws_sdk_lambda_instrumentation_test.rb
test/multiverse/suites/aws_sdk_lambda/aws_sdk_monkeypatch.rb
test/multiverse/suites/aws_sdk_lambda/config/newrelic.yml

Instrument the aws-sdk-lambda gem and upon function invocations performed by the client, create external request segments that include AWS resource information.

instrumentation for aws-sdk-lambda

---

lib/new_relic/agent/instrumentation/aws_sdk_lambda/instrumentation.rb
test/multiverse/suites/aws_sdk_lambda/aws_sdk_lambda_instrumentation_test.rb

commit 0a1527d8012cfb34c3950d34180d0974b51ab9ed sought to improve error handling, but incorrectly misused an `ensure` block to attempt to always return the raw client response.
this faulty logic has been fixed. internal agent response handling errors are logged as desired, not re-raised to the user's app, and the user's app is guaranteed to always get the raw original response.

aws-sdk-lambda fix

---

test/new_relic/healthy_urls_test.rb

ignore `https://lambda.#` urls

healthy urls test: ignore lambda comment

---

.github/workflows/security.yml

One potential solution for the TOOMANYREQUESTS error.
Sources:
* https://github.com/aquasecurity/trivy/discussions/7538
* https://aquasecurity.github.io/trivy/v0.55/docs/references/troubleshooting/#github-rate-limiting 
* https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#use-non-default-token-to-install-trivy

Add token to Trivy report mode

---

lib/new_relic/agent/instrumentation/aws_sdk_lambda/chain.rb
lib/new_relic/agent/instrumentation/aws_sdk_lambda/instrumentation.rb
lib/new_relic/agent/instrumentation/aws_sdk_lambda/prepend.rb
test/multiverse/suites/aws_sdk_lambda/aws_sdk_lambda_instrumentation_test.rb

the use of external request segments can cause confusion for Lambda entity relationships. should we wish to expose the underlying net call to the AWS back-end API in future, we can do so by simply removing the `disable_all_tracing` wrapper and allow the underlying Net::HTTP call to be instrumented.

aws-sdk-lambda: don't use external segments

---

test/multiverse/suites/agent_only/thread_profiling_test.rb

This is a temporary measure until we can work on #2947

Skip test_thread_profiling_can_stop on Ruby 3.0+

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/log_event_aggregator.rb
test/new_relic/agent/log_event_aggregator_test.rb

Add your New Relic labels/tags to your log events
Now, logs forwarded by the Ruby agent can have your New Relic labels (referred to as tags in the UI), as set using the `:labels` config option in `newrelic.yml` or the `NEW_RELIC_LABELS` environment variable, applied as attributes to your log events. This can help you cross-reference information you're used to seeing on your entities and transactions on your log events as well.
All labels attached to log events as attributes will be prefixed with `tags.`
This feature is off by default. To enable it, you will need to update your configuration:
newrelic.yml:
`application_logging.forwarding.labels.enabled: true` 
environment variable:
`NEW_RELIC_APPLICATION_LOGGING_FORWARDING_LABELS_ENABLED=true`
In addition, we have a configuration option …

Add configuration options to apply labels to log events

---

.github/workflows/security.yml

Try setting `cache: false` in Trivy action to avoid TOOMANYREQUESTS error

disable cache for trivy

---

test/multiverse/suites/deferred_instrumentation/sinatra_test.rb
test/multiverse/suites/rails/rails3_app/my_app.rb
test/multiverse/suites/sinatra/ignoring_test.rb
test/multiverse/suites/sinatra/nested_middleware_test.rb
test/multiverse/suites/sinatra/sinatra_classic_test.rb
test/multiverse/suites/sinatra/sinatra_error_tracing_test.rb
test/multiverse/suites/sinatra/sinatra_metric_explosion_test.rb
test/multiverse/suites/sinatra/sinatra_modular_test.rb
test/multiverse/suites/sinatra/sinatra_parameter_capture_test.rb
test/multiverse/suites/sinatra/sinatra_routes_test.rb
test/multiverse/suites/sinatra_agent_disabled/shim_test.rb

Sinatra 4.1.0 introduced a new `host_authorization` setting that requires app creators to determine if a header value can be trusted - https://github.com/sinatra/sinatra/pull/2053
This change requires an update to the Sinatra test apps we've built for testing.

disable HostAuthorization middleware for Sinatra testing

---

test/multiverse/suites/agent_only/thread_profiling_test.rb

Intermittent failures occur on the other test, `test_thread_profiling`, so skip those until we can address with #2947

Skip test_thread_profiling on 3.0+

---

lib/new_relic/agent/aws.rb
lib/new_relic/agent/instrumentation/aws_sdk_lambda/instrumentation.rb
lib/new_relic/agent/instrumentation/dynamodb/instrumentation.rb
test/new_relic/agent/aws_test.rb

Now that we have the official approval from AWS to get the aws account ID by decoding, i have now added that logic back to the AWS module and updated the instrumentation modules using that.

Resurrect aws account id decoding

---

CHANGELOG.md

The biggest change here is the removal of the overview sentence. If I remember correctly, the overview sentence used to help us on the page that displayed all of the Release Notes on the docs website. 
Now that the Release Notes page does not feature snippets, but instead shows the entire release notes, I don't think we need it anymore. 
* 9.16.0 release notes: https://docs.newrelic.com/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-9-16-0/ 
* Release notes page: https://docs.newrelic.com/docs/release-notes/agent-release-notes/ruby-release-notes 
* Old release notes structure: https://web.archive.org/web/20230205165159/https://docs.newrelic.com/docs/release-notes/agent-release-notes/ruby-release-notes/

Sync changelog with docs editor updates

---

lib/new_relic/agent.rb
test/new_relic/agent_test.rb

Previously, the agent would emit a`WARN` level log when it is unavailable, causing excess log noise. The agent now emits a `DEBUG` level log instead.
closes #2972

Change agent status to debug not warn

---

lib/new_relic/agent/configuration/default_source.rb

Previously, a log message stating "Detected untested Rails version 8.*" would be emitted. This is incorrect, as we are now testing the agent against Rails 8.0

Add Rails 8.0 to accepted framework versions

---

lib/new_relic/agent/configuration/default_source.rb

The link pointed to a config option that has since been renamed to allowed classes.

Fix relative link in config description

---

.github/workflows/ci.yml
.simplecov
lib/new_relic/agent/configuration/yaml_source.rb
test/multiverse/suites/config_file_loading/Envfile
test/multiverse/suites/config_file_loading/config_file_loading_test.rb

Ruby 3.4 no longer provides the line number in the exception message for the error raised by a failure to parse ERB in the newrelic.yml file.
To help our customers with debugging, add the line number to the output by printing the first line of the backtrace for the exception to the agent logs
Resolves #2902
Full CI: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/12285237901
Also, we removed branch coverage because there's a bug in Ruby 3.4's version of the prism parser that causes suites to silently fail when simplecov runs: https://bugs.ruby-lang.org/issues/20866

Add backtrace line 0 to 3.4 ERB failure logs

---

.github/versions.yml
.github/workflows/ci.yml
.github/workflows/ci_cron.yml
.github/workflows/ci_jruby.yml
.github/workflows/ci_special.yml
.github/workflows/config_docs.yml
.github/workflows/performance_tests.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/release_notes.yml
.github/workflows/release_pr.yml
.github/workflows/slack_notifications.yml
test/multiverse/suites/config_file_loading/Envfile

Adds the first release candidate for Ruby 3.4.0 to the CI. 
https://www.ruby-lang.org/en/news/2024/12/12/ruby-3-4-0-rc1-released/ 
It also bumps the ruby/setup-ruby version for all workflows.
🟢 Passing CI run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/12382636120

Bump ruby/setup-ruby and add ruby-3.4.0-rc1 to ci

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml

Though Rails 8.0 has been tested through Rails Edge, let's make our support official.

Add rails80 testing explicitly to the CI

---

.rubocop.yml
CHANGELOG.md
lib/new_relic/agent/threading/backtrace_node.rb
test/new_relic/agent/threading/backtrace_node_test.rb
test/new_relic/agent/threading/thread_profile_test.rb

Closes #2992
CI, passing on the relevant runs: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/12403980066

Thread Profile / Backtrace 3.4.0 fixes

---

test/multiverse/suites/rails/Envfile
test/multiverse/suites/rails_prepend/Envfile

CI with the other Rails versions passing also: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/12519740439 
(timeouts though for some of the `rest` suite)

Remove version lock on haml in Rails multiverse

---

.github/versions.yml
.github/workflows/ci.yml
.github/workflows/ci_cron.yml
.github/workflows/ci_jruby.yml
.github/workflows/ci_special.yml
.github/workflows/config_docs.yml
.github/workflows/performance_tests.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/release_notes.yml
.github/workflows/release_pr.yml
.github/workflows/slack_notifications.yml
test/multiverse/suites/grpc/Envfile
test/performance/Gemfile
test/performance/rails_app/config/application.rb

Ruby 3.4.1 is out! This PR updates the CI to test the newest version and replaces the areas where we used Ruby 3.3 as our default version to Ruby 3.4.
Workflow dispatches to check: 
* Perf tests: ~~https://github.com/newrelic/newrelic-ruby-agent/actions/runs/12590713430~~ 
* ~~https://github.com/newrelic/newrelic-ruby-agent/actions/runs/12590853852~~ (failing with base64 error)
* https://github.com/newrelic/newrelic-ruby-agent/actions/runs/12601064376 => failing with the same error, but this seems to be because it's trying to use 3.4 on `main`, which is still pointing to the old Rails version. Perf tests ran locally just fine on the current branch. I think we're safe to test.
* 🟢 URL test CI: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/12590710130 (as an example of a …

🎁 Run tests on Ruby 3.4.1

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
newrelic.yml

Ruby moved the logger code out of the ruby/ruby repository. This change uses the ruby/logger repository and also uses a permalink. 
I imagine the newrelic.yml changes will be updated again whenever we release, so I just added the permalink to the existing setup to get the URL CI to pass.
Passing URL CI: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/12755313559 🟢

Use permalink for Logger::Severity

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml
test/multiverse/lib/multiverse/runner.rb

So, this does seem to work to prevent the github communication errors/running out of resources thing from happening, yay!
scheduled CI run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/12772900369
I saw a couple of random actual intermittent test failures, like a timeout or openai complaining about not having a token, BUT I haven't seen ANY github communication errors come up on there and I tried rerunning it several times to give it as many chances to fail as I could. 
I don't love how much bigger the files are now and all the duplication I had to add. 
But it's better to have an annoying file than have github actions run out of resources all the time though, so ¯\\_(ツ)_/¯ oh well
Here is what changed for multiverse:
- multiverse: removed all services and runs most our …

Update multiverse jobs in CI to avoid resource issues in github actions

---

test/helpers/misc.rb

stops the url checker test from running locally

only run special CI when on CI, not locally

---

CHANGELOG.md
lib/boot/strap.rb
test/new_relic/boot/strap_test.rb

Previously, when the new relic ruby agent was installed via in a customer's `Gemfile` and attempted to be installed through the k8s operator, the agent version listed in `Gemfile` would take priority. Now, if the agent is installed via operator when both are present, the Gemfile version will be removed and the operator version will be used. 
Closes #2890

Update k8s boot/strap priority agent version

---

test/multiverse/README.md
test/multiverse/lib/multiverse/suite.rb
test/test_helper.rb

Suites related to Rails 6.0, 6.1 and 7.0 started to fail with an uninitialized constant error related to the Logger::Severity constant. This only fixes failures in the multiverse suite.

Explicitly require logger in suite.rb

---

.github/ISSUE_TEMPLATE/bug_report.md
CONTRIBUTING.md

`discuss.newrelic.com` should be replaced by the new site, `forum.newrelic.com`. While old links redirect, we should update our docs to use the correct URLs.

Update to "forum" links

---

test/multiverse/suites/ruby_openai/openai_helpers.rb

when client is created it gives it a face access token. the error we were seeing was when connection_client is used in the first test run instead of client, it was mad about not having any access token. so I made it create the client in connection_client and that made it work.
resolves https://github.com/newrelic/newrelic-ruby-agent/issues/3031

Ruby openai intermittent failure fix

---

.github/workflows/release.yml

We are getting rid of the internal [auto-layer-releases repo](https://source.datanerd.us/aws-lambda/auto-layer-releases/blob/master/app.py) and moving creating of the release tags into each agent's GHA deploy flow.

Move init container release from lambda to GHA

---

CHANGELOG.md
lib/new_relic/agent/database.rb
lib/new_relic/agent/instrumentation/active_record_helper.rb
lib/new_relic/agent/instrumentation/active_record_subscriber.rb
test/new_relic/agent/database_test.rb

We won't record host, port or db name info unless we recognize the adapter. Also for redshift, regular activerecord doesnt work, so you need to use some other gem for a redshift adapter (it looks like there are quite a lot of these for each rails version). It seems pretty consistently to be named redshift on the adapter in those gems though it seems, on the ones i saw at least. 
This is the gem i used in my testing https://github.com/pennylane-hq/activerecord-adapter-redshift
closes https://github.com/newrelic/newrelic-ruby-agent/issues/2900

Add Redshift active record adapter

---

lib/new_relic/agent/instrumentation/sidekiq/extensions/delayed_class.rb

the url test was failing with:
```
1) Failure:
HealthyUrlsTest#test_all_urls [/opt/hostedtoolcache/Ruby/3.4.1/x64/lib/ruby/gems/3.4.0/gems/minitest-5.3.3/lib/minitest/assertions.rb:129]:
1 URLs were unreachable!
https://github.com/mperham/sidekiq/issues/5076 - HTTP 404: Not Found
files: /home/runner/work/newrelic-ruby-agent/newrelic-ruby-agent/lib/new_relic/agent/instrumentation/sidekiq/extensions/delayed_class.rb.
Expected {"https://github.com/mperham/sidekiq/issues/5076" => "HTTP 404: Not Found"} to be empty.
```
Looks like the link has changed, so i updated it here.
```
old: https://github.com/mperham/sidekiq/issues/5076
new: https://github.com/sidekiq/sidekiq/issues/5076
```

update link for sidekiq issue

---

.github/workflows/lambda_release.yml

Use version

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/net_http/instrumentation.rb

related to https://github.com/newrelic/newrelic-ruby-agent/issues/3021
This isn't addressing the root cause of the issue yet, as that's still being investigated, but this change should prevent the primary reported error from occurring.

Add safe navigation in case segment is nil in net http instrumentation

---

lib/new_relic/agent/configuration/default_source.rb

Moving the `error_collector.ignore_classes` config details so the `error_collector` section is alphabetized as this is the only section out of place. This also groups the `ignore_` section in a logical way for browsing [the config doc](https://docs.newrelic.com/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration/#error-collector). …

chore: move ignore_classes in docs

---

CHANGELOG.md
lib/new_relic/agent/instrumentation/sidekiq.rb

Prepend the agent to Sidekiq's middleware chain. This stops Sidekiq-resolved exceptions from being reported to New Relic. 
We have a playground app that reproduces this issue. The introduction of this code successfully stops the error from being reported.
Closes #3037

Prepend NR middleware to Sidekiq middleware chain

---

CHANGELOG.md
lib/new_relic/agent/transaction.rb
lib/new_relic/agent/transaction/tracing.rb

Adds some safe navigation operators in cases where things are nil, for increased safety. 
Also added a new mutex for modifying and finalizing segments.
These things were added due to issues when running in jruby. 
resolves https://github.com/newrelic/newrelic-ruby-agent/issues/3021

Add nil safety for Jruby issue

---

.github/workflows/slack_notifications.yml

Let's have slack notifications for new gem releases run an hour before our CI. These should now run at about midnight and the CI kicks off at 1am PST.

Move Slack notifications up 2 hours

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb

When using the solid_queue gem, the agent previously generated excessive warn-level logs when the queue was empty. The agent now ignores `queue empty` error messages of the `ThreadError` class by default. This behavior can be adjusted using the `error_collector.ignore_messages` configuration option.

Solid Queue - Ignore `queue empty` error message by default

---

test/multiverse/suites/sidekiq/Envfile

With the release of Sidekiq 8, we should update our multiverse test suite to test 7.x now that `nil` is grabbing 8.x
Note Sidekiq 8 requires Ruby >= 3.2, so we will use that Ruby version as the min.

Test 7.x of Sidekiq

---

.build_ignore

The template for newrelic.yml in the generator can cause conflicts with the NRDiag tool.
Closes #2441

Remove instrumentation generator from build

---

test/new_relic/fake_server.rb

so the rack problem we had was because there was simply a 2 in the version number.
For deciding when to install rackup/handler, we were using the regex `/^1|2/` which checks to see if it starts with a 1 OR 2, BUT what it's actually checking is if (starts with a 1) OR 2. So just a 2 hanging out anywhere in the version will be like, yeah that's matching. 
So i changed it to `/^1|^2/` which is just starts with a 1 OR starts with a 2. which is what we actually intended originally.

fix the regex used for deciding to require rackup/handler

---

lib/new_relic/control/instance_methods.rb
test/new_relic/control_test.rb

Proposed new metric name: `Supportability/AgentVersion/newrelic_rpm/#{NewRelic::VERSION::STRING}`
Closes #2627

Add supportability metric for agent version

---

.github/versions.yml
.github/workflows/add_issues_to_project.yml

I think New Relic may have hit [its auto-add workflow limits](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/adding-items-automatically#about-automatically-adding-items), which would prevent our items from getting auto-added to our engineering board. 
As a workaround, we can call the add-to-project action in a workflow whenever a new issue is created. Unfortunately, it doesn't have an option to set a column. I'm not exactly sure where the issues will go.

Add action to put new issues on the board

---

.github/workflows/add_issues_to_project.yml

The token used needs to be a PAT. See the action's README for details. Also, make the name shorter.
https://github.com/actions/add-to-project?tab=readme-ov-file#creating-a-pat-and-adding-it-to-your-repository

Update add_issues_to_project workflow token

---

CHANGELOG.md
lib/new_relic/agent/utilization_data.rb

This updated our checks for vendor metadata to be run in parallel to decrease how much time it takes to get this information.
It will wait until one successful request OR until all finish unsuccessfully 
closes #2845 (the other idea mentioned in the issue is something we are already doing)

Parallelize vendor metadata requests

---

lib/new_relic/agent/http_clients/uri_util.rb

When passing a frozen string as the host, the agent breaks with the following error:
```
FrozenError (can't modify frozen String)
```
I encountered this issue while using the [Pusher gem](https://github.com/pusher/pusher-http-ruby). The idea of this pull request is to replace the use of the downcase! method with a reassignment of the string, preventing errors when working with frozen strings.
I have applied thos changes on my project and it started to work fine. …

Refactor URI host handling to ensure downcasing is applied correctly on frozen strings

---

lib/new_relic/agent/configuration/default_source.rb
lib/tasks/helpers/newrelicyml.rb
newrelic.yml

Add support for code fences in the newrelicyml.rb generator. 
Closes [#2959](https://github.com/newrelic/newrelic-ruby-agent/issues/2959)

Adapt newrelic.yml generator to code fences

---

lib/new_relic/agent/instrumentation/active_job_subscriber.rb
test/new_relic/agent/instrumentation/rails/active_job_subscriber.rb

Stacktrace: 
```
** [NewRelic][2025-04-01 13:44:17 +0000 run.* (4)] ERROR : Error during start callback for event 'enqueue_all.active_job':
** [NewRelic][2025-04-01 13:44:17 +0000 run.* (4)] ERROR : NoMethodError: undefined method `queue_name' for nil
** [NewRelic][2025-04-01 13:44:17 +0000 run.* (4)] ERROR : Debugging backtrace:
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.17.0/lib/new_relic/agent/instrumentation/active_job_subscriber.rb:20:in `metric_name'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.17.0/lib/new_relic/agent/instrumentation/notifications_subscriber.rb:71:in `start_segment'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.17.0/lib/new_relic/agent/instrumentation/notifications_subscriber.rb:57:in `start' …
```

Fixes NoMethodError: undefined method `queue_name' for nil in ActiveJobSubscriber when using perform_all_later.

---

CHANGELOG.md
lib/new_relic/agent/transaction/request_attributes.rb
test/multiverse/suites/agent_only/agent_attributes_test.rb
test/multiverse/suites/grape/grape_test.rb
test/multiverse/suites/rails/parameter_capture_test.rb
test/multiverse/suites/sinatra/sinatra_parameter_capture_test.rb

Add request.uri to transaction events

---

lib/new_relic/agent/opentelemetry/trace/tracer.rb
test/multiverse/suites/hybrid_agent/hybrid_agent_test.rb

For internal span kinds, yield immediately if there is not a current transaction
Resolves #3141

HA CAT - Do not create a segment without a transaction

---

test/multiverse/suites/elasticsearch/Envfile

We're failing on elasticsearch 9 after release. Once we resolve this issue, we need to reenable the tests.
related to: https://github.com/newrelic/newrelic-ruby-agent/issues/3153

stop testing elasticsearch 9 for now

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/agent/transaction/trace_context.rb
test/new_relic/agent/distributed_tracing/trace_context_test.rb

Adds logic to support the new configuration options to modify how we decide sampling and priority based on incoming traceparent value. When in default mode, the existing logic of the agent remains unchanged. 
resolves https://github.com/newrelic/newrelic-ruby-agent/issues/3077
related agent specs
[Original PR](https://source.datanerd.us/agents/agent-specs/pull/726)
[Clarifying Configs](https://source.datanerd.us/agents/agent-specs/pull/729)

W3C Sampling Flag Support

---

lib/new_relic/agent/configuration/default_source.rb

The `error_collector.ignore_messages` config is our first Hash config with a default value that isn't an empty Hash.
The default needs to use a hash rocket instead of a symbol to keep the key as a String, but this isn't valid YAML.
This PR updates the documented default to be valid in YAML.
When this is merged in, we should run the config_docs workflow to update the published documentation.
Resolves #3157

Update documented default for `error_collector.ignore_messages`

---

.github/workflows/prerelease.yml

GITHUB_TOKEN values will not trigger other workflows when PRs are opened
We want the full CI to run when the prerelease PR is created, so use the PAT for our bot instead.
Context: 
* [Slack thread (internal)](https://newrelic.slack.com/archives/GGXADQ9F1/p1745952130062349)
* https://github.com/orgs/community/discussions/57484

Use the bot PAT to create prerelease PR

---

test/multiverse/suites/config_file_loading/Envfile

Psych 5.2 supports Ruby 2.5+, but we began to get some Bundler errors on May 1, 2025 for Ruby 2.5 and 2.6 for Psych 5.2.4.
Until those errors are resolved, limit testing for the newest versions of Psych to 2.7+
🟢 Test run for 2.5/2.6: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/14782845545

Limit psych installs for Ruby 2.5 and 2.6

---

.github/workflows/lambda_release.yml

* Use the rake task that returns our version number instead of GITHUB_REF_NAME
* Add workflow_dispatch so we can rerun if there's failures 
Resolves #3170

Fix lambda release

---

test/multiverse/suites/async_http/Envfile

The latest version of the `async` gem isn't compatible with the oldest version we test, `0.59.x`. This PR sets a specific async version for that scenario.

Set async version for old async-http

---

lib/new_relic/agent/opentelemetry/trace/tracer.rb
lib/new_relic/agent/opentelemetry/transaction_patch.rb
lib/new_relic/agent/opentelemetry_bridge.rb
test/multiverse/suites/hybrid_agent/hybrid_agent_test.rb
test/multiverse/suites/hybrid_agent/span_test.rb
test/multiverse/suites/hybrid_agent/tracer_test.rb

Leverage New Relic's context methods for managing the current segment to update OpenTelemetry's current span by prepending onto our Transaction class when the OpenTelemetry Bridge is installed.
When the `current_segment_key` is fully removed from the Transaction, take this as a cue to fully detach from the OpenTelemetry context.
This implementation is drawn from the strategy used by [OpenTelemetry::Tracer.with_span](https://github.com/open-telemetry/opentelemetry-ruby/blob/b2cac915e2662f91e032097c4e0c6e9395128d64/api/lib/opentelemetry/trace.rb#L62-L71), which calls [OpenTelemetry::Context.with_value](https://github.com/open-telemetry/opentelemetry-ruby/blob/b2cac915e2662f91e032097c4e0c6e9395128d64/api/lib/opentelemetry/context.rb#L77-L91) to keep track of the current span.
Resolves #3142

Hybrid Agent: Create New Relic Span as child of OpenTelemetry Span

---

test/multiverse/suites/async_http/Envfile

Forgot that older Rubies were passing. Just stop testing the oldest version on newer Rubies to avoid an incompatible version of `async` from getting matched. The newer Rubies are tested on their latest compatible version.
~~Full CI workflow to verify: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/14843837242~~
~~Full CI workflow: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/14844446919~~
🟢 [Scheduled Continuous Integration](https://github.com/newrelic/newrelic-ruby-agent/actions/runs/14846357604)

Update Envfile for async-http

---

.github/workflows/ci_special.yml

GitHub has lowered their threshold before a 429 is hit for requests. This CI run hits the threshold, causing the workflow to fail despite the links being active.

Disable the URL checker cron

---

lib/new_relic/agent/opentelemetry/trace/span.rb
lib/new_relic/agent/opentelemetry/trace/tracer.rb
lib/new_relic/agent/opentelemetry/transaction_patch.rb
test/multiverse/suites/hybrid_agent/Envfile
test/multiverse/suites/hybrid_agent/commands.rb
test/multiverse/suites/hybrid_agent/hybrid_agent_test.rb
test/multiverse/suites/hybrid_agent/parsing_helpers.rb
test/multiverse/suites/hybrid_agent/span_test.rb
test/multiverse/suites/hybrid_agent/tracer_provider_test.rb
test/multiverse/suites/hybrid_agent/tracer_test.rb
test/multiverse/suites/hybrid_agent/transaction_patch_test.rb

This PR changes the strategy used to create transactions and segments when OpenTelemetry APIs are called to cue off the parent_context rather than the span kind.
* Add `finishable` to OpenTelemetry Span class to track the
corresponding New Relic segment/transaction
* Add `Tracer#start_span` patch for `:server` span kinds
* Refactor `Tracer#in_span` to use `#start_span`
* Start new transactions based on parent context rather than span kind
* Do not start a transaction if span kind is internal
* Update arguments for OpenTelemetry Span class to accept
only `span_context`, and create the span context in a
a separate method
* Update agent output tests to look at individual keys rather
than a full hash match
Closes #3145

Enable "Starting transaction tests" in hybrid agent CAT

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml
test/multiverse/lib/multiverse/runner.rb
test/multiverse/suites/elasticsearch/Envfile
test/multiverse/suites/elasticsearch/elasticsearch_instrumentation_test.rb

Adds elasticsearch 9 service to the CI and allows those tests to start running again\
Ran into some docker memory usage issues so I took out elasticsearch 8 from the CI since its the same as 9. Also moved elasticsearch into its own group.
closes https://github.com/newrelic/newrelic-ruby-agent/issues/3153
schedule ci https://github.com/newrelic/newrelic-ruby-agent/actions/runs/15542099551

Set up elasticsearch 9 in CI

---

test/fixtures/cross_agent_tests/hybrid_agent.json
test/multiverse/suites/hybrid_agent/parsing_helpers.rb

Two changes here:
1. Improvements made to the `verify_span_output` parsing helper to make it easier to debug and fix the attributes assertion
2. Updated to the latest version of the `hybrid_agent.json` file

Hybrid agent span output test fix

---

lib/new_relic/agent/opentelemetry/context/propagation/trace_propagator.rb
lib/new_relic/agent/opentelemetry/trace/tracer.rb
lib/new_relic/agent/opentelemetry/transaction_patch.rb
lib/new_relic/agent/transaction/trace_context.rb
test/multiverse/suites/hybrid_agent/commands.rb
test/multiverse/suites/hybrid_agent/hybrid_agent_test.rb
test/multiverse/suites/hybrid_agent/span_test.rb
test/multiverse/suites/hybrid_agent/trace_propagator_test.rb
test/multiverse/suites/hybrid_agent/tracer_test.rb
test/multiverse/suites/hybrid_agent/transaction_patch_test.rb

This PR adds an `extract` method to the TracePropagator to handle inbound distributed tracing context.
When spans have remote parents, the information is updated after the transaction/segment is started, but before yielding [(example)](https://github.com/newrelic/newrelic-ruby-agent/blob/5ca88b7a2f46d1b94e9540543c7b72e8aaa2ccf0/lib/new_relic/agent/instrumentation/rdkafka/instrumentation.rb#L28). The OpenTelemetry bridge follows this approach. 
There's also some renaming of variables to make things more clear.
These changes allow the ["Inbound distributed tracing tests"](https://github.com/newrelic/newrelic-ruby-agent/blob/f7a989066d88818fce0a0b599ad036bb918d67ae/test/fixtures/cross_agent_tests/hybrid_agent.json#L524-L629) described in the hybrid_agent.json file to pass.

Hybrid Agent Cross-Agent Tests: Inbound distributed tracing tests

---

CHANGELOG.md
lib/new_relic/agent/span_event_primitive.rb
test/new_relic/agent/transaction/datastore_segment_test.rb

When the duration is over the threshold, we should capture the stacktrace as an attribute on spans. Previously, the stacktrace was only on slowsql statements and not added to spans.
resolves https://github.com/newrelic/newrelic-ruby-agent/issues/2357

add code.stacktrace attribute to datastore span

---

.github/workflows/ci_cron.yml
.github/workflows/ci_jruby.yml
.github/workflows/ci_special.yml

This PR:
- Adds fail/success slack notifications for the JRuby CI workflow.
- Updates the Cron CI slack notifications to wait for the all jobs to finish before running
- Adds a read-only permission to slack jobs (security recommendation)
Closes https://github.com/newrelic/newrelic-ruby-agent/issues/3214

Add CI notifications for JRuby

---

test/multiverse/suites/hybrid_agent/trace_propagator_test.rb

An extra `>` was included in an assert, and JRuby was looking to match exactly that. The extra character has been removed (it isn't present in the payload, so was never needed anyways). 
JRuby CI Run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/16325584078
Closes [#3213](https://github.com/newrelic/newrelic-ruby-agent/issues/3213)
Payload:
```ruby
=> "{#<OpenTelemetry::Context::Key:0x62ec4146 @name=\"current-span\">=>#<OpenTelemetry::Trace::Span:0x4c941d19 @context=#<OpenTelemetry::Trace::SpanContext:0x5248c05a @tracestate=#<NewRelic::Agent::TraceContextPayload:0x151f1734 @priority=0.23456, @timestamp=1518469636035, @parent_app_id=\"46954\", @sampled=false, @version=0, @transaction_id=\"e8b91a159289ff74\", @id=\"7d3efb1b173fecfa\", @parent_type_id=0, …
```

Edit test regex

---

lib/new_relic/agent/distributed_tracing/cross_app_tracing.rb
lib/new_relic/agent/monitors/inbound_request_monitor.rb
lib/new_relic/agent/monitors/synthetics_monitor.rb
lib/new_relic/agent/transaction/distributed_tracer.rb

`JSON.parse` is the safer of the two methods.

Replace all calls to JSON.load with JSON.parse

---

CHANGELOG.md

I noticed we missed an entry for one of our community contributions included in this release.

Add unknown constant changelog entry

---

test/multiverse/suites/rdkafka/Envfile

A new version (0.21.0) of karafka-rdkafka was released and it is causing one of our kafka tests to fail intermittently. This pins the version in our tests to a known working version while we investigate the issue and see what needs to be done to support the new version

pin karafka-rdkafka version

---

test/multiverse/suites/rdkafka/Envfile
test/multiverse/suites/rdkafka/rdkafka_instrumentation_test.rb

The new version of karafka_rdkafka runs faster than the previous version, which lead to some tests running with the same timestamp on the topic name. Each test uses a unique topic because only some tests consume the messages produced. The failures we were seeing were caused by a shared topic between multiple tests, but the first tests only produced messages, and did not consume that message. So when the DT test ran and consumed the first message in the topic, it was a message from a previous test leaking into the DT test. That's why the trace IDs wouldn't match. So now we also slap a rand on the topic name to avoid this problem.

Fix for intermittently failing karafka_rdkafka 0.21.0 test

---

CHANGELOG.md
lib/new_relic/agent/configuration/default_source.rb
lib/new_relic/cli/commands/deployments.rb

Deprecate `newrelic deployments` CLI command
Users should refer to [Change Tracking](https://docs.newrelic.com/docs/change-tracking/change-tracking-introduction/#start-tracking) for alternative deployment tracking options.
Related to #3259

Deprecate `newrelic deployments` CLI command

---

CHANGELOG.md

Add announcements for upcoming removals in version 10:
* Ruby 2.4
* Ruby 2.5
* Cross application tracing (CAT)
Closes #3273

Add notices for Ruby 2.4, 2.5 and CAT

---

.github/workflows/prerelease.yml

GITHUB_TOKEN may let us add labels again. Though the bot token was helpful to get the CI to run automatically...
See: https://github.com/newrelic/newrelic-ruby-agent/pull/3161

Revert token change for prerelease workflow
