newrelic/newrelic-ruby-agent

.github/workflows/snyk.yml
Set up snyk to run every day at 7 UTC and when a pull request to the release branch is created
=> Run Snyk Action on schedule and on pull request

CONTRIBUTING.md, README.md
Improves the SUPPORT section of the README and adds a Version Support section to CONTRIBUTING.md
=> improvements to contributing and support sections

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/troubleshooting.md, .github/pull_request_template.md
Added issue templates for feature request, bug reports and troubleshooting requests
=> Add issue templates

.github/workflows/test.yml, test/new_relic/agent/transaction/segment_test.rb, test/new_relic/agent/transaction_test.rb
Simple test of working with Github actions
=> GitHub actions experiment

.github/workflows/ci.yml, .github/workflows/infinite_tracing_tests.yml, test/multiverse/suites/active_record/config/database.yml
- Multiverse tests set up to run
- Unit tests to run with all valid rails versions
- Added services needed for multiverse tests
- Runs on pushes to main or dev and on all pull requests
- Builds ruby versions before running any tests
- Moved infinite tracings tests to its own workflow due to instability in these tests
=> Setup services and unit tests for github actions

CONTRIBUTING.md, README.md
Updates the links to our support page to the new location
=> update support links

.github/workflows/pr_review_checklist.yml, .github/workflows/sidekick_checklist.yml
Adding a checklist for PR reviewers. Now using the newly minted `pull_request_target`!
=> Add PR review checklist

.github/workflows/release.yml, .github/workflows/scripts/ruby-gems-authenticate.rb
Adding a workflow to automate release tasks as part of our migration to GitHub actions. 🎉
=> Add workflow for release tasks

.github/workflows/release.yml
A small update to our automated release workflow.
=> Update gem credentials step

.github/workflows/release.yml, test/multiverse/suites/sidekiq/Envfile
Let's get [this fix to our release workflow](https://github.com/newrelic/newrelic-ruby-agent/pull/420) merged to main to kick off the release again.
=> Release workflow fix

.github/workflows/release.yml, CONTRIBUTING.md, newrelic_rpm.gemspec
Kicking off the release process again with another small fix to the workflow.
=> Dev to main for 6.13.0

.github/workflows/release.yml, .github/workflows/scripts/ruby-gems-authenticate.rb
Encodes apikey to base32 in the release workflow.
=> Update to release workflow for 6.13.0

.github/workflows/release.yml
Checks for the existence of the tag for the version before attempting to create the tag.
=> Release workflow update

.github/workflows/snyk.yml
Need to setup ruby before bundling because the included ruby doesn't have that
=> Fix for snyk workflow

.github/workflows/release.yml, .github/workflows/scripts/ruby-gems-authenticate.rb
Uses new github SECRETS and correct MFA/OTP handling to publish a new gem release. …
=> fixes rubygems mfa otp handling

.github/workflows/stale.yml
Updates the stale PR message to be more specific
=> Update stale PR message

lib/new_relic/version.rb
Updates the agent version to `6.14.0`.
=> update version to 6.14.0

.github/workflows/ci.yml, lib/new_relic/agent/instrumentation/active_record_helper.rb, lib/new_relic/agent/instrumentation/active_record_prepend.rb, lib/new_relic/agent/instrumentation/acts_as_solr.rb, lib/new_relic/agent/instrumentation/bunny.rb, lib/new_relic/agent/instrumentation/curb.rb, lib/new_relic/agent/instrumentation/delayed_job_instrumentation.rb, lib/new_relic/agent/instrumentation/padrino.rb, lib/new_relic/agent/instrumentation/rack.rb, lib/new_relic/agent/instrumentation/rake.rb, lib/new_relic/agent/instrumentation/redis.rb, lib/new_relic/agent/instrumentation/sinatra.rb, test/multiverse/lib/multiverse/runner.rb, test/multiverse/suites/active_record/Envfile, test/multiverse/suites/activemerchant/Envfile, test/multiverse/suites/capistrano/Envfile, test/multiverse/suites/padrino/Envfile, test/multiverse/suites/rails/Envfile, test/multiverse/suites/rails_prepend/Envfile, test/multiverse/suites/sequel/Envfile, test/multiverse/suites/sidekiq/Envfile
* Added ruby version 3.0.0-preview1 to our testing matrix.
* Added exclusions for incompatible suites with ruby 3.0 
* Removed incompatible gem versions from env files in multiverse for ruby 3.0
* Added new versions of several gems in multiverse
closes #488 
closes #490
closes #516
=> Add Ruby 3.0 to CI

infinite_tracing/newrelic-infinite_tracing.gemspec
=> update to gRPC 1.34.0

test/agent_helper.rb
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/tes …
=> update the test helper to avoid building error attributes once frozen.

CHANGELOG.md, lib/new_relic/version.rb
Bumps the version and updates the changelog
closes #533
=> Update version and changelog for 6.15.0

CHANGELOG.md
Saw these being introduced in recent dependency diffs.
=> CHANGELOG: Fix typos

lib/new_relic/supportability_helper.rb, test/new_relic/supportability_helper_test.rb
=> fixes typo in valid_api_argument_class? method

.github/workflows/ci.yml
=> add nightly build at 6 and 8

.github/actions/build-ruby/dist/index.js, lib/new_relic/agent/instrumentation/httpclient.rb, lib/new_relic/agent/instrumentation/httpclient/chain.rb, lib/new_relic/agent/instrumentation/httpclient/instrumentation.rb, lib/new_relic/agent/instrumentation/httpclient/prepend.rb
Provides a DRY implementation shared between CHAIN and PREPEND implementations
=> Dry prepend httpclient

infinite_tracing/newrelic-infinite_tracing.gemspec, newrelic_rpm.gemspec
Added Aaron Huntsman as author in gemspecs. Removed Rachel Klein from authors. …
=> add Aaron Huntsman to gemspec authors

infinite_tracing/CHANGELOG.md, infinite_tracing/lib/infinite_tracing/client.rb, infinite_tracing/lib/infinite_tracing/connection.rb
This is an attempt to fix the related issue of infinite tracing causing no data to send.
closes https://github.com/newrelic/newrelic-ruby-agent/issues/628
=> Bugfix for Infinite Tracing not sending data

CHANGELOG.md, lib/new_relic/version.rb
Bumps the version number to 7.0.0.
=> Bump to 7.0.0

lib/new_relic/agent/configuration/default_source.rb, lib/tasks/config.html.erb, lib/tasks/config.rake
Our documentation is now an open source project and the configuration page in particular has a new Markdown syntax.
This PR implements the new rendering for the new documentations website.
=> Updates the documentation renderer for configuration page

CHANGELOG.md
This PR just adds changelog entries for the community PR's we have merged recently.
=> Add changelog entries for community PRs

CONTRIBUTING.md
Added a short setup guide to the ruby agent contributing guide to give people an idea of how to set it up. If we want to update these instructions or expand them, please let me know. I had to make these up, because there weren't any install instructions that I could find in the README, Contrib guide, or the Ruby Agent documentation site.
Also fixed broken link.
and [here …
=> Updated Contributing Guide

lib/new_relic/version.rb
Updates the version number to 7.1.0 to prepare for our upcoming release
=> Update version to 7.1.0 for upcoming release

lib/new_relic/version.rb
Bumps the version to 7.2.0 for our upcoming release.
=> bump version for 7.2.0

infinite_tracing/newrelic-infinite_tracing.gemspec, newrelic_rpm.gemspec
Add Kayla Reopelle, new member of the Ruby Agent team, to the authors …
=> Add Kayla to authors

.github/workflows/ci.yml
=> Bump CI Ruby versions to latest

.gitignore, newrelic.yml
This PR addresses issue #684. We used the current documentation for the *newrelic.yml* file on the New Relic website, and inserted all of the non-deprecated configuration options, alphabetized, with documentation, into the config file template.
`newrelic install` will now install a *Devise* style, well-documentated configuration file.
#684 
We confirmed that the generated config file has all of the same uncommented sections that the old, much shorter version has. So there should be no operational effect to using this longer version.
=> Kh.expand config file generation to improve documentation

.github/workflows/ci.yml, CHANGELOG.md, lib/new_relic/agent/configuration/default_source.rb, lib/new_relic/agent/configuration/event_harvest_config.rb, lib/new_relic/agent/configuration/server_source.rb, test/multiverse/suites/agent_only/event_data_collection_test.rb, test/multiverse/suites/high_security/high_security_test.rb, test/multiverse/suites/mongo/mongo2_instrumentation_test.rb, test/multiverse/suites/rack/nested_non_rack_app_test.rb, test/multiverse/suites/rack/puma_rack_builder_test.rb, test/multiverse/suites/rack/rack_auto_instrumentation_test.rb, test/multiverse/suites/rack/url_map_test.rb, test/multiverse/suites/redis/redis_instrumentation_test.rb, test/multiverse/suites/sinatra/sinatra_metric_explosion_test.rb, test/new_relic/agent/configuration/event_harvest_config_test.rb, test/new_relic/agent/configuration/server_source_test.rb, test/new_relic/agent/instrumentation/task_instrumentation_test.rb, test/new_relic/agent/messaging_test.rb, test/new_relic/agent/method_tracer/instance_methods/trace_execution_scoped_test.rb, test/new_relic/agent/transaction/external_request_segment_test.rb, test/new_relic/agent/transaction/message_broker_segment_test.rb, test/new_relic/agent/transaction_sampler_test.rb, test/new_relic/agent/transaction_test.rb, test/new_relic/http_client_test_cases.rb, test/new_relic/marshalling_test_cases.rb
* Turn on distributed tracing by default 
* Increase `span_events.max_samples_stored` default value from 1000 to 2000
* Update connect cycle to incorporate latest agent specs span event harvest data definitions
Closes: https://github.com/newrelic/newrelic-ruby-agent/issues/755 
Closes: https://github.com/newrelic/newrelic-ruby-agent/issues/550
Github Actions when a pull request is made. More details on …
=> Update connect cycle 

CHANGELOG.md, lib/new_relic/version.rb
Bumps the version to 8.0.0 for our upcoming release
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/ …
=> Bump version to 8.0.0

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Updated the templates to add bug or feature labels to simplify triaging. …
=> Update the Github Issue template to auto label bug or feature

README.md
I noticed the title for Lew Cirne is no longer accurate at the bottom of our README and wanted to adjust it. 
None
=> Update title on README

lib/new_relic/agent/configuration/default_source.rb, lib/new_relic/agent/instrumentation/tilt.rb, lib/new_relic/agent/instrumentation/tilt/chain.rb, lib/new_relic/agent/instrumentation/tilt/instrumentation.rb, lib/new_relic/agent/instrumentation/tilt/prepend.rb, newrelic.yml, test/multiverse/suites/tilt/Envfile, test/multiverse/suites/tilt/config/newrelic.yml, test/multiverse/suites/tilt/tilt_instrumentation_test.rb
Adds files for Tilt instrumentation, configuration, and multiverse testing.
Closes: #833 
Old PR: https://github.com/newrelic/newrelic-ruby-agent/pull/840
=> [TILT-1] Create structure for tilt instrumentation

CHANGELOG.md, lib/new_relic/version.rb
This pr bumps the version and adds any missing entries to the changelog
Closes: #838
=> Bump version for 8.2.0

newrelic.yml
Delete duplicate settings in newrelic.yml
https://github.com/newrelic/newrelic-ruby-agent/issues/849
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/mult …
=> Delete duplicate settings

infinite_tracing/newrelic-infinite_tracing.gemspec, newrelic_rpm.gemspec, test/environments/rails60/Gemfile
Update author's list
N/A
For most contributions it is strongly recommended to add …
=> Update Author's List

lib/new_relic/agent/instrumentation/notifications_subscriber.rb
mini change to fix typo. no functionality added.
=> fixing bracket typo syntax error

.github/workflows/ci.yml, CHANGELOG.md, test/multiverse/suites/grape/Envfile, test/multiverse/suites/rails/Envfile
updates our CI to 3.1.0, from 3.1.0-preview1
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/mu …
=> Update CI to official release of 3.1.0

lib/new_relic/agent/configuration/default_source.rb, test/multiverse/suites/rails/rails3_app/app_rails3_plus.rb, test/multiverse/suites/rails_prepend/Envfile
The development.log output when running the `test/multiverse/suites/rails/middleware_instrumentation_test.rb` file included the error: `ArgumentError (Before process_action callback :verify_authenticity_token has not been defined)`. Defining `:verify_authenticity_token` resolved the error and allowed the tests to run. [`application/javascript` content types are invalid when authenticity tokens are included](https://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html#method-i-verify_same_origin_request), so an exclusion was required for the …
=> Bugfix: Update middleware instrumentation for Rails 7.0

lib/new_relic/version.rb
PR to increase the version for 8.3.0. Looking at the PRs for this version, it did not seem like anything needed to be added to the CHANGELOG.
and …
=> Bump version to 8.3.0

.github/workflows/release.yml, .github/workflows/snyk.yml
The [setup-ruby](https://github.com/ruby/setup-ruby) GitHub Action used in the Snyk and Release jobs was out of date. The latest version, which includes Ruby 3.1, will now be installed.
N/A
and [here for …
=> Update setup-ruby version on actions

.github/workflows/label_community_cards.yml
=> Added conditions for PR

.github/actions/build-ruby/dist/index.js, .github/actions/build-ruby/index.js
enable YJIT via the env var for Ruby 3.1+
=> use YJIT for tests

CHANGELOG.md
=> CHANGELOG typo fix

.github/workflows/ci.yml, .rubocop.yml, lib/new_relic/agent/instrumentation/active_job.rb, lib/new_relic/agent/messaging.rb, lib/new_relic/agent/method_tracer.rb, test/new_relic/agent/hostname_test.rb, test/new_relic/agent/pipe_channel_manager_test.rb
Runs rubocop first before continuing with all the test suites …
=> Add rubocop step to run first in ci.yml

.github/actions/build-ruby/dist/index.js, .github/actions/build-ruby/index.js
* don't attempt to install v1.17.3 over itself
* always use `--force`
=> Ci bundler fixes

CHANGELOG.md
* reorder v8.5.0 changelog to list general, then bugs, then commit
* added missing period
=> v8.5.0 CHANGELOG reordering

test/test_helper.rb
leverage `minitest/pride` for colorful output
=> leverage minitest/pride

.github/workflows/ci.yml
perform continuous integration against the latest stable JRuby
=> CI: target JRuby 9.3.4.0

lib/new_relic/agent/configuration/default_source.rb, lib/new_relic/agent/instrumentation/active_support_logger.rb, lib/new_relic/agent/instrumentation/active_support_logger/chain.rb, lib/new_relic/agent/instrumentation/active_support_logger/instrumentation.rb, lib/new_relic/agent/instrumentation/active_support_logger/prepend.rb, lib/new_relic/agent/instrumentation/logger.rb, newrelic.yml, test/multiverse/suites/rails/active_support_logger_test.rb
Somehow this got merged, but the code is no longer in the `logging-initiative-ga` branch!
=> Logging: Duplicate logs in Rails development

CHANGELOG.md, lib/new_relic/version.rb
Bumps the version for the upcoming release, and adds to the changelog …
=> Bump version to 8.6.0

Rakefile, test/environments/rails32/config/boot.rb, test/environments/rails40/config/boot.rb, test/environments/rails41/config/boot.rb, test/environments/rails42/config/boot.rb, test/environments/rails50/config/boot.rb, test/environments/rails51/config/boot.rb, test/environments/rails52/config/boot.rb, test/environments/rails60/config/boot.rb, test/environments/rails61/config/boot.rb, test/multiverse/lib/multiverse/runner.rb, test/multiverse/suites/mongo/helpers/mongo_server.rb, test/multiverse/suites/mongo/helpers/mongo_server_test.rb
File.exists has been deprecated for quite awhile and will be dropped in
favor of File.exist entirely with Ruby 3.2
=> update File.exists to File.exist

lib/new_relic/agent/instrumentation/action_controller_subscriber.rb, lib/new_relic/agent/method_tracer_helpers.rb, lib/new_relic/agent/transaction.rb
* Simplify the process of obtaining source code location info so that
class instances are not re-instantiated
* Record method level telemetry for Rails controller methods as there
operation is recorded
=> method level telemetry: initial Rails support

lib/new_relic/agent/instrumentation/notifications_subscriber.rb, lib/new_relic/agent/method_tracer_helpers.rb, lib/new_relic/agent/span_event_primitive.rb, lib/new_relic/agent/transaction/abstract_segment.rb
* record supportability metrics
* report code.* attributes
* include the class name in the namespace
=> method level telemetry updates

lib/new_relic/agent/method_tracer_helpers.rb, lib/new_relic/agent/transaction/abstract_segment.rb, test/new_relic/agent/instrumentation/rails/action_controller_subscriber.rb, test/new_relic/agent/method_tracer_helpers_test.rb, test/new_relic/agent/method_tracer_test.rb, test/new_relic/agent/span_event_primitive_test.rb, test/new_relic/agent/transaction/abstract_segment_test.rb
* MLT related attribute name typo fix
* Add support for determining location information for anonymous classes
* MLT related unit tests
=> Unit tests for mlt

CHANGELOG.md, lib/new_relic/version.rb, test/multiverse/suites/memcache/Envfile
* Adds changelog entry for logs-in-context 
* Bumps version to 8.7.0
N/A
=> 8.7.0 Version bump

CHANGELOG.md, lib/new_relic/control/instrumentation.rb
* Deprecate Ruby 2.2 
* Deprecate Rails 3.2
* Add entry for constant changes in CHANGELOG
=> Deprecate Ruby 2.2 and Rails 3.2

.github/workflows/label_community_cards.yml, infinite_tracing/newrelic-infinite_tracing.gemspec, newrelic_rpm.gemspec
Add Hannah as gem author and remove community label from Hannah issues.
=> Add Hannah as gem author

test/multiverse/suites/padrino/padrino_test.rb
enhance our padrino testing to confirm `#invoke_route_with_tracing` is
executed
=> improve padrino testing

newrelic_rpm.gemspec
Removes the post install message that was added for our 8.7.0 release.  …
=> Remove post install message

CHANGELOG.md
mlt/clm changelog entry for 8.8.0
=> 8.8.0 changelog entry for CLM

CHANGELOG.md, lib/new_relic/version.rb
Update minor release version and changelog.
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/mul …
=> Update minor version for release 8.8.0

test/new_relic/agent/pipe_channel_manager_test.rb
rework the PipeChannelManager test for verifying that an
`IO::WaitReadable` based exception will be rescued properly
=> rework PipeChannelManager test for nonblock

lib/new_relic/agent/agent_logger.rb, lib/new_relic/agent/autostart.rb, lib/new_relic/agent/configuration/default_source.rb, lib/new_relic/agent/configuration/manager.rb, lib/new_relic/agent/connect/request_builder.rb, lib/new_relic/agent/instrumentation/active_record_helper.rb, lib/new_relic/agent/pipe_service.rb, lib/new_relic/agent/sql_sampler.rb, lib/new_relic/agent/transaction/transaction_sample_buffer.rb, lib/new_relic/agent/transaction_sampler.rb
Replace [] with constant EMPTY_ARRAY where appropriate (not being mutated.)
Related to #974
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/RE …
=> Replace calls to empty arrays with constant

lib/new_relic/agent/system_info.rb, test/new_relic/agent/system_info_test.rb, test/new_relic/license_test.rb
Refactor `get_processor_info` for length and clarity.
For …
=> refactor processor info

lib/new_relic/agent/agent.rb, lib/new_relic/agent/agent/shutdown.rb, lib/new_relic/agent/agent/special_startup.rb, lib/new_relic/agent/agent/start_worker_thread.rb, lib/new_relic/agent/agent/startup.rb, test/new_relic/agent/agent/start_test.rb, test/new_relic/agent/agent/start_worker_thread_test.rb
Spent some time on a refactor for Agent::Agent, but didn't finish up moving everything around yet. It is small refactor, but still an improvement in breaking out the huge file into smaller sections.
#999 
[here for our unit tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/README.md), …
=> Partial refactor for NewRelic::Agent::Agent

.github/workflows/ci.yml, test/multiverse/suites/active_record_pg/Envfile, test/multiverse/suites/bunny/Envfile, test/multiverse/suites/delayed_job/Envfile, test/multiverse/suites/delayed_job/before_suite.rb, test/multiverse/suites/memcache/Envfile, test/multiverse/suites/mongo/Envfile, test/multiverse/suites/net_http/Envfile, test/multiverse/suites/rack/Envfile, test/multiverse/suites/rake/Envfile, test/multiverse/suites/redis/Envfile, test/multiverse/suites/resque/Envfile, test/multiverse/suites/sidekiq/Envfile, test/multiverse/suites/sidekiq/sidekiq_instrumentation_test.rb, test/multiverse/suites/sinatra/Envfile, test/multiverse/suites/tilt/Envfile
Adds an unspecified gem install Gemfile entry to the multiverse suite Envfiles of Core Technologies.
Closes: #1183
This ticket is about expanding the versions tested by our multiverse suites. No tests need to be added.
=> Test unpinned gem version of core technologies

.github/ISSUE_TEMPLATE/bug_report.md
Updating the bug template so that we enter suggested Priority when creating bugs if you are a maintainer or when Hero Triages a community ticket.
- [n/a] Include a link to the related GitHub issue, if applicable
- [n/a] Include a security review link, if applicable
For most contributions it …
=> Updated Bug issue template per new NR guidance

.github/workflows/ci.yml, .github/workflows/ci_cron.yml
JRuby 9.3.4.0 -> 9.3.6.0 for CI
=> use JRuby 9.3.6.0 for CI

newrelic.yml
I found a typo in `newrelic.yml` and fixed it.
The correct name was not `browser_monitoring_attributes` in `newrelic.yml`, but `browser_monitoring.attributes` in the [official documentation](https://docs.newrelic.com/docs/data-apis/custom-data/custom-events/report-browser-monitoring-custom-events-attributes/#custom-attribute-forward-apm).
Github Actions when a pull request is made. …
=> Fixed typo of option name

.github/workflows/ci.yml
simplecov - only run on the NR repo
=> CI: don't run simplecov against forks

test/environments/rails70/Gemfile, test/multiverse/suites/rails/Envfile, test/multiverse/suites/rails_prepend/Envfile
CI: update Rails in tests from 7.0.2.x to 7.0.3.x
=> CI: test against Rails 7.0.3.1

.snyk
add project `.snyk` file, ignoring `Dockerfile`
=> add .snyk file

lib/new_relic/agent/transaction/distributed_tracer.rb, test/agent_helper.rb, test/multiverse/suites/grpc/Envfile, test/multiverse/suites/grpc/grpc_client_test.rb
* Add `dt_enabled?` helper to DistributedTracer class 
* Add two new dt-related assertions: 
*  `assert_newrelic_metdata_present`
* assert_distributed_tracing_payload_created_for_transaction(transaction)'
* Refactor some of the repeated code in our tests into constants and helpers
* Break out tests for: 
* error segment 
* DT headers
* span attributes
* metric name
* possibly others that I'm forgetting
=> More gRPC Client Tests! 

.github/workflows/gem_notifications.yml, .github/workflows/scripts/slack_gem_notifications/README.md, .github/workflows/scripts/slack_gem_notifications/cve_methods.rb, .github/workflows/scripts/slack_gem_notifications/cve_script.rb, .github/workflows/scripts/slack_gem_notifications/notifications_script.rb, test/new_relic/gem_notifications_tests.rb
This PR enables gabbi to notify the team of Ruby CVEs, as reported by rubysec.com. Running on the same 24-hour cycle as when we get gem version update notifications, the addition of a CVE script checks the rubysec XML feed for Ruby security vulnerability updates and sends a Slack message to our dev-notifications channel.
closes #1281
Updates include:
- Addition of a `cve_methods.rb` file and related tests in `gem_notifications_tests.rb`
- Expansion of `gem_notifications.yml` to run a new job/script: `cve_script.rb`
Describe the changes present in the pull …
=> gabbi checks for Ruby CVEs

test/performance/Gemfile, test/performance/suites/trace_context.rb
This commit adds missing minitest requirements where there were performance testing failures. …
=> Add missing minitest requirements

test/test/test_helper_test.rb
now that `test/test_helper.rb` has started to contain methods, let's set
up tests for it
=> add tests for methods in test/test_helper.rb

test/multiverse/suites/config_file_loading/Envfile, test/multiverse/suites/rails/view_instrumentation_test.rb
Frozen strings in the test ViewsController were causing failures, made the
strings mutable that need to be
Frozen strings in the test ViewController caused errors that caused several tests to fail because the controller action was failing. These 4 strings were the cause of all the failures, I was able to confirm locally that 2.3.8 no longer fails on these tests. 
See failures here: https://github.com/newrelic/newrelic-ruby-agent/runs/7648494987?check_suite_focus=true
In addition to this, a new version of 'jar-dependencies' gem was released today. This is a …
=> Fix for multiple multiverse failures

CHANGELOG.md
update the 8.10 notes to mention gRPC
=> CHANGELOG entry for gRPC instrumentation

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, test/multiverse/suites/rack/puma_rack_builder_test.rb
Turns off fail fast for the scheduled CI and fixes an intermittent puma rack failures. Sometimes rack will generate some metrics that we aren't checking for, so now we exclude metrics that match these, by ignoring Proc.
```
Controller/Rack/Proc/call (<unscoped>),
WebTransactionTotalTime/Controller/Rack/Proc/call (<unscoped>),
Apdex/Rack/Proc/call (<unscoped>)
```
Github Actions …
=> Fix multiverse some more

lib/new_relic/version.rb
=> bump version to 8.10.0

CHANGELOG.md, test/multiverse/suites/rack/puma_rack_builder_test.rb
Fix for the regex to ignore Rack/Proc metrics that rack generates inconsistently.
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/mu …
=> Fix puma rack intermittent failure

.github/workflows/ci.yml, .github/workflows/ci_cron.yml
=> CI: JRuby 9.3.7.0

lib/new_relic/agent/datastores/metric_helper.rb, lib/new_relic/agent/datastores/mongo/metric_translator.rb, lib/new_relic/agent/distributed_tracing/distributed_trace_payload.rb, lib/new_relic/agent/instrumentation/queue_time.rb, lib/new_relic/agent/span_event_primitive.rb, lib/new_relic/agent/transaction.rb, lib/new_relic/agent/transaction/transaction_sample_buffer.rb
For #1130
For most contributions it is strongly recommended …
=> Remove orphaned constants

test/multiverse/suites/bunny/Envfile
Bunny's Envfile did not have chain enabled as a tested instrumentation method. Let's turn it back on!
=> Add chain back to instrumentation_methods for Bunny

.github/workflows/ci.yml, .github/workflows/ci_cron.yml
=> CI: JRuby 9.3.8.0

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/scripts/setup_bundler_multiverse, newrelic_rpm.gemspec, test/environments/norails/Gemfile, test/multiverse/lib/multiverse/suite.rb, test/multiverse/suites/agent_only/Envfile, test/multiverse/suites/rack/Envfile
- limits minitest version to 4.7.5 when on < 2.7
- only install rubocop when on > 2.5 
- updated jruby multiverse to run on ubuntu 22 in ci_cron, since that is what it's using in the pr ci
- added set gem to install 1.03 on ruby 2.7+ to prevent activating different versions
- added 2.7 to install strscan 3.0.4 to prevent activating different versions
- fixes rack envfile to only call create_gemfiles once
- prevents puma rack tests from running on 3.2.0-preview2 (https://github.com/newrelic/newrelic-ruby-agent/issues/1446) …
=> Revert minitest version to 4.7.5 on older ruby versions + resolve other misc CI issues

.rubocop.yml, lib/new_relic/agent/configuration/dotted_hash.rb, lib/new_relic/agent/configuration/environment_source.rb, lib/new_relic/agent/configuration/yaml_source.rb, lib/new_relic/agent/connect/response_handler.rb, lib/new_relic/agent/new_relic_service.rb, lib/new_relic/agent/transaction.rb, lib/new_relic/language_support.rb, test/agent_helper.rb, test/multiverse/suites/agent_only/synthetics_test.rb, test/new_relic/marshalling_test_cases.rb
Turns on four previously disabled cops: 
* Style/MultilineTernaryOperator
* Style/NilComparison
* Style/NonNilCheck
* Style/OrAssignment
=> Enable four new Style cops

.rubocop.yml, test/multiverse/suites/padrino/Envfile, test/multiverse/suites/rack/rack_builder_test.rb
raise code coverage for rack instrumentation to 100% line and 100% branch
=> test coverage: get rack instrumentation to 100%

test/multiverse/suites/rack/rack_builder_test.rb
CI cron workflow failed on merge due to `encoding: utf-8` comment's presence.
=> Remove encoding magic comment

.rubocop_todo.yml, test/multiverse/suites/agent_only/log_events_test.rb
Address `Minitest/AssertNil` and remove from `rubocop_todo`
=> Address AssertNil offenses

.rubocop_todo.yml, test/multiverse/suites/datamapper/datamapper_test.rb, test/multiverse/suites/grpc/grpc_server_test.rb, test/multiverse/suites/mongo/helpers/mongo_operation_tests.rb, test/multiverse/suites/mongo/mongo2_instrumentation_test.rb, test/multiverse/suites/rack/rack_cascade_test.rb, test/new_relic/agent/configuration/manager_test.rb, test/new_relic/control/instance_methods_test.rb
Address `Minitest/RefuteIncludes` and remove from `rubocop_todo`
=> Address Minitest/RefuteIncludes

.rubocop_todo.yml
for now, let's TODO our ABC size violations outside of the tests
=> RuboCop: scope ABC size concerns to non tests

lib/new_relic/agent/agent.rb
break large methods up into smaller pieces to keep ABC size down
=> agent.rb: address ABC size issues

lib/new_relic/environment_report.rb
=> Refactor EnvironmentReport for Rubocop Metrics/AbcSize

lib/new_relic/control/instance_methods.rb, lib/new_relic/control/private_instance_methods.rb
=> Refactor NewRelic::Control::InstanceMethods

lib/tasks/instrumentation_generator/instrumentation.thor
=> Refactor instrumentation.thor to adhere to Rubocop Metrics/AbcSize

.github/workflows/scripts/slack_notifications/gem_notifier.rb, test/new_relic/slack_notifications_tests/gem_notifier_tests.rb
Fix method return URL and add test for valid GitHub diff URLs.
=> Fix method return url and add test

.rubocop_todo.yml, test/multiverse/suites/sequel/sequel_plugin_test.rb, test/multiverse/suites/sinatra_agent_disabled/shim_test.rb, test/new_relic/agent/configuration/default_source_test.rb, test/new_relic/collection_helper_test.rb, test/new_relic/data_container_tests.rb
Address `Minitest/AssertRespondTo` and remove from `rubocop_todo`
=> Address Minitest/AssertRespondTo

lib/new_relic/rack/browser_monitoring.rb
=> Refactor BrowserMonitoring for AbcSize

.github/workflows/scripts/slack_notifications/gem_notifier.rb, test/new_relic/slack_notifications_tests/gem_notifier_tests.rb
`github_diff` should be`github_diff_exist` so that the variable is used vs the method. This has been updated.
=> Update variable name

.rubocop_todo.yml, infinite_tracing/newrelic-infinite_tracing.gemspec, infinite_tracing/test/support/fixtures.rb, test/multiverse/lib/multiverse/suite.rb, test/multiverse/suites/mongo/helpers/mongo_server_test.rb
Address Assert/ RefutePathExists
=> Address Assert/ RefutePathExists changes

CHANGELOG.md
* Fix bolding of the bugfix
* Standardize formatting across the 2 entries for this release for referencing PRs and community members
=> v8.11 CHANGELOG.md updates

lib/new_relic/version.rb
set the agent version to 8.11.0
=> bump version to 8.11.0

lib/new_relic/agent/database.rb, lib/new_relic/agent/instrumentation/elasticsearch/chain.rb, lib/new_relic/agent/instrumentation/elasticsearch/instrumentation.rb, test/multiverse/suites/elasticsearch/Envfile, test/multiverse/suites/elasticsearch/elasticsearch_instrumentation_test.rb
=> Elasticsearch tests

.github/workflows/performance_tests.yml
use markdown instead of plaintext for the perf test results
=> perf tests: use markdown

CHANGELOG.md
get the CHANGELOG ready for v8.12.0
=> prep CHANGELOG for v8.12.0

Brewfile, test/multiverse/README.md
Update `Brewfile` and related documentation for Elasticsearch
=> Homebrew updates for Elasticsearch

lib/new_relic/agent/configuration/default_source.rb, test/new_relic/agent/logging_test.rb
=> Add fixes for Style/RedundantStringEscape

CHANGELOG.md
=> CHANGELOG 8.12.0

lib/new_relic/version.rb
=> Bump 8.11.0 -> 8.12.0

.github/workflows/ci.yml, .github/workflows/ci_cron.yml
=> CI: Test with JRuby 9.3.9.0

lib/tasks/instrumentation_generator/README.md, lib/tasks/instrumentation_generator/TODO.md
After our discussion about including instrumentation generator improvements in our Q4 plans, I decided to look over the documentation and TODOs for this tool. This PR has the updates.
=> Update instrumentation generator README and TODOs

lib/new_relic/agent/parameter_filtering.rb, test/multiverse/suites/sidekiq/Envfile, test/new_relic/agent/parameter_filtering_test.rb
Return params if the RAILS_FILTER_CLASS is undefined or nil
=> Return params if undefined or nil

test/multiverse/suites/redis/Envfile, test/multiverse/suites/redis/redis_instrumentation_test.rb
=> CI test redis v5

test/multiverse/suites/agent_only/key_transactions_test.rb, test/new_relic/agent/log_priority_test.rb, test/new_relic/agent/logging_test.rb, test/new_relic/agent/priority_sampled_buffer_test.rb, test/new_relic/agent/stats_engine/gc_profiler_test.rb, test/new_relic/agent/transaction/trace_node_test.rb, test/new_relic/agent/transaction_time_aggregator_test.rb, test/new_relic/agent_test.rb, test/new_relic/cli/commands/deployments_test.rb
=> Address rubocop Minitest/EmptyLineBeforeAssertionMethods offenses

CHANGELOG.md
start the v8.13.0 `CHANGELOG.md` section
=> changelog entry for v8.13.0

test/multiverse/suites/rack/Envfile
with the recent Rack v3 changes that have taken place, things seem to work with Ruby 3.2.0 now
=> resume testing Rack/Puma with Ruby 3.2.0

lib/new_relic/agent/instrumentation/sidekiq.rb, lib/new_relic/agent/instrumentation/sidekiq/client.rb, lib/new_relic/agent/instrumentation/sidekiq/extensions/delayed_class.rb, lib/new_relic/agent/instrumentation/sidekiq/server.rb
In addition, the class names have been updated to reflect their locations
=> Move Sidekiq classes into their own files

newrelic_rpm.gemspec, test/environments/norails/Gemfile, test/environments/rails32/Gemfile, test/environments/rails40/Gemfile, test/environments/rails41/Gemfile, test/environments/rails42/Gemfile, test/environments/rails50/Gemfile, test/environments/rails51/Gemfile, test/environments/rails52/Gemfile, test/environments/rails60/Gemfile, test/environments/rails61/Gemfile, test/environments/rails70/Gemfile, test/environments/railsedge/Gemfile, test/multiverse/lib/multiverse/suite.rb, test/multiverse/suites/active_record/ar_method_aliasing.rb, test/multiverse/suites/active_record_pg/ar_method_aliasing.rb
=> dev/CI Gemfiles: latest stable 1.x mocha

CHANGELOG.md
=> Fix changelog formatting for 8.13.0

lib/new_relic/version.rb
Update version constant for 8.13.0 release 
=> Update version constant for 8.13.0 release

CHANGELOG.md
This word refers to a required argument within a method.
cc @hannahramadan 
=> Update formatting for `:category`

README.md
Removed the line referencing the issue that @tannalynn recently resolved around the API keys and recording deploys.
- [N/A] Include a link to the related GitHub issue, if applicable
- [N/A] Include a security review link, if applicable
Readme file edited and previewed.
=> Removed text on the issue of recording deploys

lib/new_relic/version.rb
Update version constant to 8.13.1 ahead of release.
=> Update version constant 8.13.1

.github/workflows/ci.yml
following the success of making this change to `ci_cron.yml`, let's update `ci.yml` as well
=> CI: allow the PR tests to be dispatched manually

.github/workflows/ci.yml, .github/workflows/ci_cron.yml
=> CI: use JRuby with the default Ubuntu Java

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, test/multiverse/suites/config_file_loading/Envfile, test/multiverse/suites/high_security/high_security_test.rb, test/multiverse/suites/rails/error_tracing_test.rb, test/multiverse/suites/rails/parameter_capture_test.rb, test/multiverse/suites/rake/rake_test.rb, test/new_relic/transaction_ignoring_test_cases.rb
v9.4.1.0 will fix all of this, surely
=> CI: revert to JRuby v9.3.9.0, additional JRuby skips, Psych v5 TODO

.github/workflows/ci_cron.yml, test/multiverse/suites/grpc/Envfile
... So this is 3.2
And what has been done?
Another year over
And a new one just begun
And so this is 3.2
I hope you have fun
The devs and the hobbyists
The old timers and noobs
... A very Merry Ruby Release
And a Happy New Year
Let's hope it's a good one
Without any tears
... And so this is 3.2 (ooh)
For WASI based Wasm (ooh)
For large and small projects (ooh)
This release should be awesome (ooh)
And so happy 3.2 (a new release is here)
For CRuby and JRuby (if you've got Java)
For Truffle and Rubinius (use what you like)
Let's all get moving (now)
... A very Merry Ruby Release
And a Happy New Year
Let's hope it's a good one
Without any tears
... And so this is 3.2 (ooh)
For improved regex with timeouts (ooh)
For error highlights and suggestions (ooh)
And better performance no doubt (ooh) …
=> CI: test with Ruby 3.2.0-RC1

CHANGELOG.md
Sadly, my code editor is making decisions about some markdown files for me. Since I can't find the cause, I hope the team
is willing to obey its wishes so I can resume writing entries.
=> Lint CHANGELOG

CONTRIBUTING.md
update the slack invite link
For most contributions it is …
=> docs: update slack invite link

CHANGELOG.md, test/new_relic/agent/guid_generator_test.rb
* add tests for PR 1693
* add CHANGELOG entry for 1693
=> tests and CHANGELOG entry for 1693

.rubocop.yml, .rubocop_todo.yml
Disable rubocop [Style/ConcatArrayLiterals](https://docs.rubocop.org/rubocop/cops_style.html#styleconcatarrayliterals)
=> Disable Style/ConcatArrayLiterals

.github/workflows/scripts/slack_notifications/cve_notifier.rb, .github/workflows/scripts/slack_notifications/slack_notifier.rb, .rubocop.yml
- Remove unnecessary `text:` from json message
- add puts statements for debugging help
=> Gabbi testing updates + text fix

CHANGELOG.md, lib/new_relic/version.rb
* Increment version for upcoming release
* Update the CHANGELOG heading from upcoming release to 8.15.0
* Add entry for Padrino/Sinatra 3
* Add workflow_dispatch to performance test CI action
* Our release process says to run perf tests first, this will let that happen.
For most …
=> Prepare for 8.15.0

.github/workflows/performance_tests.yml
This will allow perf tests to run on demand
=> Add workflow_dispatch to performance tests

CHANGELOG.md
This PR adds the summary to the 8.15.0 changelog entry
=> Add overview paragraph to CHANGELOG

lib/new_relic/agent/instrumentation/active_support_subscriber.rb, test/new_relic/agent/instrumentation/rails/active_support_subscriber.rb
Fixes the failures in the unit env tests on dev
Link to passing run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/3971311601
=> Updates active support cache instrumentation for older rails versions

.github/workflows/ci_cron.yml
=> Skip slack notification if CI is manually triggered

CHANGELOG.md, lib/new_relic/agent/configuration/default_source.rb, lib/new_relic/agent/instrumentation/action_mailbox.rb, lib/new_relic/agent/instrumentation/action_mailbox_subscriber.rb, lib/new_relic/agent/instrumentation/action_mailer.rb, lib/new_relic/agent/instrumentation/action_mailer_subscriber.rb, lib/new_relic/agent/instrumentation/notifications_subscriber.rb, newrelic.yml, test/new_relic/agent/instrumentation/action_mailbox_subscriber_test.rb, test/new_relic/agent/instrumentation/action_mailer_subscriber_test.rb, test/new_relic/agent/instrumentation/rails/action_mailbox_subscriber.rb, test/new_relic/agent/instrumentation/rails/action_mailer_subscriber.rb
add Rails notifications based instrumentation support for ActionMailer and ActionMailbox
addresses #1513
=> ActionMailer and ActionMailbox instrumentation

lib/new_relic/agent/instrumentation/action_mailbox_subscriber.rb, lib/new_relic/agent/instrumentation/action_mailer_subscriber.rb, lib/new_relic/agent/instrumentation/action_view_subscriber.rb, lib/new_relic/agent/instrumentation/active_storage_subscriber.rb, lib/new_relic/agent/instrumentation/active_support_subscriber.rb, test/new_relic/agent/instrumentation/rails/action_mailer_subscriber.rb, test/new_relic/agent/instrumentation/rails/active_storage_subscriber.rb, test/new_relic/agent/instrumentation/rails/active_support_subscriber.rb
=> Use NewRelic::UNKNOWN const

CHANGELOG.md, lib/new_relic/version.rb
Release includes improvements to Rails instrumentation
=> Prepare for 8.16.0 release

CHANGELOG.md, lib/new_relic/agent/configuration/default_source.rb
* Vale linter found issues with CHANGELOG
* default_source descriptions changed by docs team in config file
=> 8.16.0: Update text to match docs-website

CHANGELOG.md
This adds the changelog entry listing all removed public configuration options and provides the replacement.
=> Removed configuration changelog

CHANGELOG.md
Create a section to shoutout our community member contributions for the next release
=> Community contribution CHANGELOG update

lib/new_relic/agent/monitors/cross_app_monitor.rb
Removing an orphaned constant
newrelic/newrelic-ruby-agent/issues/1130
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/RE …
=> Remove NEW_RELIC_ID_HEADER

README.md
Updated the coommunity header in the readme, as per the linter
github issue: https://github.com/newrelic/newrelic-ruby-agent/issues/1720 …
=> add community header to readme

CHANGELOG.md, test/new_relic/agent/instrumentation/active_record_helper_test.rb
for PR #1872
- add Timestream unit test
- add CHANGELOG entry
=> CHANGELOG entry and test accompaniment for 1872

.github/workflows/ci.yml
We're consistently hitting this coverage value. This will help us avoid dropping below it.
=> Increase failedThresholdBranch to 85

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/performance_tests.yml, .github/workflows/release.yml, .github/workflows/slack_notifications.yml, .github/workflows/snyk.yml
use the latest stable release of each Ruby
=> CI: use latest Ruby versions

.github/workflows/label_community_cards.yml, .github/workflows/release_notes.yml
Add permissions for two more actions.
=> Permission updates

.github/workflows/label_community_cards.yml, .github/workflows/release.yml
Re-releasing 9.2.0. The first run had both workflows that run on pushes to main fail due to issues with the actions. 
Resolves #1945 
=> Release 9.2.0, take 2

.github/workflows/scripts/generate_release_notes.rb
This commit incorporates changes made by a docs writer into our release note template.
=> Update release callout

lib/new_relic/agent/configuration/default_source.rb
Some changes have been made to our configs by docs-website editors since the last release. This PR puts our default source file back in sync.
Related to #1945
=> Update config descriptions to match docs-website

.github/workflows/release_notes.yml
Update action to use GH secrets
=> Email secrets

CHANGELOG.md
adds the changelog entry for the community PR https://github.com/newrelic/newrelic-ruby-agent/pull/1954
=> Add changelog entry for expected error community pr

CHANGELOG.md, lib/new_relic/version.rb
=> Bump version to 9.2.1

infinite_tracing/lib/infinite_tracing/transformer.rb, lib/new_relic/control/instrumentation.rb, test/warning_test_helper.rb
Clean up a few areas with conditionals related to Ruby 2.4
=> Remove Ruby < 2.4 constraints

lib/new_relic/agent/transaction.rb
=> Add save navigation to finished?

CHANGELOG.md, lib/new_relic/version.rb
* Adds CHANGELOG entry
* Increments tiny version number 
=> Bump agent version to 9.2.2

.github/workflows/assignproj.yml
Write permissions to projets doesn't seem to be working. Grant max write permissions.
=> Grant max write permissions

.github/workflows/assignproj.yml
=> Add steps back

.github/actions/simplecov-report/action.yml, .github/workflows/ci.yml
Since our codebase is now at 94.08% line coverage, let's make sure not to fall below 94% 🤠
=> Raise line test coverage threshold

.github/workflows/ci_cron.yml
use Ruby 3.3.0-preview1 in the CI tests
=> test Ruby 3.3

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/ci_jruby.yml, .github/workflows/performance_tests.yml, .github/workflows/release.yml, .github/workflows/release_notes.yml, .github/workflows/slack_notifications.yml, .github/workflows/snyk.yml
pin all instances of setup-ruby to v1.149.0
=> GHA: setup-ruby v1.149.0

test/new_relic/agent/method_tracer/instance_methods/trace_execution_scoped_test.rb
Todo fixed: https://github.com/newrelic/newrelic-ruby-agent/issues/1435
=> Remove addressed TODO

lib/new_relic/agent/configuration/default_source.rb, newrelic.yml
- Refactored `security.applicationinfo.port` to `security.application_info.port`
- Changed default value of `security.application_info.port` to `nil`
=> updated security config: application_info

lib/new_relic/control/security_interface.rb, test/new_relic/control/security_interface_test.rb
- add handling, security disable if high security enabled
- update unit_test security_interface_test for high_security config changes
=> add handling, security disable if high_security enabled

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/ci_jruby.yml
=> CI: test with JRuby 9.4.3.0

test/new_relic/transaction_ignoring_test_cases.rb
remove all JRuby special handling for
`test/new_relic/transaction_ignoring_test_cases.rb`
=> don't special case JRuby for transaction ignoring

test/multiverse/suites/rake/rake_test.rb
note why we skip certain rake tests for JRuby
=> CI: note JRuby rake issues

.github/workflows/pr_closed.yml
=> wip - need clone

.github/workflows/release_notes.yml
Update pull request job to use GitHub CLI after previously used Action was retired.
Resolves #2095
=> Update pull request step

README.md
discuss.newrelic.com is now forum.newrelic.com
=> Update community portal links

test/new_relic/agent/method_tracer_test.rb
- Rename the `push_scope: false` test so that it gets seen as being a test
- Refactor the `push_scope: false` test's assertion to match expected behavior
- Remove the unused `check_time` method
resolves #1491
=> CI: update method tracer tests

CHANGELOG.md
community member thanks for PR 2121
=> CHANGELOG entry for 2121

test/new_relic/healthy_urls_test.rb
HTTParty exists only as a dev dependency for non-CI, so use net/http instead for the healthy urls test
=> CI: use net/http for the healthy urls test

README.md
Update README with new project board information.
=> Add project board information to README

test/multiverse/suites/delayed_job/Envfile
MiniTest 5.19.0 introduced a breaking change. This PR limits MiniTest to the prior version, 5.18.1.
Related: https://github.com/minitest/minitest/issues/960
Full CI run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/5696113798
GitHub Actions when a pull request is made. More details on running the tests locally can be …
=> Pin MiniTest

test/multiverse/suites/roda/roda_instrumentation_test.rb
Fix CI failure with Ruby 3.1.4
=> Roda instrumentation

.github/workflows/label_community_cards.yml
Add kford-newrelic to label_community_cards workflow. This will prevent his tickets from being labeled "community". …
=> Add kford-newrelic to label_community_cards

CHANGELOG.md
* Capitalize "ID" for container ID
* Update bullet description for docker ID
* Add missing PR links
* Add an entry for the Sidekiq error handler fix
=> Changelog edits

.github/actions/simplecov-report/action.yml, .github/workflows/ci.yml
=> Lower threshold branch

.github/workflows/ci_cron.yml
=> CI: test with Ruby 3.3.0-preview3

lib/new_relic/agent/vm.rb, lib/new_relic/agent/vm/c_ruby_vm.rb, test/new_relic/agent/vm/c_ruby_vm_test.rb
Resolves #2321 
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/README.m …
=> renamed MriVM toCRubyVM

test/multiverse/lib/multiverse/envfile.rb, test/new_relic/gemspec_files_test.rb
Issue #2430 exists to resolve these TODOs. Let's call it out specifically in the code to make sure it's known and marked as resolved when these are addressed.
=> Link issue #2430 to Ruby 3.3.0 eval TODOs

lib/new_relic/agent/configuration/security_policy_source.rb
=> Add ai_monitoring to security policy source

.rubocop.yml, lib/new_relic/agent/agent.rb, lib/new_relic/agent/agent_helpers/connect.rb, lib/new_relic/agent/agent_helpers/shutdown.rb, lib/new_relic/agent/agent_helpers/start_worker_thread.rb, lib/new_relic/agent/agent_helpers/startup.rb, lib/new_relic/agent/agent_logger.rb, lib/new_relic/agent/configuration/default_source.rb, lib/new_relic/agent/configuration/environment_source.rb, lib/new_relic/agent/distributed_tracing/distributed_trace_payload.rb, lib/new_relic/agent/new_relic_service.rb, lib/new_relic/agent/serverless_handler.rb, lib/new_relic/control/instance_methods.rb, lib/new_relic/local_environment.rb, test/new_relic/agent/agent/start_test.rb, test/new_relic/agent/agent/start_worker_thread_test.rb, test/new_relic/agent/serverless_handler_test.rb
- Force every harvester to output data immediately
- Support namespaced customer lambda function handler methods
- Enhance tests with integration tests for errors and logs, new helpers, etc.
=> Serverless mode enhancements

README.md
The referenced URL will provide a link to our BugCrowd page when it is live. …
=> We are changing our bug bounty program from HackerOne to BugCrowd. 

.github/workflows/release_notes.yml
=> Add workflow dispatch for tests

lib/new_relic/agent/instrumentation/net_http/instrumentation.rb, lib/new_relic/agent/llm.rb, test/multiverse/suites/net_http/net_http_openai_test.rb
=> Net::HTTP OpenAI check

.github/workflows/slack_notifications.yml
Update gems to reviece slack notifications about when new version releases are published.
=> Update watched gems

test/multiverse/suites/grape/grape_test.rb
ensure that very similar routes still end up with unique transaction names for Grape
=> grape: very similar routes get unique txn names

.github/workflows/ci_jruby.yml
update to the latest stable JRuby
resolves #2609
=> CI: JRuby 9.4.5.0 -> 9.4.7.0

CHANGELOG.md
Added changelog entry for the introduction of instrumentation for dynamodb
=> add changelog entry for dynamodb

lib/new_relic/agent/configuration/default_source.rb
These updates were based on a review in the config doc for 9.10.0
=> Update config descriptions

.github/versions.yml, .github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/ci_jruby.yml, .github/workflows/config_docs.yml, .github/workflows/performance_tests.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/release_notes.yml, .github/workflows/release_pr.yml, .github/workflows/slack_notifications.yml
new Rubies are out, so let's upgrade to the latest setup-ruby sha and start testing with them
=> CI: use Ruby v3.3.3 and v3.1.6

CHANGELOG.md, lib/new_relic/agent/configuration/default_source.rb, lib/new_relic/agent/instrumentation/aws_sqs.rb, lib/new_relic/agent/instrumentation/aws_sqs/chain.rb, lib/new_relic/agent/instrumentation/aws_sqs/instrumentation.rb, lib/new_relic/agent/instrumentation/aws_sqs/prepend.rb, test/multiverse/suites/awssqs/Envfile, test/multiverse/suites/awssqs/awssqs_instrumentation_test.rb, test/multiverse/suites/awssqs/config/newrelic.yml
adds instrumentation for the aws-sdk-sqs gem
resolves https://github.com/newrelic/newrelic-ruby-agent/issues/2592
=> Add SQS instrumentation

.github/versions.yml, .github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/ci_jruby.yml, .github/workflows/config_docs.yml, .github/workflows/performance_tests.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/release_notes.yml, .github/workflows/release_pr.yml, .github/workflows/slack_notifications.yml
Update setup-ruby and target the latest stable JRuby
=> CI: JRuby 9.4.7.0 -> 9.4.8.0

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, test/environments/rails71/Gemfile, test/environments/rails71/Rakefile, test/environments/rails71/app/controllers/application_controller.rb, test/environments/rails71/app/controllers/no_method_controller.rb, test/environments/rails71/config/application.rb, test/environments/rails71/config/boot.rb, test/environments/rails71/config/database.yml, test/environments/rails71/config/environment.rb, test/environments/rails71/config/initializers/test.rb, test/environments/rails71/db/schema.rb
add Rails v7.1 to the list of test environments
resolves #2266
=> add Rails v7.1 test environment

.github/versions.yml, .github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/ci_jruby.yml, .github/workflows/config_docs.yml, .github/workflows/performance_tests.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/release_notes.yml, .github/workflows/release_pr.yml, .github/workflows/slack_notifications.yml
=> CI: test with Ruby v3.3.4

README.md
the NR serverless docs have moved, so update the readme accordingly
=> README: serverless link fix

lib/new_relic/agent/configuration/default_source.rb, lib/new_relic/agent/system_info.rb, lib/new_relic/environment_report.rb, test/new_relic/agent/system_info_test.rb
- Update OS detection for MacOS #2775 
- Update OS detection for Windows #2776
=> Update OS detection for environment report

.github/versions.yml, .github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/ci_jruby.yml, .github/workflows/ci_special.yml, .github/workflows/config_docs.yml, .github/workflows/performance_tests.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/release_notes.yml, .github/workflows/release_pr.yml, .github/workflows/slack_notifications.yml
=> CI: upgrade to Ruby 3.2.5

CHANGELOG.md
=> Add changelog entry for grape/padrino

.github/actions/workflow-conclusion/LICENSE, .github/actions/workflow-conclusion/README.ja.md, .github/actions/workflow-conclusion/README.md, .github/actions/workflow-conclusion/_config.yml, .github/actions/workflow-conclusion/action.yml, .github/actions/workflow-conclusion/package.json, .github/actions/workflow-conclusion/rollup.config.mjs, .github/actions/workflow-conclusion/src/constant.ts, .github/actions/workflow-conclusion/src/fixtures/actions.list.jobs1.json, .github/actions/workflow-conclusion/src/fixtures/actions.list.jobs2.json, .github/actions/workflow-conclusion/src/fixtures/actions.list.jobs3.json, .github/actions/workflow-conclusion/src/fixtures/actions.list.jobs4.json, .github/actions/workflow-conclusion/src/main.ts, .github/actions/workflow-conclusion/src/process.test.ts, .github/actions/workflow-conclusion/src/process.ts, .github/actions/workflow-conclusion/src/setup.ts, .github/actions/workflow-conclusion/tsconfig.json, .github/actions/workflow-conclusion/vite.config.ts, .github/versions.yml, .github/workflows/ci_cron.yml, .github/workflows/ci_special.yml
The action we use to send CI results to Slack, [technote-space/workflow-conclusion-action](https://github.com/technote-space/workflow-conclusion-action), has been archived as of Nov 16, 2023. Moving this to a local copy and updating the Node.js20
Closes #2790
=> Vendor workflow-conclusion

README.md
Minor copy changes to README file to align with NR style guide and improve scannability:
* Removes link to developer site, which will be EOLed at end of August
* Tweaks structure of other install links to make the list more scannable
* Moves Lambda link into other install
* Uses sentence case instead of title case in headings, to match general capitalization guideliens
GitHub Actions when a pull …
=> style(readme): Align with NR style guide, improve structure

CHANGELOG.md
=> Add CHANGELOG for Bundler version update

.github/versions.yml, .github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/ci_jruby.yml, .github/workflows/ci_special.yml, .github/workflows/config_docs.yml, .github/workflows/performance_tests.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/release_notes.yml, .github/workflows/release_pr.yml, .github/workflows/slack_notifications.yml
=> CI: update to Ruby v3.3.5

.github/workflows/slack_notifications.yml
Now, we'll receive alerts when new versions are released.
=> Add rdkafka gem to Slack Notifications

CHANGELOG.md
Add Boolean coercion to CHANGELOG summary.
=> Add boolean update to summary

CHANGELOG.md
Saw a few little things that could use updates
=> Update changelog for 9.14.0 release

lib/new_relic/agent/configuration/default_source.rb
Tweaks for automatic_custom_instrumentation_method_list
=> Update verbiage to match docs website

CHANGELOG.md
Docs team made some changes, now we should match
=> Update 9.14 changelog to match release notes

.github/workflows/security.yml
Attempt to fix failures on scheduled security job
=> Grant security-events write permissions for Trivy

.github/versions.yml, .github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/ci_jruby.yml, .github/workflows/ci_special.yml, .github/workflows/config_docs.yml, .github/workflows/performance_tests.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/release_notes.yml, .github/workflows/release_pr.yml, .github/workflows/security.yml, .github/workflows/slack_notifications.yml
=> update CI to use Ruby v3.2.6

CHANGELOG.md, lib/new_relic/agent/configuration/default_source.rb
Related PRs: 
https://github.com/newrelic/docs-website/pull/19152 
https://github.com/newrelic/docs-website/pull/19151
=> Backport docs writer updates to agent for 9.15.0

.github/versions.yml, .github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/ci_jruby.yml, .github/workflows/ci_special.yml, .github/workflows/config_docs.yml, .github/workflows/performance_tests.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/release_notes.yml, .github/workflows/release_pr.yml, .github/workflows/security.yml, .github/workflows/slack_notifications.yml
Test Ruby 3.3.6 and JRuby 9.4.9.0
🟢 JRuby test results: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/11808169822
=> Update ruby/setup-ruby to 1.202.0

newrelic.yml
Resolves merge conflicts related to updating setup-ruby, ViewComponent, and newrelic.yml text and spacing updates, and CHANGELOG text.
=> Main to dev merge conflicts

CHANGELOG.md
=> Change title to `bugfix`

lib/new_relic/agent/instrumentation/resque.rb, test/multiverse/suites/resque/Envfile
Resolves #2396 
🟢 CI output: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/12403984308
=> Remove Resque resolv-replace require for Ruby 3.4

test/multiverse/suites/rake/Rakefile
Also, the rake tests need logger as well
=> add logger to rake tests

.github/workflows/lambda_release.yml
=> Refactor lambda release action

.github/workflows/lambda_release.yml
=> Use GITHUB_REF_NAME and add 'v' for tagging

.github/versions.yml, .github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/ci_jruby.yml, .github/workflows/ci_special.yml, .github/workflows/config_docs.yml, .github/workflows/lambda_release.yml, .github/workflows/performance_tests.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/release_notes.yml, .github/workflows/release_pr.yml, .github/workflows/slack_notifications.yml
Full CI run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/13445800029
=> Update CI to run Ruby 3.4.2

CHANGELOG.md
=> Add CHANGELOG entry for sidekiq-delay_extensions

.github/versions.yml, .github/workflows/ci.yml, .github/workflows/ci_cron.yml
updates outdated actions/cache
=> update actions cache

lib/new_relic/agent/instrumentation/notifications_subscriber.rb
removes old todo based on yesterdays discussion
=> remove todo

test/multiverse/lib/multiverse/envfile.rb, test/new_relic/gemspec_files_test.rb
=> Remove the TODO workarounds for eval with files

.github/dependabot.yml
=> Update dependabot interval to monthly

lib/tasks/instrumentation_generator/templates/instrumentation.tt
=> Add invocation metric to instrumentation template

.github/workflows/ci_cron.yml
=> Add postgres to ci_cron

CHANGELOG.md, test/new_relic/agent/http_clients/uri_util_test.rb
=> Add Changelog entry and test for URI host fix

.github/workflows/ci_jruby.yml
Run the CI on the latest version of JRuby
Passing JRuby run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/14133954690
=> Bump jruby version to 9.4.12.0

.github/workflows/ci_jruby.yml, test/multiverse/suites/sidekiq/Envfile
Passing CI run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/14133891639
=> Run Sidekiq tests on JRuby

.github/workflows/scripts/rubygems-publish.rb
=> Remove unused API key reference

.github/workflows/release.yml
=> Release 9.18.0

.github/workflows/release.yml
=> Revert full release.yml changes

CHANGELOG.md
Add an entry for #3110, which was submitted by a community member.
=> Add entry for active job community fix

lib/new_relic/agent/configuration/yaml_source.rb, lib/new_relic/agent/instrumentation/action_dispatch_subscriber.rb, lib/new_relic/agent/instrumentation/active_record_helper.rb, lib/new_relic/agent/instrumentation/aws_sdk_kinesis/instrumentation.rb, lib/new_relic/agent/instrumentation/memcache/instrumentation.rb, lib/new_relic/agent/instrumentation/mongodb_command_subscriber.rb, lib/new_relic/agent/instrumentation/redis/constants.rb, lib/new_relic/agent/samplers/memory_sampler.rb, lib/new_relic/agent/tracer.rb, lib/new_relic/agent/transaction/datastore_segment.rb, lib/new_relic/agent/transaction/distributed_tracer.rb, lib/new_relic/agent/transaction/message_broker_segment.rb, lib/new_relic/agent/transaction_time_aggregator.rb, lib/new_relic/constants.rb
fixed: https://github.com/newrelic/newrelic-ruby-agent/issues/2368
- Replaced 'Unknown' with NewRelic::UNKNOWN 
- Replaced 'unknown' with NewRelic::UNKNOWN_LOWER 
- X::UNKNOWN was left intact. Because it is necessary to replace each reference to X::UNKNOWN with NewRelic::UNKNOWN/NewRelic::UNKNOWN_LOWER individually, and the scope of influence is large.
verify your changes don't break existing functionality. These …
=> Consolidate "Unknown" constant values

test/multiverse/README.md
This small PR fixes the `Brewfile` reference in `test/multiverse/README.md`.
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multive …
=> Fix Brewfile source

.github/workflows/scripts/slack_notifications/gem_notifier.rb
https://github.com/newrelic/newrelic-ruby-agent/blob/1105a0f5713d7b31284879100d51af258576abe0/.github/workflows/scripts/slack_notifications/gem_notifier.rb#L62-L68
https://github.com/newrelic/newrelic-ruby-agent/blob/1105a0f5713d7b31284879100d51af258576abe0/.github/workflows/scripts/slack_notifications/gem_notifier.rb#L71-L71
fix the SSRF vulnerability, we need to validate the `source_code_uri` to ensure it is a legitimate and safe URL before using it to construct the `interpolated_url`. Specifically, we should:
1. Restrict the `source_code_uri` to a known, trusted domain (e.g., GitHub).
2. Use a URI parsing library to validate the structure of the URL.
3. Abort or raise an error if the `source_code_uri` does not meet the expected criteria.
The changes will be made in the …
=> fix Server-side request forgery `gem_notifier`

.github/workflows/scripts/slack_notifications/gem_notifier.rb
Use new method name, introduced in #3184
=> Use new method name

.github/actions/run_multiverse/action.yml, .github/actions/run_unit_tests/action.yml, .github/actions/setup_mysql_tests/action.yml, .github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/scripts/setup_bundler, test/multiverse/lib/multiverse/envfile.rb, test/multiverse/suites/ruby_openai/ruby_openai_instrumentation_test.rb
Makes our ci and ci_cron workflows easier to read and modify.
Also, adds more gem versions to the bundler setup that have been making certain test runs fail the first time each time.
ci cron run: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/15715092685
=> Composite actions for CI and Scheduled CI

lib/new_relic/agent/configuration/default_source.rb, lib/tasks/helpers/newrelicyml.rb
=> Update newrelic.yml generator

.github/workflows/label_community_cards.yml
=> Exempt bot from community label

CHANGELOG.md, lib/new_relic/agent/transaction/tracing.rb
resolves https://github.com/newrelic/newrelic-ruby-agent/issues/3246
=> Bugfix: Revert change in logic for thread_starting_span

CHANGELOG.md
Attach PR#'s to CHANGELOG entries.
=> Attach PRs to CHANGELOG entries
